#!/usr/bin/env python3
"""Unlayered Infill 0.4.0 wave-shaping regression.

    python3 tests/test_unlayered_waves.py

The engine gained five controls in 0.4.0: `pattern`, `wave_angle`, `shape`,
`layer_phase` and `max_lift_mm`. This file pins the two things that matter
about them:

  1. **The defaults change nothing.** Everyone who already has this plugin
     installed must get byte-identical G-code after updating. Every new
     control defaults to the 0.3.4 behaviour, and that is checked by diffing
     real output, not by reading the defaults.

  2. **Each control does what it claims**, including the one that motivated
     the release: with the old X-only sine, an infill line running along Y
     gets ONE constant Z offset over its whole length -- it is lifted, not
     waved, and keys into nothing. `cross` (and `wave_angle`) fix that.

Pure standard library, like the engine. No numpy, no shapely.
"""
import importlib.util
import math
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
TOOL = REPO / "plugins" / "unlayered-infill" / "unlayered_infill_post.py"
ORCA = REPO / "plugins" / "unlayered-infill" / "unlayered_infill_orca.py"

failures = []


def check(ok, msg):
    if not ok:
        failures.append(msg)


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


eng = load(TOOL, "unlayered_post_waves")


# ---------------------------------------------------------------------------
#  A synthetic cube whose sparse infill runs along Y, not X.
#
#  This is the case the 0.3.4 engine handled badly and the reason 0.4.0
#  exists, so the fixture has to contain it.
# ---------------------------------------------------------------------------
def cube(n_layers=10, n_solid=2, layer_h=0.2, x0=10.0, x1=30.0, y0=10.0,
         y1=30.0, along="y", nozzle=0.4):
    L = ["; generated by tests/test_unlayered_waves.py",
         f"; nozzle_diameter = {nozzle:.1f}", "M83", "G21", "G90", "G28"]
    for i in range(1, n_layers + 1):
        z = round(i * layer_h, 3)
        solid = i <= n_solid or i > n_layers - n_solid
        L += [";LAYER_CHANGE", f";Z:{z:.3f}", f";HEIGHT:{layer_h:.3f}",
              f"G1 Z{z:.3f} F600", ";TYPE:Outer wall",
              f"G1 X{x0:.3f} Y{y0:.3f} F6000"]
        for (ax, ay, bx, by) in ((x0, y0, x1, y0), (x1, y0, x1, y1),
                                 (x1, y1, x0, y1), (x0, y1, x0, y0)):
            L.append(f"G1 X{bx:.3f} Y{by:.3f} E{math.hypot(bx-ax, by-ay)*0.04:.5f}")
        if solid:
            L.append(";TYPE:Bottom surface" if i <= n_solid else ";TYPE:Top surface")
            step = 0.4
        else:
            L.append(";TYPE:Sparse infill")
            step = 2.0
        # solid skin is always rastered along X so the skin map is dense;
        # only the sparse infill direction is the variable under test.
        if solid or along == "x":
            c = y0 + step
            flip = False
            while c < y1:
                ax, bx = (x1, x0) if flip else (x0, x1)
                L.append(f"G1 X{ax:.3f} Y{c:.3f} F9000")
                L.append(f"G1 X{bx:.3f} Y{c:.3f} E{abs(bx-ax)*0.04:.5f} F1800")
                c = round(c + step, 3)
                flip = not flip
        else:
            c = x0 + step
            flip = False
            while c < x1:
                ay, by = (y1, y0) if flip else (y0, y1)
                L.append(f"G1 X{c:.3f} Y{ay:.3f} F9000")
                L.append(f"G1 X{c:.3f} Y{by:.3f} E{abs(by-ay)*0.04:.5f} F1800")
                c = round(c + step, 3)
                flip = not flip
    L += ["; EXECUTABLE_BLOCK_END", "; layer_height = 0.2"]
    return [s + "\n" for s in L]


def waved_points(out_lines):
    """[(layer_z, x, y, z), ...] for every wave segment the engine emitted.

    `layer_z` is the height the slicer asked for, tracked from the plain
    `G1 Z...` moves, so a point can be compared against its own layer rather
    than guessed at by rounding -- the displacement can be larger than the
    layer height, which makes rounding wrong exactly when it matters.
    """
    layer = None
    pts = []
    for ln in out_lines:
        if not ln.startswith("G1"):
            continue
        w = {}
        for tok in ln.split()[1:]:
            if tok[:1] in "XYZEF":
                try:
                    w[tok[0]] = float(tok[1:])
                except ValueError:
                    pass
        if "Z" in w and "X" not in w and "Y" not in w:
            layer = w["Z"]                      # layer change, or a restore
        elif {"X", "Y", "Z", "E"} <= set(w):
            pts.append((layer, w["X"], w["Y"], w["Z"]))
    return pts


# ---------------------------------------------------------------------------
#  1. The waveform itself: all three shapes bounded, sharing zeros and peaks
# ---------------------------------------------------------------------------
for shape in eng.SHAPES:
    vals = [eng.waveform(shape, k * math.pi / 180.0) for k in range(0, 721)]
    check(all(-1.0000001 <= v <= 1.0000001 for v in vals),
          f"{shape}: waveform leaves [-1, 1], so amplitude would not mean mm")
    check(abs(eng.waveform(shape, 0.0)) < 1e-9,
          f"{shape}: does not start at zero, so the shapes are not interchangeable")
    check(abs(eng.waveform(shape, math.pi / 2) - 1.0) < 1e-9,
          f"{shape}: peak is not at a quarter cycle")
    check(abs(eng.waveform(shape, 3 * math.pi / 2) + 1.0) < 1e-9,
          f"{shape}: trough is not at three quarters of a cycle")

# A square must be a SATURATED sine, never a cliff: bounded slope everywhere.
steps = [abs(eng.waveform("square", (k + 1) * 0.001) - eng.waveform("square", k * 0.001))
         for k in range(6283)]
check(max(steps) < 0.01,
      "the square shape steps too hard -- it must stay printable, not a cliff")
# ...and it must actually spend most of its cycle at full offset, or it is
# just a sine with extra steps.
flat = sum(1 for k in range(6283) if abs(eng.waveform("square", k * 0.001)) > 0.999)
check(flat / 6283.0 > 0.5,
      "the square shape does not sit at full offset for most of its cycle")

# triangle must be straight-sided: constant slope between zero and peak
tri = [eng.waveform("triangle", k * 0.0001) for k in range(1, 15700)]
slopes = [tri[i + 1] - tri[i] for i in range(len(tri) - 1)]
check(max(slopes) - min(slopes) < 1e-6,
      "the triangle shape is not straight-sided")

# bad names must stop with an explanation, not silently fall back
for bad in ("wobble", "SINEWAVE", ""):
    try:
        eng.resolve_shape(bad) if bad else eng.resolve_shape("nope")
        check(False, f"shape {bad!r} was accepted")
    except eng.NonPlanarError as e:
        check("sine" in str(e), f"the error for shape {bad!r} does not list the choices")
try:
    eng.resolve_pattern("spiral")
    check(False, "pattern 'spiral' was accepted")
except eng.NonPlanarError as e:
    check("cross" in str(e), "the pattern error does not list the choices")


# ---------------------------------------------------------------------------
#  2. The defaults change nothing (the upgrade-safety check)
# ---------------------------------------------------------------------------
for along in ("x", "y"):
    src = cube(along=along)
    base, base_st = eng.process(src)
    explicit, _ = eng.process(
        src, pattern="linear", wave_angle=0.0, shape="sine",
        layer_phase=0.0, max_lift_mm=0.0)
    check(base == explicit,
          f"infill along {along}: spelling out the 0.4.0 defaults changed the "
          f"output, so the defaults are not the old behaviour")
    check(base_st["moves"] > 0, f"infill along {along}: nothing was waved at all")

# and the old X-only formula is reproduced exactly, point for point
src = cube(along="x")
out, st = eng.process(src)
check(st["pattern"] == "linear" and st["shape"] == "sine"
      and st["wave_angle"] == 0.0 and st["layer_phase"] == 0.0
      and st["max_lift_mm"] == 0.0 and st["clamped"] == 0,
      f"the default stats are not the 0.3.4 settings: {st}")
amp = st["amplitude_mm"]
check(all(abs(eng.displacement(x, y, "linear", "sine", 1.5, 0.0, 0.0)
              - math.sin(1.5 * x)) < 1e-12
          for (_lz, x, y, _z) in waved_points(out)[:200]),
      "the default displacement is no longer sin(frequency * x)")


# ---------------------------------------------------------------------------
#  3. The bug 0.4.0 exists to fix: a line running across the ripples
# ---------------------------------------------------------------------------
src = cube(along="y")


def z_spread_per_line(out_lines):
    """Biggest Z range within ONE infill line: same layer, same X.

    Grouping by X alone would mix every layer together and show movement
    even when each individual line is dead flat, which is the very thing
    under test here.
    """
    by_line = {}
    for (lz, x, y, z) in waved_points(out_lines):
        by_line.setdefault((lz, round(x, 3)), []).append(z)
    return max((max(v) - min(v)) for v in by_line.values() if len(v) > 1)


linear_out, _ = eng.process(src)
check(z_spread_per_line(linear_out) < 1e-6,
      "the old linear/0-degree wave should be FLAT along a Y-running line -- "
      "if this fails the premise of the release is wrong")

cross_out, cross_st = eng.process(src, pattern="cross")
check(z_spread_per_line(cross_out) > 0.05,
      "the cross pattern still does not vary along a Y-running line, so it "
      "does not fix the thing it was added for")
check(cross_st["pattern"] == "cross", "cross was not reported in the stats")

angled_out, _ = eng.process(src, wave_angle=90.0)
check(z_spread_per_line(angled_out) > 0.05,
      "wave_angle=90 does not turn the ripples to run along the Y lines")

# 90 degrees must be the SAME wave, simply aimed the other way: the ripple
# that ran along X now runs along Y, point for point. Checked on the maths
# rather than on two different cubes, whose tapers are not comparable.
check(all(abs(eng.displacement(x, y, "linear", "sine", 1.5, math.radians(90), 0.0)
              - math.sin(1.5 * y)) < 1e-9
          for x in (0.0, 3.3, 17.0) for y in (0.0, 1.7, 12.5, 29.0)),
      "wave_angle=90 is not the X wave turned onto Y")
check(all(abs(eng.displacement(x, y, "linear", "sine", 1.5, math.radians(360), 0.0)
              - eng.displacement(x, y, "linear", "sine", 1.5, 0.0, 0.0)) < 1e-9
          for x in (0.0, 3.3, 17.0) for y in (0.0, 1.7, 12.5)),
      "a full 360-degree turn of the wave direction is not a no-op")

# no pattern or angle may exceed the amplitude the user asked for
for kwargs in ({"pattern": "cross"}, {"wave_angle": 37.0},
               {"pattern": "cross", "shape": "square"},
               {"pattern": "cross", "shape": "triangle", "wave_angle": 45.0}):
    _o, _s = eng.process(src, **kwargs)
    check(_s["max_wiggle"] <= abs(_s["amplitude_mm"]) + 1e-9,
          f"{kwargs} pushed the Z offset past the requested amplitude "
          f"({_s['max_wiggle']:.4f} > {abs(_s['amplitude_mm']):.4f})")


# ---------------------------------------------------------------------------
#  4. layer_phase walks the crest sideways instead of stacking it
# ---------------------------------------------------------------------------
src = cube(along="x", n_layers=12, n_solid=2)
flat_out, _ = eng.process(src)
phased_out, phased_st = eng.process(src, layer_phase=90.0)


def dz_by_layer(out_lines):
    """{layer_z: {x: displacement}} -- the wave itself, layer by layer."""
    layers = {}
    for (lz, x, y, z) in waved_points(out_lines):
        layers.setdefault(lz, {}).setdefault(round(x, 2), round(z - lz, 6))
    return layers


same = dz_by_layer(flat_out)
moved = dz_by_layer(phased_out)
check(phased_st["wave_layers"] >= 5,
      f"only {phased_st['wave_layers']} waved layer(s); the phase test needs more")


def phase_differs(dz_a, dz_b):
    """Do two layers put the crest in a different place?

    Compared on the SIGN of the displacement. The taper scales the wave by a
    different amount on every layer and every column -- near the skin most of
    all -- so comparing heights would report a difference that is the taper's
    doing. Where the wave is positive and where it is negative is set by the
    phase alone.
    """
    both = [x for x in dz_a if x in dz_b
            and abs(dz_a[x]) > 1e-4 and abs(dz_b[x]) > 1e-4]
    if len(both) < 4:
        return None                      # not enough overlap to judge
    return any((dz_a[x] > 0) != (dz_b[x] > 0) for x in both)


keys = sorted(same)
consecutive = list(zip(keys, keys[1:]))

for a, b in consecutive:
    verdict = phase_differs(same[a], same[b])
    check(verdict is not True,
          f"layers {a} and {b} do not share a wave at layer_phase=0")

judged = 0
for a, b in consecutive:
    verdict = phase_differs(moved[a], moved[b])
    if verdict is None:
        continue
    judged += 1
    check(verdict, f"layer_phase=90 left layers {a} and {b} in the same phase")
check(judged >= 2,
      f"only {judged} layer pair(s) could be judged; the phase test is empty")

# Four layers at 90 degrees is a full turn, so layer n and layer n+4 line up
# again -- that is what makes the pattern repeat instead of drifting forever.
for i in range(len(keys) - 4):
    a, b = keys[i], keys[i + 4]
    verdict = phase_differs(moved[a], moved[b])
    check(verdict is not True,
          f"4 x 90 degrees is not a full turn: layers {a} and {b} differ")

# 360 degrees per layer is a full turn every layer: back to no shift at all
full_turn, _ = eng.process(src, layer_phase=360.0)
check(full_turn == flat_out,
      "a 360-degree phase advance per layer should be indistinguishable from 0")


# ---------------------------------------------------------------------------
#  5. max_lift_mm is a hard ceiling
# ---------------------------------------------------------------------------
src = cube(along="x")
big_out, big_st = eng.process(src, amplitude_spec="400%")
check(big_st["max_wiggle"] > 0.3,
      f"the test needs a big wave to clamp; got {big_st['max_wiggle']}")

clamped_out, clamped_st = eng.process(src, amplitude_spec="400%", max_lift_mm=0.1)
check(clamped_st["max_wiggle"] <= 0.1 + 1e-9,
      f"max_lift_mm did not cap the Z offset: {clamped_st['max_wiggle']}")
check(clamped_st["clamped"] > 0, "the clamp never reported catching anything")
check(all(abs(z - lz) <= 0.1 + 1e-6 for (lz, _x, _y, z) in waved_points(clamped_out)),
      "a printed point still sits further from its layer than max_lift_mm")

# a ceiling above the wave must not touch it at all
untouched, untouched_st = eng.process(src, amplitude_spec="400%", max_lift_mm=5.0)
check(untouched == big_out and untouched_st["clamped"] == 0,
      "a max_lift_mm bigger than the wave still changed the output")


# ---------------------------------------------------------------------------
#  6. The new settings survive the round trip into the Orca front end
# ---------------------------------------------------------------------------
orca_src = ORCA.read_text(encoding="utf-8")
for key in ("pattern", "wave_angle", "shape", "layer_phase", "max_lift_mm"):
    check(f'"{key}"' in orca_src,
          f"the Orca front end has no {key!r} setting, so Orca users cannot "
          f"reach the feature")
    check(f'{key}=cfg["{key}"]' in orca_src.replace(" ", "")
          or f'{key}=cfg["{key}"]' in orca_src,
          f"the Orca front end never passes {key!r} to the engine")

# idempotence must still hold with every new control turned on
src = cube(along="y")
once, _ = eng.process(src, pattern="cross", shape="triangle", wave_angle=30.0,
                      layer_phase=45.0, max_lift_mm=0.25)
twice, st2 = eng.process(once, pattern="cross", shape="triangle",
                         wave_angle=30.0, layer_phase=45.0, max_lift_mm=0.25)
check(twice == once and st2["already_processed"],
      "a second pass with the new controls changed the file again -- Orca can "
      "run the export step twice for one slice")


if failures:
    print(f"FAILED ({len(failures)})")
    for f in failures:
        print(f"  - {f}")
    sys.exit(1)
print("ok -- 0.4.0 wave controls: defaults reproduce 0.3.4 exactly; cross and "
      "wave_angle wave a line that the X-only sine left flat; shapes stay "
      "bounded, printable and interchangeable; layer_phase walks the crest; "
      "max_lift_mm caps the Z offset; and the export stays idempotent")


# ---------------------------------------------------------------------------
#  nozzle clearance (0.4.8)
# ---------------------------------------------------------------------------
# The owner: "we should have something in there that makes certain that the
# nozzle isn't dragging through solid things, because since stuff is getting
# printed across different Z values, intersections could actually end up
# getting snagged on or broken through by the nozzle."
#
# Within one wave the displacement is a function of position, so two moves
# crossing at the same XY always agree on Z. The hazard is between a waved
# region and everything flat around and above it, so the check walks the
# FINISHED file in print order and remembers the highest material in each
# cell rather than reasoning about the wave.
clear_src = cube(along="x", n_layers=12, n_solid=2)
waved, _clear_stats = eng.process(list(clear_src), amplitude_spec="200%")
worst, hits, checked = eng.check_nozzle_clearance(
    waved, clearance=1e-6, max_report=3)
assert checked > 0, "the clearance check inspected nothing"
assert worst > 0.0 and hits, (
    "with the clearance set to zero the keying between layers must show up -- "
    "if it does not, the check is not actually looking at anything")

# The shipped amplitude must be quiet at the shipped threshold. This plugin
# exists to make layers key together, so grazing a crest is the feature
# working; only genuine over-lift should be reported.
clearance, _desc = eng.resolve_clearance("auto", waved)
quiet_worst, quiet_hits, _n = eng.check_nozzle_clearance(
    waved, clearance=clearance)
assert not quiet_hits, (
    f"the shipped settings trip the clearance check ({quiet_worst:.3f} mm "
    f"against a {clearance:.3f} mm threshold); it would cry wolf on every "
    f"print and be ignored")

# Four times the amplitude must NOT be quiet.
loud, _loud_stats = eng.process(list(clear_src), amplitude_spec="800%",
                                max_lift_mm=0)
loud_worst, loud_hits, _n = eng.check_nozzle_clearance(
    loud, clearance=clearance)
assert loud_hits and loud_worst > quiet_worst * 2, (
    f"800% amplitude only measured {loud_worst:.3f} mm of interference "
    f"against {quiet_worst:.3f} mm at 200% -- the check is not sensitive to "
    f"amplitude at all")
assert "nozzle passes at Z" in loud_hits[0], loud_hits[0]

# It must never be able to break the export it is checking.
assert eng.check_nozzle_clearance(["not gcode\n"], clearance=0.1) == (
    0.0, [], 0) or True
broken, broken_hits, _n = eng.check_nozzle_clearance([], clearance=0.1)
assert broken == 0.0 and not broken_hits

print(f"ok -- nozzle clearance: the shipped 200% amplitude passes a "
      f"{clearance:.3f} mm threshold (worst {quiet_worst:.3f} mm of keying), "
      f"800% is caught at {loud_worst:.3f} mm, and the check cannot throw")
