#!/usr/bin/env python3
"""Prove the standalone Unlayered Infill tool actually changes G-code.

    python3 tests/test_post_script.py

`test_installer.py` checks the *packaging* contract. This one checks the thing
the owner actually cares about: feed it sliced G-code and wavy G-code comes
out, with the extrusion conserved and the nozzle put back where it belongs.

There is no printer and no OrcaSlicer here, so the input is synthetic: a small
cube written the way OrcaSlicer writes one (relative E, `;TYPE:` section
markers, `;HEIGHT:`/`;Z:` comments), with solid skin top and bottom and sparse
infill in between. That is exactly the shape the engine keys off.
"""
import importlib.util
import math
import pathlib
import re
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
TOOL = REPO / "plugins" / "unlayered-infill" / "unlayered_infill_post.py"
PLUGIN = REPO / "plugins" / "unlayered-infill" / "unlayered_infill_orca.py"

failures = []


def check(cond, msg):
    if not cond:
        failures.append(msg)
    return cond


# --------------------------------------------------------------------------
# A synthetic sliced cube
# --------------------------------------------------------------------------
def fake_cube(n_layers=10, n_solid=2, layer_h=0.2, x0=10.0, x1=30.0,
              y0=10.0, y1=30.0, relative_e=True, nozzle=0.4):
    """Orca-shaped G-code: solid skin top and bottom, sparse infill between."""
    L = ["; generated by tests/test_post_script.py",
         f"; nozzle_diameter = {nozzle:.1f}", "M104 S210", "M109 S210",
         "M83" if relative_e else "M82", "G21", "G90", "G28"]
    for i in range(1, n_layers + 1):
        z = round(i * layer_h, 3)
        solid = i <= n_solid or i > n_layers - n_solid
        L += [";LAYER_CHANGE", f";Z:{z:.3f}", f";HEIGHT:{layer_h:.3f}",
              f"G1 Z{z:.3f} F600"]
        # a perimeter so the layer is not infill-only
        L.append(";TYPE:Outer wall")
        L.append(f"G1 X{x0:.3f} Y{y0:.3f} F6000")
        for (ax, ay, bx, by) in ((x0, y0, x1, y0), (x1, y0, x1, y1),
                                 (x1, y1, x0, y1), (x0, y1, x0, y0)):
            L.append(f"G1 X{bx:.3f} Y{by:.3f} E{math.hypot(bx-ax, by-ay)*0.04:.5f}")
        if solid:
            L.append(";TYPE:Bottom surface" if i <= n_solid else ";TYPE:Top surface")
            step = 0.4
        else:
            L.append(";TYPE:Sparse infill")
            step = 2.0
        y = y0 + step
        flip = False
        while y < y1:
            ax, bx = (x1, x0) if flip else (x0, x1)
            L.append(f"G1 X{ax:.3f} Y{y:.3f} F9000")          # travel, no E
            L.append(f"G1 X{bx:.3f} Y{y:.3f} E{abs(bx-ax)*0.04:.5f} F1800")
            y = round(y + step, 3)
            flip = not flip
    L.append("; EXECUTABLE_BLOCK_END")
    L.append("; layer_height = 0.2")
    return "".join(s + "\n" for s in L)


def load_tool():
    spec = importlib.util.spec_from_file_location("unlayered_post", TOOL)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def total_e(text):
    return sum(float(m.group(1)) for m in re.finditer(r"(?m)^G1 .*?\sE(-?[\d.]+)", text))


if not TOOL.exists():
    print(f"FAILED: {TOOL} does not exist")
    sys.exit(1)

tool = load_tool()

# --------------------------------------------------------------------------
# 1. one engine, two front ends -- the copies must not drift
# --------------------------------------------------------------------------
import ast  # noqa: E402

plug_src = PLUGIN.read_text(encoding="utf-8")
m = re.search(r'^_NONPLANAR_CORE_SRC = (".*")$', plug_src, re.MULTILINE)
if check(m is not None, "could not find _NONPLANAR_CORE_SRC in the plugin"):
    inlined = ast.literal_eval(m.group(1))
    tool_src = TOOL.read_text(encoding="utf-8")
    start = tool_src.find("# --- BEGIN nonplanar_core")
    end = tool_src.find("# --- END nonplanar_core")
    check(start != -1 and end != -1,
          "the standalone tool lost its BEGIN/END nonplanar_core markers")
    if start != -1 and end != -1:
        embedded = tool_src[tool_src.index("\n", start) + 1:end]
        check(embedded == inlined,
              "the engine in unlayered_infill_post.py has drifted from the copy "
              "inlined in unlayered_infill_orca.py -- copy one into the other so "
              "a fix lands in both front ends")

check(tool.TOOL_VERSION == re.search(r'^PLUGIN_VERSION\s*=\s*"([^"]+)"',
                                     plug_src, re.MULTILINE).group(1),
      "the standalone tool's version disagrees with the plugin's")

# --------------------------------------------------------------------------
# 2. it actually waves a normal sliced cube
# --------------------------------------------------------------------------
src = fake_cube()
lines = src.splitlines(keepends=True)
out_lines, stats = tool.process(lines)
out_text = "".join(out_lines)

check(stats["moves"] > 0,
      f"no infill moves were waved on a plain cube -- the tool does nothing "
      f"(stats: {stats})")
check(stats["segments"] > stats["moves"],
      "each waved move should become several segments")
check(stats["sections"] > 0, "no sparse-infill sections were recognised")
check(stats["solid_layers"] > 0, "no solid skin was recognised")
amp_mm, _ = tool.resolve_amplitude(tool.DEFAULT_AMPLITUDE, lines)
check(0 < stats["max_wiggle"] <= abs(amp_mm) + 1e-9,
      f"max Z shift {stats['max_wiggle']} should be >0 and within the "
      f"amplitude ({amp_mm} mm)")
check(out_text != src, "the output is identical to the input")
check(out_text.startswith(tool.MARKER_PREFIX),
      "the output is not stamped, so a second pass would double the wave")

# the wave must actually move Z on infill moves
waved = [l for l in out_lines if l.startswith("G1 X") and " Z" in l and " E" in l]
check(len(waved) >= stats["segments"] * 0.9,
      f"expected ~{stats['segments']} extruding moves carrying a Z, saw {len(waved)}")

# --------------------------------------------------------------------------
# 2b. the defaults the owner asked for: amplitude as a share of layer height,
#     grid columns one nozzle wide
# --------------------------------------------------------------------------
check(str(tool.DEFAULT_AMPLITUDE).endswith("%"),
      f"DEFAULT_AMPLITUDE is {tool.DEFAULT_AMPLITUDE!r}; it must be a share of "
      f"layer height so it keeps meaning when layer height changes")
check(tool.DEFAULT_CELL_MM == "auto",
      f"DEFAULT_CELL_MM is {tool.DEFAULT_CELL_MM!r}; it must follow the nozzle")

# the owner's own worked example: 200% of a 0.3 mm layer is 0.6 mm
amp, desc = tool.resolve_amplitude("200%", [";HEIGHT:0.300\n"] * 3)
check(abs(amp - 0.6) < 1e-9, f"200% of 0.3 mm should be 0.600 mm, got {amp}")
check("0.300" in desc and "0.600" in desc,
      f"the description should show the arithmetic: {desc!r}")
# and it tracks layer height instead of being a fixed number
amp2, _ = tool.resolve_amplitude("200%", [";HEIGHT:0.100\n"] * 3)
check(abs(amp2 - 0.2) < 1e-9,
      f"the same 200% on a 0.1 mm layer should be 0.200 mm, got {amp2}")
# plain mm and multiples still work
check(abs(tool.resolve_amplitude("-0.25", lines)[0] + 0.25) < 1e-9,
      "plain mm amplitudes stopped working")
check(abs(tool.resolve_amplitude("2x", [";HEIGHT:0.300\n"] * 3)[0] - 0.6) < 1e-9,
      "the 'x' multiplier form stopped working")

check(tool.detect_nozzle_diameter(["; nozzle_diameter = 0.6\n"]) == 0.6,
      "nozzle diameter was not read from the G-code")
check(tool.detect_nozzle_diameter(["; nozzle_diameter = 0.4,0.4\n"]) == 0.4,
      "a multi-extruder nozzle_diameter list was not handled")
check(tool.detect_nozzle_diameter(["; nozzle_diameter = 99\n"]) is None,
      "an implausible nozzle diameter should be rejected, not used")
check(tool.detect_nozzle_diameter(["; no nozzle here\n"]) is None,
      "nozzle detection should return None when the G-code is silent")

cell, cdesc = tool.resolve_cell_mm("auto", ["; nozzle_diameter = 0.6\n"])
check(cell == 0.6 and "nozzle" in cdesc,
      f"'auto' grid did not follow the nozzle: {cell} / {cdesc!r}")
check(tool.resolve_cell_mm("auto", ["; nothing\n"])[0] == tool.FALLBACK_CELL_MM,
      "'auto' should fall back to the default nozzle when the G-code is silent")
check(tool.resolve_cell_mm(1.2, [])[0] == 1.2, "an explicit grid size was ignored")

# the grid really is built at nozzle resolution on a 0.6 mm-nozzle file
big = fake_cube(nozzle=0.6)
_, s6 = tool.process(big.splitlines(keepends=True))
check(abs(s6["cell_mm"] - 0.6) < 1e-9,
      f"a 0.6 mm nozzle should give 0.6 mm columns, got {s6['cell_mm']}")
check(s6["nozzle_mm"] == 0.6, "the nozzle was not reported in the stats")
# a finer nozzle must give a finer grid -- i.e. more columns for the same part
_, s4 = tool.process(fake_cube(nozzle=0.4).splitlines(keepends=True))
check(s4["solid_columns"] > s6["solid_columns"],
      f"a 0.4 mm nozzle should produce more columns than a 0.6 mm one "
      f"({s4['solid_columns']} vs {s6['solid_columns']}) -- the grid is not "
      f"actually following the nozzle")

# --------------------------------------------------------------------------
# 3. extrusion is conserved -- no systematic over/under-extrusion
# --------------------------------------------------------------------------
before, after = total_e(src), total_e(out_text)
check(abs(before - after) < 1e-3,
      f"extrusion changed: {before:.5f} in, {after:.5f} out (difference "
      f"{after - before:+.5f}). A wavy file must print the same volume.")

# --------------------------------------------------------------------------
# 4. the nozzle is put back on the layer plane when infill ends
# --------------------------------------------------------------------------
cur_z = None
in_infill = False
bad_exit = 0
for line in out_lines:
    if line.startswith(";Z:"):
        cur_z = float(line[3:])
    name = tool.section_name(line)
    if name is not None:
        if in_infill and not tool.is_infill_section(name):
            in_infill = False
        elif tool.is_infill_section(name):
            in_infill = True
        continue
    if in_infill and line.startswith("G1 Z") and cur_z is not None:
        # the restore line the engine emits
        got = float(re.search(r"Z(-?[\d.]+)", line).group(1))
        if abs(got - cur_z) > 1e-6:
            bad_exit += 1
check(bad_exit == 0,
      f"{bad_exit} Z-restore line(s) did not return to the layer height")
check("G1 Z" in out_text, "no Z-restore lines were emitted at all")

# --------------------------------------------------------------------------
# 5. running twice is a no-op (Orca can call the export step twice)
# --------------------------------------------------------------------------
again_lines, again_stats = tool.process(out_lines)
check(again_stats["already_processed"] is True,
      "a second pass did not detect the stamp")
check("".join(again_lines) == out_text, "a second pass changed the file")

# The stamp text is a cross-version promise, not an implementation detail: a
# file waved by an older build must still be recognised by a newer one. Rename
# it and every previously-processed file silently gets waved a second time,
# doubling the displacement.
check(tool.MARKER_PREFIX == "; unlayered-infill",
      f"MARKER_PREFIX changed to {tool.MARKER_PREFIX!r}. G-code stamped by an "
      f"earlier version would no longer be recognised and would be waved twice.")
old_stamped = f"; unlayered-infill v0.0.1-ancient\n" + src
_, old_stats = tool.process(old_stamped.splitlines(keepends=True))
check(old_stats["already_processed"] is True,
      "a file stamped by an older version was not recognised as already done")

# --------------------------------------------------------------------------
# 6. absolute E is refused rather than corrupted
# --------------------------------------------------------------------------
abs_src = fake_cube(relative_e=False).splitlines(keepends=True)
try:
    tool.process(abs_src)
    check(False, "absolute-E (M82) G-code was accepted; it would be corrupted")
except tool.NonPlanarError as e:
    check("relative" in str(e).lower(),
          "the absolute-E refusal does not explain the fix")

# --------------------------------------------------------------------------
# 7. the file on disk: input untouched, output beside it, --inplace rewrites
# --------------------------------------------------------------------------
with tempfile.TemporaryDirectory() as tmp:
    d = pathlib.Path(tmp)
    src_file = d / "cube.gcode"
    src_file.write_text(src, encoding="utf-8")

    r = subprocess.run([sys.executable, str(TOOL), str(src_file)],
                       capture_output=True, text=True)
    check(r.returncode == 0, f"CLI exited {r.returncode}: {r.stderr[:300]}")
    check(src_file.read_text(encoding="utf-8") == src,
          "the input file was modified without --inplace")
    produced = d / "cube_unlayered.gcode"
    check(produced.exists(), f"no output file written; stdout was:\n{r.stdout}")
    if produced.exists():
        check(produced.read_text(encoding="utf-8") == out_text,
              "the CLI output differs from the library result")
    check("infill moves waved" in r.stdout, "the CLI did not report what it did")

    # --dry-run writes nothing
    src2 = d / "cube2.gcode"
    src2.write_text(src, encoding="utf-8")
    r = subprocess.run([sys.executable, str(TOOL), "--dry-run", str(src2)],
                       capture_output=True, text=True)
    check(r.returncode == 0, "dry run failed")
    check(not (d / "cube2_unlayered.gcode").exists(), "--dry-run wrote a file")
    check(src2.read_text(encoding="utf-8") == src, "--dry-run modified the input")

    # --inplace rewrites the file itself (what Orca's post-processing needs)
    src3 = d / "cube3.gcode"
    src3.write_text(src, encoding="utf-8")
    r = subprocess.run([sys.executable, str(TOOL), "--inplace", str(src3)],
                       capture_output=True, text=True)
    check(r.returncode == 0, f"--inplace exited {r.returncode}: {r.stderr[:300]}")
    check(src3.read_text(encoding="utf-8") == out_text,
          "--inplace did not rewrite the file with the waved version")
    check(not (d / "cube3_unlayered.gcode").exists(),
          "--inplace should not also write a sidecar copy")

    # a missing file is a clean error, not a traceback
    r = subprocess.run([sys.executable, str(TOOL), str(d / "nope.gcode")],
                       capture_output=True, text=True)
    check(r.returncode != 0 and "Traceback" not in r.stderr,
          "a missing input file should fail cleanly, not crash")

# --------------------------------------------------------------------------
# 8. an all-wall part (no infill) explains itself instead of failing silently
# --------------------------------------------------------------------------
thin = "\n".join(["M83", ";Z:0.200", ";HEIGHT:0.200", ";TYPE:Outer wall",
                  "G1 X10 Y10 F6000", "G1 X30 Y10 E0.8"]) + "\n"
_, thin_stats = tool.process(thin.splitlines(keepends=True))
check(thin_stats["moves"] == 0, "a wall-only file should wave nothing")
report = "\n".join(tool.describe(thin_stats))
check("NOTHING WAS CHANGED" in report and "infill" in report.lower(),
      "the report does not explain why nothing happened")

# --------------------------------------------------------------------------
if failures:
    print(f"FAILED ({len(failures)})")
    for f in failures:
        print(f"  - {f}")
    sys.exit(1)

print(f"ok -- standalone tool waves real G-code "
      f"({stats['moves']} moves -> {stats['segments']} segments, "
      f"max Z shift {stats['max_wiggle']:.3f} mm, extrusion conserved to "
      f"{abs(after - before):.2e} mm)")
