# /// script
# requires-python = ">=3.12"
# dependencies = []
#
# [tool.orcaslicer.plugin]
# name = "Unlayered Infill"
# description = "Non-planar sparse infill: rides a sine wave in Z so successive layers interlock instead of stacking as clean planes, tapering to flat where it meets the solid skin. | What's new in v0.4.5: Your settings are now backed up by the plugin itself, so they survive the Config panel being wiped."
# author = "Unlayered Infill plugin lane"
# version = "0.4.5"
# ///
"""Unlayered Infill for OrcaSlicer — non-planar sparse infill.

Layer-aligned infill fails along the same planes the perimeters do, so a part
is only as strong as its weakest layer boundary. This rewrites sparse-infill
moves to ride a sine wave in Z, `dz = amplitude * scale * sin(f * x)`, so each
layer's infill keys into the one below. `scale` tapers to zero as the infill
approaches the solid skin above or below, leaving the skins flat.

WHY THIS ONE IS A POST-PROCESSOR
  The other plugins in this repo inject geometry at `Step.posSlice` and let
  Orca own flow, speed and cooling — see plugins/wave-overhangs/README.md
  argument. Non-planar infill is the one case where that cannot work: a slice
  polygon is planar by construction, so there is no way to express a wave in Z
  through the slicing seam. This plugin therefore runs at
  `Step.psGCodePostProcess`, the supported seam for rewriting the exported
  file, where `ctx.gcode_path` points at the working G-code.

SETUP -- ONE preset field
  Process preset > Others > Slicing Pipeline Plugin > "Unlayered Infill".

  That single field is all there is. Both Print.cpp (geometry steps) and
  PostProcessor.cpp (the G-code export step this plugin uses) resolve the
  same preset capability refs, so selecting the capability once wires up
  every step. This plugin returns success() immediately for all the steps
  it does not care about.

  Slice once, then run "Unlayered Infill - Check setup": it reports whether
  the export step actually ran, so you never have to guess.

REQUIREMENTS
  * Relative extrusion (`M83`). Splitting moves under absolute E (`M82`) would
    corrupt the file, so the plugin refuses rather than produce bad G-code.
  * Pure standard library — no numpy, no shapely, no first-run dependency
    install, and no restart after installing.

Engine adapted from nonPlanarInfill.py, Copyright (c) 2025 Roman Tenger
(TenTech), GPL-3.0 — https://github.com/TengerTechnologies/NonPlanarInfill.
This file is likewise GPL-3.0. The five behavioural fixes relative to that
tool are documented in the engine source between the
`BEGIN/END nonplanar_core` markers of unlayered_infill_post.py, and pinned by
tests/test_post_script.py.
"""
import json
import os
import time
# `traceback` is imported HERE, not where it is used. It is only needed on an
# error path inside a capability call -- which is exactly where Orca's audit
# hook is watching every file open, so a first-use import there can be denied.
# See docs/ORCA-PLUGIN-FACTS.md, "The audit hook".
import traceback

import orca

# The version this file was built as. Kept in lockstep with the PEP 723 header
# at the top (tests/test_installer.py fails if they drift), so everything that
# reports a version at runtime reports the one actually running.
PLUGIN_VERSION = "0.4.5"

# --- BEGIN changelog (generated by tools/sync_changelog.py) ---
CHANGELOG_RECENT = """\
v0.4.5  (2026-10-02)
   * Your settings are now backed up by the plugin itself, so they
     survive the Config panel being wiped. Every run saves a copy of the
     values in force; if the panel ever comes back reset, set
     restore_backup to true and slice once to put them back, and the
     flag turns itself off.
   * The backup is a short history, not one slot, because the wipe is
     followed by a run that would otherwise overwrite the only copy with
     the defaults that just replaced your settings. Why this was needed.
     OrcaSlicer owns the settings file and keeps it in one global place,
     so a plugin cannot stop it being reset -- "Restore defaults", a
     reinstall, a data-directory or profile change, an Orca upgrade.
     Ordinary version-to-version migration already preserved everything
     (it merges this build's new keys into your saved copy and never
     touches a value you set), but there was no protection against the
     file simply going away. Nothing is restored automatically,
     deliberately. Silently putting old settings back would make
     "Restore defaults" impossible, and a plugin that overrules an
     explicit action is worse than one that loses a value. So the backup
     sits there, Check setup prints exactly what it holds, and
     restore_backup is a one-shot undo you ask for. The one case where a
     value genuinely cannot carry over is a setting this build no longer
     has. Those are dropped on the way back in rather than resurrected
     as dead keys.

v0.4.4  (2026-10-02)
   * wave_angle: "auto" reads fill_angle from the export and runs the
     ripples square across your infill — which is where they do the most
     work, since a line parallel to the ripples never crosses one.
   * max_lift_mm: "auto" caps the Z offset at 1.5 layer heights. Check
     setup and the log now print what each auto resolved to, with the
     reasoning — frequency : 0.997 ripples/mm (auto: one ripple every
     10.5 x 0.60 mm nozzle widths) — rather than echoing the word "auto"
     back at you.

v0.4.3  (2026-10-02)
"""
# --- END changelog ---

# nonplanar_core is inlined by build.py for the single-file install; during
# tests and development it is imported from src/ next to this file.
import sys as _sys, types as _types
# nonplanar_core.py inlined by build.py (single-file plugin). Registered in
# sys.modules so anything that resolves the module by name still works.
_NONPLANAR_CORE_SRC = "\"\"\"Non-planar infill engine: pure text in, pure text out, stdlib only.\n\nAdapted from `nonPlanarInfill.py`, Copyright (c) 2025 Roman Tenger (TenTech),\nGPL-3.0 \u2014 https://github.com/TengerTechnologies/NonPlanarInfill \u2014 by way of the\n\"Non-Planar Infill Tool\" kept verbatim at\n`tools/nonplanar-infill-tool/nonplanar_infill_tool.py`.\n\nThe idea is unchanged: inside sparse-infill sections, split each extrusion into\nshort segments and ride a sine wave in Z, `dz = amplitude * scale * sin(f * x)`,\nwith `scale` tapering to zero as the infill approaches the solid skin above or\nbelow it. Successive layers then interlock instead of stacking as clean planes.\n\nFive behaviours differ from the reference, each pinned by a test in\n`tests/test_post_script.py`:\n\n1. **Extrusion is attached to the right move.** In G-code the `E` on a line\n   describes the move that *ends* at that line's coordinates. The reference\n   read `(x, y)` off the current line as the segment *start* and `(x, y)` off\n   the next line as the end, so every stroke was printed with its neighbour's\n   extrusion. On a plain rectilinear layer that under-extrudes the long infill\n   strokes by ~44% and over-extrudes the short repositioning moves.\n\n2. **No duplicated points.** `segment_line()` returned both endpoints, so each\n   emitted stroke re-stated the previous stroke's final point *with a share of\n   the extrusion* \u2014 a zero-length extruding move, i.e. a blob, at every\n   junction (44 of them in a ten-layer test cube).\n\n3. **Z is restored on the way out.** The reference left the nozzle at whatever\n   displaced Z the last wave segment reached. Anything printed afterwards in\n   the same layer \u2014 gap fill, a top surface, the wipe \u2014 ran at that wrong\n   height until the next layer change reset it.\n\n4. **Orca's skins are recognised.** Solid layers were matched on\n   `\"solid infill\"` only. OrcaSlicer and Bambu Studio label the outermost\n   skins `;TYPE:Top surface` and `;TYPE:Bottom surface`, so the real bottom\n   was never found and the taper measured from the build plate instead. That\n   makes the wave far too aggressive right next to the bottom skin.\n\n5. **The taper can't inverate.** `next_top_layer` kept a stale value once the\n   nozzle rose above the topmost solid layer, which made `d_top` negative and\n   flipped the wave's sign. Infill that isn't bracketed by solid above *and*\n   below now simply gets no wave.\n\nSection markers are matched on `;TYPE:` lines only, and case-insensitively:\nPrusaSlicer writes `;TYPE:Internal infill`, Orca `;TYPE:Sparse infill`.\n\"\"\"\nimport bisect\nimport math\nimport re\n# Imported HERE, at module load, and never lazily inside a capability call.\n# OrcaSlicer's audit hook is off while a plugin module is being imported and\n# ON during a capability call, where every file open is audited. A first-use\n# `import statistics` inside the export step would therefore be an audited\n# read of the stdlib from inside the audit scope -- the same shape as the\n# numpy failure in OrcaSlicer issue #15944. See docs/ORCA-PLUGIN-FACTS.md,\n# \"The audit hook\".\nfrom statistics import multimode\n\nTYPE_PREFIX = \";type:\"\nINFILL_MARKERS = (\"internal infill\", \"sparse infill\")\n# \"internal solid infill\" contains \"solid infill\"; Orca/Bambu name the outer\n# skins \"top surface\" / \"bottom surface\", which the reference missed.\nSOLID_MARKERS = (\"solid infill\", \"top surface\", \"bottom surface\")\n\n# Amplitude is a share of the LAYER HEIGHT by default, not a fixed mm value:\n# \"200%\" on a 0.3 mm layer is 0.6 mm, and the same setting still makes sense\n# after you change layer height. Plain mm (\"-0.2\") and multiples (\"2x\") are\n# still accepted. Sign only phase-shifts a sine wave, so it barely matters.\nDEFAULT_AMPLITUDE = \"200%\"\nDEFAULT_FREQUENCY = 1.5\nDEFAULT_SEGMENT_MM = 1.0\n# XY resolution of the solid-column map. \"auto\" means one column per nozzle\n# diameter, read from the G-code -- the finest grid that still corresponds to\n# something the printer can actually lay down.\nDEFAULT_CELL_MM = \"auto\"\nFALLBACK_CELL_MM = 0.6       # used when the G-code does not name the nozzle\nDEFAULT_BLEND_MM = 2.0       # smooth the taper across this radius of columns\n\n# --- the shape of the wave -------------------------------------------------\n#\n# Up to 0.3.4 the displacement was always `sin(frequency * x)`: a ripple that\n# varies along X and along X only. That has one real weakness. An infill line\n# running along Y crosses no ripple at all -- every point on it has the same\n# X, so it gets one constant Z offset over its whole length. It is lifted,\n# not waved, and it keys into nothing. With the usual 45/135-degree infill\n# that costs little, but with 0/90-degree infill, or any line that happens to\n# run across the ripples, half the infill does no interlocking work.\n#\n# `pattern` fixes that, `angle` aims it, `shape` changes the profile, and\n# `layer_phase` stops every layer from being a copy of the one below.\n# Defaults reproduce 0.3.4 output exactly.\nPATTERNS = (\"linear\", \"cross\")\nDEFAULT_PATTERN = \"linear\"\n#   linear  ripples that vary along one axis only -- the 0.3.4 behaviour.\n#   cross   an egg-crate: ripples along BOTH axes at once, so a line running\n#           in any direction still goes up and down. Costs nothing extra and\n#           interlocks in two directions instead of one.\n\nDEFAULT_WAVE_ANGLE = 0.0     # degrees, counter-clockwise, 0 = ripples along X\n\nSHAPES = (\"sine\", \"triangle\", \"square\")\nDEFAULT_SHAPE = \"sine\"\n#   sine      the smooth classic.\n#   triangle  straight ramps into sharp peaks -- steeper flanks for the same\n#             peak height, so the layers key together harder.\n#   square    flat crests joined by short ramps: most of the infill sits at\n#             full offset instead of passing through it. It is a SATURATED\n#             sine, never a true square -- a vertical Z step is not printable.\nSQUARE_GAIN = 3.0            # how hard the sine is driven before clipping\n\nDEFAULT_LAYER_PHASE = 0.0    # degrees of extra phase per infill layer\n#   0 puts the crest of the wave at the same XY on every layer, so the part\n#   keeps a column of crests. Advancing the phase a little each layer makes\n#   the crests walk sideways, which is what actually braids the layers.\n#   180 puts each layer's crest exactly over the layer below's trough.\n\nDEFAULT_MAX_LIFT_MM = 0.0    # 0 = no clamp\n#   A hard ceiling on the Z displacement, in millimetres, whatever the\n#   amplitude and taper work out to. This is a safety net: \"200%\" of a\n#   0.3 mm layer is 0.6 mm, and if you then raise layer height or amplitude\n#   without thinking, the nozzle can be driven far enough up to hit the skin\n#   above or plough through already-printed material.\n\n# Stamped into the output so a second pass is a no-op. Orca can invoke\n# psGCodePostProcess more than once for one slice (file export and network\n# upload are separate calls), and waving an already-waved file would double\n# every displacement.\nMARKER_PREFIX = \"; unlayered-infill\"\nMARKER_VERSION = \"0.4.5\"\nMARKER = f\"{MARKER_PREFIX} v{MARKER_VERSION} (non-planar sparse infill)\\n\"\n\n_WORD = re.compile(r\"([A-Za-z])\\s*([-+]?\\d*\\.?\\d+)\")\n_Z = re.compile(r\"Z([-+]?\\d*\\.?\\d+)\")\n\n\nclass NonPlanarError(Exception):\n    \"\"\"A problem worth stopping for, explained in plain English.\"\"\"\n\n\ndef parse_words(line):\n    \"\"\"`G1 X1 Y2 E.5 ; comment` -> {'G':1.0,'X':1.0,'Y':2.0,'E':0.5}.\"\"\"\n    body = line.split(\";\", 1)[0]\n    if not body.strip():\n        return None\n    words = {}\n    for m in _WORD.finditer(body):\n        words.setdefault(m.group(1).upper(), float(m.group(2)))\n    return words or None\n\n\ndef section_name(line):\n    \"\"\"The section label if this is a `;TYPE:` line, else None.\"\"\"\n    low = line.lower()\n    if low.startswith(TYPE_PREFIX):\n        return low[len(TYPE_PREFIX):].strip()\n    return None\n\n\ndef is_infill_section(name):\n    return any(m in name for m in INFILL_MARKERS)\n\n\ndef is_solid_section(name):\n    return any(m in name for m in SOLID_MARKERS)\n\n\ndef detect_extrusion_mode(lines):\n    \"\"\"'relative' (M83), 'absolute' (M82), or 'unknown'.\"\"\"\n    head = \"\\n\".join(lines[:400])\n    if \"M83\" in head:\n        return \"relative\"\n    if \"M82\" in head:\n        return \"absolute\"\n    tail = \"\\n\".join(lines[-4000:])  # the slicer config block lives at the end\n    if \"relative_extrusion = 1\" in tail or \"use_relative_e_distances = 1\" in tail:\n        return \"relative\"\n    if \"relative_extrusion = 0\" in tail or \"use_relative_e_distances = 0\" in tail:\n        return \"absolute\"\n    return \"unknown\"\n\n\ndef detect_layer_height(lines):\n    \"\"\"The layer height actually being printed: the most common `;HEIGHT:`,\n    falling back to the slicer's `layer_height = ` config line.\"\"\"\n    heights = []\n    config_lh = None\n    for line in lines:\n        if line.startswith(\";HEIGHT:\"):\n            try:\n                heights.append(float(line[len(\";HEIGHT:\"):].strip()))\n            except ValueError:\n                pass\n        elif config_lh is None and \"layer_height\" in line:\n            m = re.search(r\";\\s*layer_height\\s*=\\s*(\\d*\\.?\\d+)\", line)\n            if m and \"first_layer\" not in line:\n                config_lh = float(m.group(1))\n    if heights:\n        return max(multimode(heights))\n    return config_lh\n\n\ndef resolve_amplitude(spec, lines):\n    \"\"\"'-0.2' -> mm; '200%' / '-1.5x' -> that fraction of the layer height.\n\n    Returns (millimetres, human description).\n    \"\"\"\n    s = str(spec).strip()\n    if not s:\n        raise NonPlanarError(\n            \"No amplitude given. Use mm (e.g. -0.2), a percent of layer height \"\n            \"(e.g. -150%), or a multiple (e.g. -1.5x).\")\n    relative = s.endswith(\"%\") or s.lower().endswith(\"x\")\n    try:\n        value = float(s[:-1]) if relative else float(s)\n    except ValueError:\n        raise NonPlanarError(\n            f\"Could not understand amplitude {s!r}. Use mm (e.g. -0.2), a \"\n            f\"percent of layer height (e.g. -150%), or a multiple (e.g. -1.5x).\")\n    if not relative:\n        return value, f\"{value:.3f} mm (fixed value)\"\n    mult = value / 100.0 if s.endswith(\"%\") else value\n    lh = detect_layer_height(lines)\n    if lh is None:\n        raise NonPlanarError(\n            f\"You gave the amplitude as {s} of layer height, but this G-code has \"\n            \"no layer height in it (no ';HEIGHT:' comments and no \"\n            \"'layer_height =' config line). Give the amplitude in plain mm \"\n            \"instead, e.g. -0.2.\")\n    amp = mult * lh\n    return amp, f\"{s} of layer height {lh:.3f} mm = {amp:.3f} mm\"\n\n\ndef already_processed(lines):\n    \"\"\"Has this file already been waved? Then leave it completely alone.\"\"\"\n    return any(line.startswith(MARKER_PREFIX) for line in lines)\n\n\ndef waveform(shape, phase):\n    \"\"\"One cycle of the chosen profile at `phase` radians, in [-1, 1].\n\n    All three share their zero crossings and their peak positions, so\n    changing `shape` changes the character of the wave without moving it.\n    \"\"\"\n    if shape == \"sine\":\n        return math.sin(phase)\n    if shape == \"square\":\n        # A real square wave would ask the nozzle to step in Z instantly,\n        # which no printer can do and no extrusion can follow. Overdriving a\n        # sine and clipping it gives flat crests with short, printable ramps\n        # between them -- the useful part of a square wave, minus the cliff.\n        return max(-1.0, min(1.0, SQUARE_GAIN * math.sin(phase)))\n    if shape == \"triangle\":\n        t = (phase / (2.0 * math.pi)) % 1.0\n        return 4.0 * abs(((t - 0.25) % 1.0) - 0.5) - 1.0\n    raise NonPlanarError(\n        f\"Unknown wave shape {shape!r}. Use one of: {', '.join(SHAPES)}.\")\n\n\ndef resolve_shape(spec):\n    s = str(spec or DEFAULT_SHAPE).strip().lower()\n    if s not in SHAPES:\n        raise NonPlanarError(\n            f\"Unknown wave shape {spec!r}. Use one of: {', '.join(SHAPES)}.\")\n    return s\n\n\ndef resolve_pattern(spec):\n    s = str(spec or DEFAULT_PATTERN).strip().lower()\n    if s not in PATTERNS:\n        raise NonPlanarError(\n            f\"Unknown wave pattern {spec!r}. Use one of: \"\n            f\"{', '.join(PATTERNS)}.\")\n    return s\n\n\ndef displacement(x, y, pattern, shape, frequency, angle_rad, phase_rad):\n    \"\"\"The unit wave at a point: the bit that gets multiplied by amplitude.\n\n    Always within [-1, 1], so `max_lift_mm` and the amplitude mean what they\n    say no matter which pattern is chosen.\n    \"\"\"\n    cos_a, sin_a = math.cos(angle_rad), math.sin(angle_rad)\n    u = x * cos_a + y * sin_a\n    if pattern == \"linear\":\n        return waveform(shape, frequency * u + phase_rad)\n    # cross: the same ripple along the perpendicular axis as well. Averaging\n    # the two keeps the result inside [-1, 1]; adding them would double the\n    # amplitude the user asked for wherever two crests happened to meet.\n    v = -x * sin_a + y * cos_a\n    return 0.5 * (waveform(shape, frequency * u + phase_rad) +\n                  waveform(shape, frequency * v + phase_rad))\n\n\nclass SolidGrid:\n    \"\"\"Where the part has solid skin, mapped as a grid of XY columns.\n\n    A single global list of solid Z heights is only correct for a part whose\n    skins are flat planes spanning the whole footprint. Give it a ledge, a\n    bridge, a chamfered top, or two towers of different heights and it fails\n    in a way that matters: every column is told its roof is the *highest*\n    skin anywhere in the print, so infill directly under a low ledge thinks\n    it has metres of headroom and waves at full amplitude straight into it.\n\n    Recording solid heights per XY column instead gives every infill move a\n    floor and roof measured in its own column \u2014 the wave fades against the\n    skin it is actually about to hit.\n    \"\"\"\n\n    __slots__ = (\"cell\", \"columns\", \"_raw_cache\", \"_disc\")\n\n    def __init__(self, cell_mm=DEFAULT_CELL_MM):\n        self.cell = max(0.05, float(cell_mm))\n        self.columns = {}\n        self._raw_cache = {}\n        self._disc = None\n\n    def key(self, x, y):\n        c = self.cell\n        return (int(math.floor(x / c)), int(math.floor(y / c)))\n\n    def add_move(self, x0, y0, x1, y1, z):\n        \"\"\"Mark every column the solid extrusion (x0,y0)->(x1,y1) crosses.\"\"\"\n        zr = round(z, 4)\n        step = self.cell * 0.5\n        n = max(1, int(math.hypot(x1 - x0, y1 - y0) / step) + 1)\n        cols = self.columns\n        for i in range(n + 1):\n            t = i / n\n            cols.setdefault(self.key(x0 + t * (x1 - x0),\n                                     y0 + t * (y1 - y0)), set()).add(zr)\n\n    def finalize(self):\n        self.columns = {k: sorted(v) for k, v in self.columns.items()}\n        return self\n\n    def _raw(self, key, z, full_strength):\n        \"\"\"Taper for one column: 0 at its own skins, peak mid-span.\n\n        Returns None when the column has no solid at all (nothing to measure\n        against), which the blend treats as \"no opinion\" rather than zero.\n        \"\"\"\n        ck = (key, z)\n        hit = self._raw_cache.get(ck)\n        if hit is not None:\n            return hit[0]\n        zs = self.columns.get(key)\n        if not zs:\n            self._raw_cache[ck] = (None,)\n            return None\n        i = bisect.bisect_left(zs, z - 1e-9)\n        if i < len(zs) and abs(zs[i] - z) <= 1e-6:\n            val = 0.0                      # this column is solid right here\n        else:\n            below = zs[i - 1] if i > 0 else None\n            j = bisect.bisect_right(zs, z + 1e-9)\n            above = zs[j] if j < len(zs) else None\n            if below is None or above is None or above - below <= 0:\n                val = 0.0                  # unbracketed: no wave, no sign flip\n            else:\n                val = min(above - z, z - below) / (above - below)\n                if full_strength:\n                    val = min(1.0, val * 2.0)\n        self._raw_cache[ck] = (val,)\n        return val\n\n    def _offsets(self, blend_mm):\n        \"\"\"Cell offsets within the blend radius, computed once.\"\"\"\n        if self._disc is None:\n            r = min(8, int(math.ceil(blend_mm / self.cell)))\n            self._disc = [(dx, dy)\n                          for dx in range(-r, r + 1)\n                          for dy in range(-r, r + 1)\n                          if math.hypot(dx, dy) * self.cell <= blend_mm + 1e-9]\n        return self._disc\n\n    def scale(self, x, y, z, full_strength=False, blend_mm=DEFAULT_BLEND_MM):\n        \"\"\"Blended taper at a point.\n\n        Neighbouring columns can have very different floors and roofs \u2014 at the\n        edge of a ledge, one column's roof is 2 mm up and the next one's is\n        20 mm up. Taking each column's answer literally puts a step in the\n        wave exactly there. Averaging over a small disc turns that step into a\n        ramp, which is what `blend_mm` buys.\n\n        Columns with no solid recorded are skipped rather than counted as\n        zero: they are usually just gaps between solid extrusion lines, and\n        counting them would damp the wave everywhere.\n        \"\"\"\n        z = round(z, 4)\n        if blend_mm <= 0:\n            return self._raw(self.key(x, y), z, full_strength) or 0.0\n        ix, iy = self.key(x, y)\n        c = self.cell\n        total = weight = 0.0\n        for dx, dy in self._offsets(blend_mm):\n            val = self._raw((ix + dx, iy + dy), z, full_strength)\n            if val is None:\n                continue\n            # distance from the sample point to that column's centre\n            cx = (ix + dx + 0.5) * c\n            cy = (iy + dy + 0.5) * c\n            d = math.hypot(cx - x, cy - y)\n            w = 1.0 - d / blend_mm\n            if w <= 0.0:\n                continue\n            total += w * val\n            weight += w\n        return total / weight if weight > 0.0 else 0.0\n\n\ndef detect_nozzle_diameter(lines):\n    \"\"\"The nozzle diameter the slicer recorded, in mm, or None.\n\n    Orca writes `; nozzle_diameter = 0.6` into the config block at the end of\n    the file (comma-separated per extruder on a multi-tool machine; we take\n    the first). This is what makes the column grid match the printer instead\n    of being an arbitrary constant.\n    \"\"\"\n    for line in lines:\n        if \"nozzle_diameter\" not in line:\n            continue\n        m = re.search(r\";\\s*nozzle_diameter\\s*=\\s*([\\d.]+)\", line)\n        if m:\n            try:\n                v = float(m.group(1))\n            except ValueError:\n                continue\n            if 0.05 <= v <= 5.0:       # anything else is a misparse\n                return v\n    return None\n\n\n# --- \"auto\": take the value from the print instead of a constant -----------\n#\n# Every number below that describes a LENGTH is really a multiple of the\n# nozzle, and every print has a nozzle. Hard-coding 1.0 mm or 2.0 mm means the\n# settings are right for a 0.4 nozzle and quietly wrong for a 0.25 or a 0.8.\n# \"auto\" reads the nozzle out of the exported G-code and scales.\n#\n# The factors are chosen so that \"auto\" on a 0.4 mm nozzle reproduces the\n# constants this plugin shipped with, exactly. Nothing changes for the common\n# case; the settings simply follow the printer when it is not the common case.\nAUTO_WORDS = (\"\", \"auto\", \"orca\")\n\n#   setting      x nozzle   value at 0.4 mm   what it is\nAUTO_NOZZLE_FACTORS = {\n    \"segment_mm\":  2.5,     # 1.0 mm   how finely a move is chopped\n    \"blend_mm\":    5.0,     # 2.0 mm   taper smoothing radius\n}\n# Wavelength, as a multiple of the nozzle. frequency = 2*pi / wavelength, so\n# 10.5 nozzles on a 0.4 gives 1.496 ~ the 1.5 this plugin shipped with. Below\n# about 6 nozzles neighbouring crests start running into each other.\nAUTO_WAVELENGTH_NOZZLES = 10.5\n# A ceiling for \"auto\" max_lift_mm, as a multiple of the layer height.\nAUTO_MAX_LIFT_LAYERS = 1.5\n\n\ndef is_auto(spec):\n    \"\"\"True for None, \"\", \"auto\" and \"orca\" -- anything meaning 'you decide'.\"\"\"\n    return spec is None or (isinstance(spec, str)\n                            and spec.strip().lower() in AUTO_WORDS)\n\n\ndef nozzle_or(lines, fallback=FALLBACK_CELL_MM):\n    noz = detect_nozzle_diameter(lines)\n    return (noz, True) if noz else (fallback, False)\n\n\ndef resolve_auto_length(spec, key, lines, name):\n    \"\"\"A length in mm: \"auto\" -> a multiple of the nozzle; a number -> itself.\n\n    Returns (millimetres, human description).\n    \"\"\"\n    if is_auto(spec):\n        factor = AUTO_NOZZLE_FACTORS[key]\n        noz, measured = nozzle_or(lines)\n        value = factor * noz\n        how = (f\"auto: {factor:g} x the {noz:.2f} mm nozzle\"\n               if measured else\n               f\"auto, but this G-code names no nozzle, so {noz:.2f} mm was \"\n               f\"assumed\")\n        return value, f\"{value:.3f} mm ({how})\"\n    try:\n        value = float(spec)\n    except (TypeError, ValueError):\n        raise NonPlanarError(\n            f\"Could not understand {name} {spec!r}. Use 'auto' to follow the \"\n            f\"nozzle, or a number of millimetres.\")\n    return value, f\"{value:.3f} mm (fixed value)\"\n\n\ndef resolve_frequency(spec, lines):\n    \"\"\"'auto' -> a wavelength of AUTO_WAVELENGTH_NOZZLES nozzles.\"\"\"\n    if is_auto(spec):\n        noz, measured = nozzle_or(lines)\n        value = 2.0 * math.pi / (AUTO_WAVELENGTH_NOZZLES * noz)\n        how = (f\"auto: one ripple every {AUTO_WAVELENGTH_NOZZLES:g} x \"\n               f\"{noz:.2f} mm nozzle widths\"\n               if measured else\n               f\"auto, but this G-code names no nozzle, so {noz:.2f} mm was \"\n               f\"assumed\")\n        return value, f\"{value:.3f} ripples/mm ({how})\"\n    try:\n        value = float(spec)\n    except (TypeError, ValueError):\n        raise NonPlanarError(\n            f\"Could not understand the frequency {spec!r}. Use 'auto' to \"\n            f\"follow the nozzle, or a number of ripples per millimetre.\")\n    return value, f\"{value:.3f} ripples/mm (fixed value)\"\n\n\ndef resolve_wave_angle(spec, lines):\n    \"\"\"'auto' -> square across the slicer's own infill angle.\n\n    A wave only does interlocking work where an infill line CROSSES it, so\n    the useful angle is the infill angle turned by 90 degrees. Orca writes\n    `; fill_angle = 45` into the exported file.\n    \"\"\"\n    if is_auto(spec):\n        raw = slicer_setting(lines, \"fill_angle\")\n        if raw is None:\n            return 0.0, \"0.0 deg (auto, but this G-code names no fill_angle)\"\n        try:\n            fill = float(str(raw).split(\",\")[0])\n        except ValueError:\n            return 0.0, \"0.0 deg (auto, but fill_angle could not be read)\"\n        value = (fill + 90.0) % 180.0\n        return value, (f\"{value:.1f} deg (auto: square across the \"\n                       f\"{fill:g} deg infill)\")\n    try:\n        value = float(spec)\n    except (TypeError, ValueError):\n        raise NonPlanarError(\n            f\"Could not understand the wave angle {spec!r}. Use 'auto' to run \"\n            f\"square across the infill, or a number of degrees.\")\n    return value, f\"{value:.1f} deg (fixed value)\"\n\n\ndef resolve_max_lift(spec, lines):\n    \"\"\"'auto' -> AUTO_MAX_LIFT_LAYERS layer heights; 0 or 'off' -> no ceiling.\"\"\"\n    if isinstance(spec, str) and spec.strip().lower() in (\"off\", \"none\"):\n        return 0.0, \"no ceiling\"\n    if is_auto(spec):\n        lh = detect_layer_height(lines)\n        if not lh:\n            return 0.0, \"no ceiling (auto, but no layer height in the G-code)\"\n        value = AUTO_MAX_LIFT_LAYERS * lh\n        return value, (f\"{value:.3f} mm (auto: {AUTO_MAX_LIFT_LAYERS:g} x the \"\n                       f\"{lh:.3f} mm layer)\")\n    try:\n        value = max(0.0, float(spec))\n    except (TypeError, ValueError):\n        raise NonPlanarError(\n            f\"Could not understand the Z ceiling {spec!r}. Use 'auto', 0 for \"\n            f\"no ceiling, or a number of millimetres.\")\n    return value, (f\"{value:.3f} mm (fixed value)\" if value else \"no ceiling\")\n\n\ndef slicer_setting(lines, key):\n    \"\"\"One `; key = value` line out of the slicer's config block, or None.\"\"\"\n    pattern = re.compile(r\"^;\\s*\" + re.escape(key) + r\"\\s*=\\s*(.+?)\\s*$\")\n    for line in reversed(lines):          # the config block is at the end\n        m = pattern.match(line.rstrip(\"\\n\"))\n        if m:\n            return m.group(1).strip()\n    return None\n\n\ndef resolve_cell_mm(spec, lines):\n    \"\"\"'auto' -> the nozzle diameter; a number -> itself.\n\n    Returns (millimetres, human description).\n    \"\"\"\n    if spec is None or (isinstance(spec, str) and spec.strip().lower() in (\"\", \"auto\")):\n        nozzle = detect_nozzle_diameter(lines)\n        if nozzle is None:\n            return FALLBACK_CELL_MM, (\n                f\"{FALLBACK_CELL_MM:.3f} mm (auto, but this G-code does not \"\n                f\"name a nozzle diameter, so the default was used)\")\n        return nozzle, f\"{nozzle:.3f} mm (auto: one column per nozzle width)\"\n    try:\n        v = float(spec)\n    except (TypeError, ValueError):\n        raise NonPlanarError(\n            f\"Could not understand the grid cell size {spec!r}. Use 'auto' to \"\n            f\"follow the nozzle diameter, or a number of millimetres.\")\n    return v, f\"{v:.3f} mm (fixed value)\"\n\n\ndef build_solid_grid(lines, cell_mm=FALLBACK_CELL_MM):\n    \"\"\"Rasterise every solid-skin extrusion into an XY column map.\"\"\"\n    grid = SolidGrid(cell_mm)\n    x = y = None\n    z = 0.0\n    solid = False\n    solid_heights = set()\n    for line in lines:\n        name = section_name(line)\n        if name is not None:\n            solid = is_solid_section(name)\n            continue\n        words = parse_words(line)\n        if not words or words.get(\"G\") not in (0.0, 1.0):\n            continue\n        nx = words.get(\"X\", x)\n        ny = words.get(\"Y\", y)\n        if \"Z\" in words:\n            z = words[\"Z\"]\n        e = words.get(\"E\")\n        if solid and e is not None and e > 0 and None not in (x, y, nx, ny):\n            grid.add_move(x, y, nx, ny, z)\n            solid_heights.add(round(z, 4))\n        x, y = nx, ny\n    grid.finalize()\n    return grid, sorted(solid_heights)\n\n\ndef _empty_stats(**over):\n    base = {\"amplitude_mm\": 0.0, \"amplitude_desc\": \"\", \"extrusion_mode\": \"\",\n            \"solid_layers\": 0, \"solid_columns\": 0, \"sections\": 0, \"moves\": 0,\n            \"segments\": 0, \"max_wiggle\": 0.0, \"skipped_unbracketed\": 0,\n            \"already_processed\": False, \"cell_mm\": 0.0, \"cell_desc\": \"\",\n            \"nozzle_mm\": None, \"layer_height_mm\": None, \"blend_mm\": 2.0,\n            \"full_strength\": False, \"pattern\": DEFAULT_PATTERN,\n            \"wave_angle\": DEFAULT_WAVE_ANGLE, \"shape\": DEFAULT_SHAPE,\n            \"layer_phase\": DEFAULT_LAYER_PHASE,\n            \"max_lift_mm\": 0.0, \"clamped\": 0,\n            \"wave_layers\": 0, \"frequency_desc\": \"\", \"segment_desc\": \"\",\n            \"blend_desc\": \"\", \"wave_angle_desc\": \"\", \"max_lift_desc\": \"\"}\n    base.update(over)\n    return base\n\n\ndef process(lines, amplitude_spec=DEFAULT_AMPLITUDE, frequency=DEFAULT_FREQUENCY,\n            segment_mm=DEFAULT_SEGMENT_MM, require_relative_e=True,\n            cell_mm=DEFAULT_CELL_MM, blend_mm=DEFAULT_BLEND_MM,\n            full_strength=False, pattern=DEFAULT_PATTERN,\n            wave_angle=DEFAULT_WAVE_ANGLE, shape=DEFAULT_SHAPE,\n            layer_phase=DEFAULT_LAYER_PHASE, max_lift_mm=DEFAULT_MAX_LIFT_MM):\n    \"\"\"Rewrite sparse-infill moves as wavy ones. Returns (out_lines, stats).\"\"\"\n    # Orca may run the export step twice for one slice (file + upload). Waving\n    # an already-waved file would double every displacement, so bail out.\n    if already_processed(lines):\n        return list(lines), _empty_stats(already_processed=True)\n\n    amplitude, amp_desc = resolve_amplitude(amplitude_spec, lines)\n\n    mode = detect_extrusion_mode(lines)\n    if mode == \"absolute\" and require_relative_e:\n        raise NonPlanarError(\n            \"This G-code uses ABSOLUTE extrusion (M82). Splitting moves would \"\n            \"corrupt it.\\n\\nFix: OrcaSlicer > Printer Settings > Advanced > \"\n            \"'Use relative E distances', then slice again.\")\n\n    cell_resolved, cell_desc = resolve_cell_mm(cell_mm, lines)\n    grid, solids = build_solid_grid(lines, cell_resolved)\n    # Anything that can be read off the print is read off the print. Each\n    # resolver also hands back a sentence saying what it decided and why, so\n    # the log and \"Check setup\" can show the real number rather than \"auto\".\n    frequency, frequency_desc = resolve_frequency(frequency, lines)\n    segment_mm, segment_desc = resolve_auto_length(\n        segment_mm, \"segment_mm\", lines, \"the segment length\")\n    segment_mm = max(0.05, segment_mm)\n    blend_mm, blend_desc = resolve_auto_length(\n        blend_mm, \"blend_mm\", lines, \"the blend radius\")\n    blend_mm = max(0.0, blend_mm)\n    full_strength = bool(full_strength)\n    pattern = resolve_pattern(pattern)\n    shape = resolve_shape(shape)\n    wave_angle, wave_angle_desc = resolve_wave_angle(wave_angle, lines)\n    angle_rad = math.radians(wave_angle)\n    layer_phase_rad = math.radians(float(layer_phase))\n    max_lift_mm, max_lift_desc = resolve_max_lift(max_lift_mm, lines)\n\n    out = []\n    x = y = z = None\n    in_infill = False\n    displaced = False           # nozzle currently sitting at a wave-shifted Z\n    sections = moves = segments = 0\n    max_wiggle = 0.0\n    skipped_unbracketed = 0\n    clamped = 0                 # segments the max_lift ceiling actually caught\n\n    # Which infill layer we are on, for `layer_phase`. Counted only at the\n    # heights where infill is really waved, and in the order they are met, so\n    # a Z-hop or a travel at some other height cannot advance the phase. The\n    # first waved layer is 0, which keeps `layer_phase` from moving anything\n    # when the feature is off.\n    layer_ordinal = {}\n\n    def restore_z():\n        \"\"\"Never leave the nozzle on the wave once the infill stroke ends.\"\"\"\n        nonlocal displaced\n        if displaced and z is not None:\n            out.append(f\"G1 Z{z:.3f}\\n\")\n            displaced = False\n\n    for line in lines:\n        name = section_name(line)\n        if name is not None:\n            was = in_infill\n            in_infill = is_infill_section(name)\n            if in_infill and not was:\n                sections += 1\n            if not in_infill:\n                restore_z()\n            out.append(line)\n            continue\n\n        words = parse_words(line)\n        if not words or words.get(\"G\") not in (0.0, 1.0):\n            out.append(line)\n            continue\n\n        nx = words.get(\"X\", x)\n        ny = words.get(\"Y\", y)\n        e = words.get(\"E\")\n\n        if \"Z\" in words:                 # the slicer's own Z always wins\n            z = words[\"Z\"]\n            displaced = False\n\n        movable = (in_infill and e is not None and e > 0 and \"Z\" not in words\n                   and None not in (x, y, z) and (nx != x or ny != y))\n        if movable:\n            # sample the taper at the midpoint of the stroke\n            scale = grid.scale((x + nx) * 0.5, (y + ny) * 0.5, z,\n                               full_strength, blend_mm)\n            if scale > 0.0:\n                length = math.hypot(nx - x, ny - y)\n                n = max(1, int(length // segment_mm))\n                feed = words.get(\"F\")\n                zr = round(z, 4)\n                if zr not in layer_ordinal:\n                    layer_ordinal[zr] = len(layer_ordinal)\n                phase_rad = layer_ordinal[zr] * layer_phase_rad\n                # Hand out the extrusion so the printed digits sum to exactly\n                # `e`. Rounding each segment independently drifts, and across\n                # a whole print that drift is systematic under/over-extrusion.\n                spent = 0.0\n                for i in range(1, n + 1):      # skip i=0: we are already there\n                    t = i / n\n                    sx = x + t * (nx - x)\n                    sy = y + t * (ny - y)\n                    dz = amplitude * scale * displacement(\n                        sx, sy, pattern, shape, frequency, angle_rad, phase_rad)\n                    if max_lift_mm and abs(dz) > max_lift_mm:\n                        dz = math.copysign(max_lift_mm, dz)\n                        clamped += 1\n                    if abs(dz) > max_wiggle:\n                        max_wiggle = abs(dz)\n                    share = round(e * t - spent, 5)\n                    spent += share\n                    tail = f\" F{feed:.0f}\" if (i == 1 and feed is not None) else \"\"\n                    out.append(f\"G1 X{sx:.3f} Y{sy:.3f} Z{z + dz:.3f} \"\n                               f\"E{share:.5f}{tail}\\n\")\n                segments += n\n                moves += 1\n                displaced = True\n                x, y = nx, ny\n                continue\n            skipped_unbracketed += 1\n\n        restore_z()\n        out.append(line)\n        x, y = nx, ny\n\n    restore_z()\n\n    if moves:\n        out.insert(0, MARKER)\n\n    return out, {\n        \"amplitude_mm\": amplitude,\n        \"amplitude_desc\": amp_desc,\n        \"extrusion_mode\": mode,\n        \"solid_layers\": len(solids),\n        \"solid_columns\": len(grid.columns),\n        \"sections\": sections,\n        \"moves\": moves,\n        \"segments\": segments,\n        \"max_wiggle\": max_wiggle,\n        \"skipped_unbracketed\": skipped_unbracketed,\n        \"already_processed\": False,\n        \"cell_mm\": grid.cell,\n        \"cell_desc\": cell_desc,\n        \"nozzle_mm\": detect_nozzle_diameter(lines),\n        \"layer_height_mm\": detect_layer_height(lines),\n        \"blend_mm\": blend_mm,\n        \"full_strength\": full_strength,\n        \"pattern\": pattern,\n        \"wave_angle\": float(wave_angle),\n        \"shape\": shape,\n        \"layer_phase\": float(layer_phase),\n        \"max_lift_mm\": max_lift_mm,\n        \"clamped\": clamped,\n        \"wave_layers\": len(layer_ordinal),\n        # What each \"auto\" actually resolved to, in words.\n        \"frequency_desc\": frequency_desc,\n        \"segment_desc\": segment_desc,\n        \"blend_desc\": blend_desc,\n        \"wave_angle_desc\": wave_angle_desc,\n        \"max_lift_desc\": max_lift_desc,\n    }\n"
# Re-entrant on purpose. Pressing Refresh in the Plugins dialog re-runs
# discovery and imports this module AGAIN in the same interpreter, so this
# block runs more than once per session.
#
# The module is published in sys.modules before it is exec'd -- an inlined
# engine has to be findable by name while it executes (dataclasses resolve
# string annotations through sys.modules, and Wave Overhangs' engine depends
# on exactly that).
#
# What changed in 0.4.3 is the failure path. It used to POP "nonplanar_core"
# and set npc = None, so a second pass that failed for any reason replaced a
# working engine with nothing and left the plugin reporting "engine MISSING"
# while Wave Overhangs -- whose engine was already resident -- carried on
# fine. The previous engine is now put back instead, and the reason is kept
# so Check setup can print it rather than a bare "MISSING".
_ENGINE_ERROR = None
_npc_prev = _sys.modules.get("nonplanar_core")
npc = _types.ModuleType("nonplanar_core")
_sys.modules["nonplanar_core"] = npc
try:
    exec(compile(_NONPLANAR_CORE_SRC, "nonplanar_core (inlined)", "exec"),
         npc.__dict__)
except BaseException as _e:  # pragma: no cover - surfaced via Check setup
    # BaseException, not Exception: the audit hook is not required to raise an
    # Exception subclass, and an engine that cannot load must still leave a
    # readable reason behind rather than a bare "MISSING".
    _ENGINE_ERROR = f"{type(_e).__name__}: {_e}"
    if _npc_prev is not None and hasattr(_npc_prev, "process"):
        _sys.modules["nonplanar_core"] = _npc_prev    # keep what already worked
        npc = _npc_prev
    else:
        _sys.modules.pop("nonplanar_core", None)
        npc = None


# ---------------------------------------------------------------------------
#  The settings
#
#  Three rules, so the Config panel stays readable as this grows:
#
#  1. The panel is ORGANISED. `_SECTIONS` below is the running order and the
#     grouping; `annotated_defaults()` builds the JSON from it, so the panel
#     and the "Check setup" guide can never disagree about either.
#  2. Notes are ONE LINE. A JSON editor shows "\n" as the two characters
#     backslash-en, so a long note is an unreadable smear. Each note here is
#     a short sentence shaped `values -- what it does`. The long explanations
#     live in plugins/unlayered-infill/README.md, where there is room.
#  3. "auto" wherever the print can answer the question. See the engine's
#     AUTO_* tables: every factor is chosen so that "auto" on a 0.4 mm nozzle
#     reproduces the constant this plugin used to ship, exactly. Nothing
#     changes for a 0.4 nozzle; a 0.25 or a 0.8 now gets settings that suit
#     it instead of settings that suit somebody else's printer.
# ---------------------------------------------------------------------------
_DEFAULTS = {
    "enabled": True,
    # A share of the LAYER HEIGHT, so it keeps meaning when layer height
    # changes. No Orca equivalent and nothing in the G-code implies it: this
    # is a taste/strength decision, so it stays a constant.
    "amplitude": "200%",
    "frequency": "auto",        # auto: one ripple per 10.5 nozzle widths
    "pattern": "linear",
    "wave_angle": 0.0,          # accepts "auto" = square across the infill
    "shape": "sine",
    "layer_phase": 0.0,
    "max_lift_mm": 0.0,         # accepts "auto" = 1.5 layer heights
    "require_relative_e": True,
    "segment_mm": "auto",       # auto: 2.5 x nozzle
    "cell_mm": "auto",          # auto: one column per nozzle
    "blend_mm": "auto",         # auto: 5 x nozzle
    "full_strength": False,
    "log": True,
    "restore_backup": False,    # one-shot: put my remembered settings back
}


# One line each. Shape: `accepted values -- what it does`.
_NOTES = {
    "_READ_ME": (
        "Keys starting with _ are notes and section headings; the plugin "
        "ignores them. \"auto\" means the value is read from your print. Run "
        "\"Unlayered Infill - Check setup\" to see what each auto resolved to."),

    "_enabled": (
        "true | false -- master switch; false leaves your G-code untouched."),
    "_amplitude": (
        "\"200%\" of layer height, \"2x\", or mm like \"-0.2\" -- how far the "
        "infill rides up and down in Z."),
    "_frequency": (
        "\"auto\" or ripples per mm -- auto puts one ripple every 10.5 nozzle "
        "widths (1.50 on a 0.4 nozzle)."),

    "_pattern": (
        "linear | cross -- linear ripples one way; cross is an egg-crate so "
        "infill running in ANY direction still rises and falls."),
    "_wave_angle": (
        "\"auto\" or degrees -- auto runs the ripples square across your "
        "profile's infill angle, which is where they do the most work."),
    "_shape": (
        "sine | triangle | square -- sine is smooth, triangle has sharper "
        "peaks that key harder, square holds full offset longest."),
    "_layer_phase": (
        "degrees per waved layer -- 0 stacks every crest in a column; a small "
        "value walks them sideways and braids the layers. 180 = crest over "
        "trough."),

    "_max_lift_mm": (
        "\"auto\", 0 for none, or mm -- hard ceiling on the Z offset so a big "
        "amplitude cannot drive the nozzle into printed material."),
    "_require_relative_e": (
        "true | false -- refuse absolute-E G-code instead of corrupting it. "
        "Leave on; the fix is Printer Settings > Use relative E distances."),

    "_segment_mm": (
        "\"auto\" or mm -- how finely each infill move is chopped to follow "
        "the wave. auto is 2.5 nozzle widths (1.0 mm on a 0.4)."),
    "_cell_mm": (
        "\"auto\" or mm -- resolution of the solid-skin map. auto is one "
        "column per nozzle width, the finest the printer can resolve."),
    "_blend_mm": (
        "\"auto\" or mm -- smooths the fade-out where a ledge makes one "
        "column's ceiling much lower than its neighbour's. auto is 5 nozzles."),
    "_full_strength": (
        "true | false -- off, the wave peaks at half amplitude mid-span; on, "
        "it reaches full amplitude and still fades to nothing at the skins."),

    "_restore_backup": (
        "true | false -- a one-shot undo. Set true and slice once: every "
        "setting this plugin remembers from before is put back, and this "
        "returns to false. Check setup prints what is remembered."),
    "_log": (
        "true | false -- append a record of every export to the log file "
        "named by Check setup."),
}


# Running order AND grouping for both the Config panel and the guide.
# (heading key, heading text, [settings in this group])
_SECTIONS = [
    ("_1_BASICS", "===== 1. BASICS =====",
     ["enabled", "amplitude", "frequency"]),
    ("_2_WAVE_SHAPE", "===== 2. THE SHAPE OF THE WAVE =====",
     ["pattern", "wave_angle", "shape", "layer_phase"]),
    ("_3_SAFETY", "===== 3. LIMITS AND SAFETY =====",
     ["max_lift_mm", "require_relative_e"]),
    ("_4_RESOLUTION", "===== 4. RESOLUTION AND SMOOTHING (mostly auto) =====",
     ["segment_mm", "cell_mm", "blend_mm", "full_strength"]),
    ("_5_DIAGNOSTICS", "===== 5. DIAGNOSTICS AND RECOVERY =====",
     ["log", "restore_backup"]),
]


def _ordered_keys():
    """Every setting, in panel order, with any stragglers appended.

    Defensive: a setting added to `_DEFAULTS` and forgotten in `_SECTIONS`
    still has to appear somewhere, or it silently becomes uneditable.
    """
    seen = [k for _h, _t, keys in _SECTIONS for k in keys]
    return seen + [k for k in _DEFAULTS if k not in seen]


def settings_guide_lines(cfg=None, width=72):
    """The notes as readable text, for printing inside OrcaSlicer.

    Same order and same groups as the Config panel, because both are built
    from `_SECTIONS`.
    """
    # Orca gives a capability its OWN config and no one else's, so this item
    # cannot read what you set on the main Unlayered Infill capability. Say
    # so rather than print a default and call it "your value".
    live = cfg or _DEFAULTS
    out = ["--- what every setting means ---"]
    if cfg is None:
        out += ["The values below are the DEFAULTS. OrcaSlicer only lets an",
                "item read its own settings, so this check cannot see what",
                "you changed on the main Unlayered Infill capability -- open",
                "that item to see and edit your own values. The same notes",
                "are in its config panel, as the entries beginning with an",
                "underscore."]
    else:
        out += ['Your current value is shown first; (default X) follows when',
                'you have changed it. "auto" means the number is worked out',
                'from your print -- Check setup prints what it resolved to.']
    out.append("")

    def wrapped(note):
        line = "   "
        for word in note.split():
            if len(line) + len(word) + 1 > width:
                yield line
                line = "   "
            line += (" " if line.strip() else "") + word
        if line.strip():
            yield line

    for heading, title, keys in _SECTIONS:
        out.append(title)
        out.append("")
        for key in keys:
            note = _NOTES.get("_" + key)
            if not note:
                continue
            default = _DEFAULTS.get(key)
            value = live.get(key, default)
            head = f"{key} = {json.dumps(value)}"
            if value != default:
                head += f"   (default {json.dumps(default)})"
            out.append(head)
            out.extend(wrapped(note))
            out.append("")
    return out


def annotated_defaults():
    """`_DEFAULTS` as the user sees it in OrcaSlicer: grouped, note then key.

    Built fresh every time -- never hand out `_DEFAULTS` itself to be
    mutated -- and ordered by `_SECTIONS` so the panel reads top to bottom
    instead of being an undifferentiated wall of keys.
    """
    out = {"_READ_ME": _NOTES["_READ_ME"]}
    placed = set()
    for heading, title, keys in _SECTIONS:
        out[heading] = title
        for key in keys:
            if key not in _DEFAULTS:
                continue
            note = _NOTES.get("_" + key)
            if note:
                out["_" + key] = note
            out[key] = _DEFAULTS[key]
            placed.add(key)
    leftover = [k for k in _DEFAULTS if k not in placed]
    if leftover:
        out["_9_OTHER"] = "===== OTHER ====="
        for key in leftover:
            note = _NOTES.get("_" + key)
            if note:
                out["_" + key] = note
            out[key] = _DEFAULTS[key]
    return out


# --- keeping the Config panel up to date across upgrades -------------------
#
# Orca stores each capability's settings globally in
# `data_dir()/orca_plugins/config.json`, keyed by capability identity (see
# docs/ORCA-PLUGIN-FACTS.md, "Capability configuration"). `get_default_config()`
# is only consulted when there is nothing saved or when the user presses
# "Restore defaults" -- so a config saved by 0.3.4 keeps 0.3.4's nine settings
# forever, and `pattern`, `shape`, `wave_angle`, `layer_phase` and
# `max_lift_mm` never appear in the panel even though the running plugin
# supports them.
#
# The wiki documents the cure: `get_config_version()` to spot an older schema
# and `save_config()` to write a migrated one back, from
# `migrate_config_if_needed()`. That is what this does. The user's own values
# are always kept; only missing keys are added and the explanatory notes are
# refreshed.
_MIGRATED = set()


def merge_for_panel(saved, template):
    """`template` (the annotated defaults) with every value the user set kept.

    Settings the user changed survive. Settings this build added appear at
    their default. Notes are taken from the running build, so they describe
    the code that is actually installed. Keys we no longer recognise are kept
    at the end rather than thrown away -- losing something the owner typed is
    worse than carrying a dead key.
    """
    out = {}
    for key, value in template.items():
        if not key.startswith("_") and key in saved:
            out[key] = saved[key]
        else:
            out[key] = value
    for key, value in saved.items():
        if key not in out and not key.startswith("_"):
            out[key] = value
    return out


def _migrate_config(cap, template, name):
    """Add this build's new settings to an older saved config, in place.

    Returns the merged dict (or None when there was nothing saved, which is
    the good case: Orca then shows `get_default_config()` already). Never
    raises -- a settings panel that cannot be refreshed must not be able to
    stop a slice.
    """
    try:
        saved = json.loads(cap.get_config() or "{}")
    except BaseException:
        return None
    if not isinstance(saved, dict) or not saved:
        return None
    merged = merge_for_panel(saved, template)
    # An explicit, one-shot "put my settings back". Deliberately not
    # automatic -- see the comment on _backup_settings.
    restored = []
    if _as_bool_cfg(merged.get("restore_backup", False)):
        restored = _apply_backup(merged)
    if merged == saved:
        return merged
    try:
        ok = cap.save_config(json.dumps(merged, indent=2))
    except BaseException:
        return merged
    if restored:
        backup = _settings_backup() or {}
        _log(f"Unlayered Infill v{PLUGIN_VERSION}: restored {len(restored)} "
             f"setting(s) from the backup taken by "
             f"v{backup.get('version', '?')} on {backup.get('saved_at', '?')}: "
             + ", ".join(sorted(restored)))
    added = [k for k in merged if k not in saved and not k.startswith("_")]
    _log(f"Unlayered Infill v{PLUGIN_VERSION}: config for {name!r} was saved "
         f"by an older build; "
         + (f"added {', '.join(added)}" if added else "refreshed its notes")
         + (" and saved it" if ok else " but Orca refused to save it"))
    return merged


def _migrate_once(cap, template, name):
    """Migrate at most once per session, so a per-step call stays cheap."""
    if name in _MIGRATED:
        return
    _MIGRATED.add(name)
    _migrate_config(cap, template, name)



# ---------------------------------------------------------------------------
#  Never lose the owner's settings
#
#  OrcaSlicer keeps a capability's settings in one global file. That copy can
#  go away for reasons the plugin does not control -- "Restore defaults", a
#  reinstall, a profile or data-directory change, an Orca upgrade. When it
#  does, the panel comes back as factory defaults and the tuning is gone.
#
#  So every time a capability runs, the current settings are copied into this
#  plugin's own state file. Nothing is restored automatically: silently
#  putting old settings back would make "Restore defaults" impossible, and a
#  plugin that overrules an explicit user action is worse than one that loses
#  a value. Instead the backup is always there, Check setup prints it, and
#  setting `restore_backup: true` and slicing once puts it back.
#
#  Settings that no longer exist in this build are dropped on the way in --
#  which is exactly the one case where a value genuinely cannot carry over.
# ---------------------------------------------------------------------------
# How many settings snapshots to keep. Five is enough to get
# behind an accidental wipe without the state file growing.
BACKUP_HISTORY = 5


def _as_bool_cfg(value):
    """A JSON editor can hand back the string "false"; treat it as false."""
    if isinstance(value, str):
        return value.strip().lower() not in ("", "0", "false", "no", "off")
    return bool(value)


def _backup_settings(cfg, name):
    """Remember the values in force, so they can survive the config going."""
    try:
        values = {k: v for k, v in cfg.items()
                  if not k.startswith("_") and k in _DEFAULTS
                  and k != "restore_backup"}
        if not values:
            return
        state = _load_state()
        history = state.get("settings_backups")
        if not isinstance(history, list):
            history = []
        if history and history[0].get("values") == values:
            return                       # unchanged; skip the write
        history.insert(0, {
            "version": PLUGIN_VERSION,
            "saved_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            "capability": name,
            "values": values,
        })
        # A HISTORY, not a single slot. The event we are insuring against --
        # the config being wiped -- is itself followed by a run, which would
        # otherwise overwrite the only copy with the factory defaults that
        # just replaced the owner's settings. Keeping the last few snapshots
        # means the wipe cannot destroy the thing that undoes it.
        state["settings_backups"] = history[:BACKUP_HISTORY]
        _save_state(state)
    except BaseException:
        pass                             # a backup must never break a slice


def _settings_backup():
    """The most recent remembered settings worth restoring, or None.

    "Worth restoring" means the newest snapshot that holds at least one
    non-default value. A snapshot of pure defaults is what a wipe looks
    like, and restoring that would achieve nothing.
    """
    try:
        history = _load_state().get("settings_backups")
        if not isinstance(history, list):
            return None
        usable = [b for b in history
                  if isinstance(b, dict) and isinstance(b.get("values"), dict)]
        for backup in usable:
            if any(k in _DEFAULTS and _DEFAULTS[k] != v
                   for k, v in backup["values"].items()):
                return backup
        return usable[0] if usable else None
    except BaseException:
        pass
    return None


def _apply_backup(merged):
    """Put the remembered settings back into `merged`, in place.

    Returns the list of settings restored. Anything the backup holds that
    this build no longer has is dropped: a removed setting is the one thing
    that genuinely cannot carry over.
    """
    backup = _settings_backup()
    if not backup:
        return []
    restored = []
    for key, value in backup["values"].items():
        if key not in _DEFAULTS or key == "restore_backup":
            continue
        if merged.get(key) != value:
            merged[key] = value
            restored.append(key)
    merged["restore_backup"] = False     # one-shot: never loop on next slice
    return restored


def _cfg(self):
    try:
        src = json.loads(self.get_config() or "{}")
    except (AttributeError, TypeError, ValueError):
        src = {}
    cfg = dict(_DEFAULTS)
    if isinstance(src, dict):
        for k, v in src.items():
            if k in cfg:
                cfg[k] = v
    # Insurance: keep our own copy of whatever is in force right now.
    _backup_settings(cfg, getattr(self, "_backup_name", "settings"))
    return cfg


def _truthy(v):
    if isinstance(v, str):
        return v.strip().lower() not in ("", "0", "false", "no", "off")
    return bool(v)


def _plugin_storage_dir():
    """No-prompt plugin storage folder, with a local fallback for tests."""
    try:
        storage = orca.host.plugin.storage()
        if storage:
            return storage
    except BaseException:
        pass
    return os.path.dirname(os.path.abspath(__file__))


def _state_path():
    return os.path.join(_plugin_storage_dir(), "unlayered_infill_state.json")


def _load_state():
    """What happened on previous exports. Empty dict if there is no history."""
    try:
        with open(_state_path(), "r", encoding="utf-8") as f:
            st = json.load(f)
        return st if isinstance(st, dict) else {}
    except Exception:
        return {}


def _save_state(state):
    try:
        with open(_state_path(), "w", encoding="utf-8") as f:
            json.dump(state, f)
    except Exception:
        pass


def _record_run(**fields):
    """Remember that the export step fired, and what it did.

    Which preset field drives Step.psGCodePostProcess differs between
    OrcaSlicer builds, so rather than read a setting whose name we cannot
    rely on, the setup check reports what was actually observed.
    """
    st = _load_state()
    st["seam_ever"] = True
    st["last_run_at"] = time.time()
    st.update(fields)
    _save_state(st)


# ---------------------------------------------------------------------------
#  Logging
#
#  Default logs live in Orca's plugin storage folder. Orca allows writes there
#  without prompting, so normal slicing should not ask the user to authorize a
#  log or state-file write. ORCA_PLUGIN_LOG_DIR remains as an explicit debug
#  override for local tests or a user who deliberately wants an external log.
# ---------------------------------------------------------------------------
LOG_NAME = "orca-plugins.log"
LOG_MAX_BYTES = 1000000          # roll over at ~1 MB so it cannot grow forever


def log_path():
    """Default no-prompt plugin-storage log path.

    ORCA_PLUGIN_LOG_DIR is an explicit debug override and may trigger Orca's
    audit prompt if it points outside plugin storage.
    """
    override = os.environ.get("ORCA_PLUGIN_LOG_DIR")
    if override:
        return os.path.join(override, LOG_NAME)
    return os.path.join(_plugin_storage_dir(), LOG_NAME)


def _log(headline, *detail, **kw):
    """Append one readable block. Never raises -- logging must not break a print.

    Both plugins in this repo append to the SAME file, so one paste of it
    shows the whole picture.
    """
    if not kw.get("enabled", True):
        return
    try:
        path = log_path()
        try:
            if os.path.getsize(path) > LOG_MAX_BYTES:
                os.replace(path, path + ".1")
        except OSError:
            pass
        stamp = time.strftime("%Y-%m-%d %H:%M:%S")
        pad = " " * len(stamp)
        with open(path, "a", encoding="utf-8") as f:
            f.write(f"{stamp}  {headline}\n")
            for line in detail:
                f.write(f"{pad}    {line}\n")
    except BaseException:
        # Deliberately broader than Exception: Orca's audit hook can raise
        # things that are not Exception subclasses, and losing a log line must
        # never be able to fail an export or ruin a print.
        pass


def _fmt_stats(stats):
    """The numbers that tell you whether it worked, in plain language."""
    lh = stats.get("layer_height_mm")
    noz = stats.get("nozzle_mm")
    out = [
        f"layer height : {lh:.3f} mm" if lh else "layer height : not found in the G-code",
        f"nozzle       : {noz:.3f} mm" if noz else "nozzle       : not named in the G-code",
        f"grid columns : {stats.get('cell_desc') or stats.get('cell_mm')}",
        f"amplitude    : {stats.get('amplitude_desc')}",
        # What each "auto" actually became on THIS print. Printing the word
        # "auto" back at the user tells them nothing.
        f"frequency    : {stats.get('frequency_desc') or stats.get('frequency')}",
        f"segment      : {stats.get('segment_desc')}",
        f"blend        : {stats.get('blend_desc')}",
        f"wave angle   : {stats.get('wave_angle_desc') or stats.get('wave_angle')}",
        f"Z ceiling    : {stats.get('max_lift_desc') or 'no ceiling'}",
        f"solid skin   : {stats.get('solid_layers')} layer height(s) over "
        f"{stats.get('solid_columns')} column(s)",
        f"infill runs  : {stats.get('sections')}",
        f"moves waved  : {stats.get('moves')}  ->  {stats.get('segments')} segment(s)",
        f"largest Z    : {stats.get('max_wiggle', 0.0):.3f} mm",
    ]
    if stats.get("skipped_unbracketed"):
        out.append(f"left flat    : {stats['skipped_unbracketed']} move(s) with no "
                   f"skin both above and below")
    return out


# NEVER log at import time. OrcaSlicer installs a CPython audit hook
# (PluginAuditManager) that categorises filesystem events, prompts the user,
# and persists per-plugin permissions. A write while the module is being
# imported happens during PluginLoader's load, outside any per-call audit
# scope -- at best it throws a permission prompt in the user's face mid-
# install, at worst it fails the load and the plugin "won't install".
# So the "loaded" line is emitted lazily, on the first capability call.
_LOADED_LOGGED = False


def _log_loaded_once():
    global _LOADED_LOGGED
    if _LOADED_LOGGED:
        return
    _LOADED_LOGGED = True
    _log(f"Unlayered Infill v{PLUGIN_VERSION} loaded "
         f"(engine {'ok' if npc else 'MISSING'})")


# Each pipeline step is logged the first time it is seen, and no more. That
# is bounded (there are only a handful of steps) and it is the single most
# useful diagnostic there is: it distinguishes "the plugin is not installed"
# (no log file) from "installed but never selected in the preset" (loaded,
# but no steps) from "it ran" (a psGCodePostProcess block).
_SEEN_STEPS = set()


class UnlayeredInfill(orca.slicing.SlicingPipelineCapabilityBase):
    def get_name(self):
        return "Unlayered Infill"

    def get_default_config(self):
        # Annotated, so the JSON panel in Orca explains itself. The notes are
        # ignored on the way back in (see _cfg).
        return annotated_defaults()

    def migrate_config_if_needed(self):
        """Orca's documented schema-migration hook.

        A config saved by an older release is missing every setting added
        since, and the Config panel shows that saved copy -- which is why
        `pattern` and `shape` were invisible to anyone who had used 0.3.4.
        Merge the new keys in, keep the user's values, write it back.
        """
        merged = _migrate_config(self, annotated_defaults(), self.get_name())
        _MIGRATED.add(self.get_name())
        try:
            version = self.get_config_version()
        except BaseException:
            version = ""
        return version, (merged if merged is not None else annotated_defaults())

    def execute(self, ctx):
        _log_loaded_once()
        # Belt and braces: the host is documented to call
        # migrate_config_if_needed(), but *when* is shown only by example and
        # is not verified on a real build. Doing it here too means one slice
        # is always enough to make the new settings appear in the panel.
        _migrate_once(self, annotated_defaults(), self.get_name())
        step = getattr(ctx, "step", None)
        step_name = getattr(step, "name", None) or str(step)

        # Every other step is somebody else's business.
        if step != orca.slicing.Step.psGCodePostProcess:
            if step_name not in _SEEN_STEPS:
                _SEEN_STEPS.add(step_name)
                _log(f"Unlayered Infill v{PLUGIN_VERSION}: pipeline step "
                     f"'{step_name}' seen (not ours, ignored)")
            return orca.ExecutionResult.success()

        cfg = _cfg(self)
        if not _truthy(cfg["enabled"]):
            return orca.ExecutionResult.success("Unlayered Infill: disabled")
        if npc is None:
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                "Unlayered Infill: the engine module is missing. Reinstall the "
                "plugin (the single-file build should have it inlined)."
                + (f"\nReason: {_ENGINE_ERROR}" if _ENGINE_ERROR else ""))

        path = getattr(ctx, "gcode_path", "") or ""
        if not path or not os.path.isfile(path):
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                f"Unlayered Infill: no G-code file to work on (gcode_path={path!r})")

        do_log = _truthy(cfg["log"])
        started = time.time()
        _log(f"Unlayered Infill v{PLUGIN_VERSION}: EXPORT STEP RUNNING",
             f"file         : {path}",
             f"settings     : amplitude={cfg['amplitude']!r} "
             f"frequency={cfg['frequency']!r} cell_mm={cfg['cell_mm']!r} "
             f"full_strength={cfg['full_strength']!r}",
             f"wave         : pattern={cfg['pattern']!r} "
             f"shape={cfg['shape']!r} angle={cfg['wave_angle']!r} "
             f"layer_phase={cfg['layer_phase']!r} "
             f"max_lift_mm={cfg['max_lift_mm']!r}",
             enabled=do_log)
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                lines = f.readlines()
            out, stats = npc.process(
                lines,
                amplitude_spec=cfg["amplitude"],
                frequency=cfg["frequency"],
                segment_mm=cfg["segment_mm"],
                require_relative_e=_truthy(cfg["require_relative_e"]),
                cell_mm=cfg["cell_mm"],
                blend_mm=cfg["blend_mm"],
                full_strength=_truthy(cfg["full_strength"]),
                pattern=cfg["pattern"],
                wave_angle=cfg["wave_angle"],
                shape=cfg["shape"],
                layer_phase=cfg["layer_phase"],
                max_lift_mm=cfg["max_lift_mm"],
            )
        except npc.NonPlanarError as e:
            # A clear, actionable stop -- surfaced as a slicing error. The seam
            # still demonstrably fired, so record that.
            _record_run(last_refused=str(e))
            _log("Unlayered Infill: REFUSED (file left untouched)",
                 *str(e).splitlines(), enabled=do_log)
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError, f"Unlayered Infill: {e}")
        except Exception as e:  # never corrupt an export over a bug in here
            _log(f"Unlayered Infill: INTERNAL ERROR ({type(e).__name__}: {e})",
                 "the file was left untouched; this is a bug, please report it",
                 *traceback.format_exc().splitlines()[-6:], enabled=do_log)
            return orca.ExecutionResult.success(
                f"Unlayered Infill: skipped, file left untouched "
                f"({type(e).__name__}: {e})")

        if stats["already_processed"]:
            # Orca ran the export step twice for one slice. The first call did
            # the work; waving again would double every displacement.
            _record_run(last_skipped="already waved")
            _log("Unlayered Infill: already waved, left as is",
                 "Orca ran the export step twice for one slice; doing it again "
                 "would double every displacement", enabled=do_log)
            return orca.ExecutionResult.success(
                "Unlayered Infill: already applied to this file, left as is")

        if not stats["moves"]:
            _record_run(last_moves=0, last_sections=stats["sections"])
            if stats["sections"] == 0:
                why = ("no sparse-infill sections in this file -- infill "
                       "density 0%, or an all-wall part")
            elif stats["solid_layers"] == 0:
                why = ("infill found but no solid skin -- the wave tapers "
                       "against the skin above and below, so check that "
                       "top/bottom shell layers are not 0")
            else:
                why = ("infill and skin both found, but no infill move sits "
                       "between skin above AND below in its own column")
            _log("Unlayered Infill: NOTHING CHANGED", *_fmt_stats(stats),
                 f"reason       : {why}", enabled=do_log)
            return orca.ExecutionResult.success(
                "Unlayered Infill: nothing to do — no sparse infill was found "
                "between two solid skins. Thin all-wall parts, 0% infill, and "
                "parts with no top/bottom solid layers have nothing to wave.")

        try:
            with open(path, "w", encoding="utf-8") as f:
                f.writelines(out)
        except Exception as e:
            _log(f"Unlayered Infill: COULD NOT WRITE THE G-CODE ({e})",
                 enabled=do_log)
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                f"Unlayered Infill: could not write the G-code: {e}")

        _record_run(last_moves=stats["moves"], last_sections=stats["sections"],
                    last_segments=stats["segments"], last_skipped=None,
                    last_refused=None, last_columns=stats["solid_columns"])
        _log("Unlayered Infill: DONE -- the G-code was rewritten",
             *_fmt_stats(stats),
             f"took         : {time.time() - started:.1f} s",
             "NOTE: Orca's 3D preview will NOT show this. To see it, drag the "
             "exported .gcode back into OrcaSlicer.", enabled=do_log)
        return orca.ExecutionResult.success(
            f"Unlayered Infill: {stats['moves']} infill move(s) across "
            f"{stats['sections']} section(s) rewritten as {stats['segments']} "
            f"wavy segment(s); amplitude {stats['amplitude_desc']}, "
            f"largest Z offset {stats['max_wiggle']:.3f} mm")


_CHECK_DEFAULTS = {
    "_READ_ME": (
        "Keys starting with _ are notes, not settings -- the plugin ignores "
        "them. This item reports whether Unlayered Infill is working and "
        "then explains every setting of the main Unlayered Infill capability."
    ),
    "_settings_guide": (
        "Show the full explanation of every Unlayered Infill setting after "
        "the diagnostics. Set false once you know them and you will get just "
        "the short status report."
    ),
    "settings_guide": True,
}


class UnlayeredInfillCheck(orca.script.ScriptPluginCapabilityBase):
    def get_name(self):
        return "Unlayered Infill - Check setup"

    def get_default_config(self):
        return dict(_CHECK_DEFAULTS)

    def migrate_config_if_needed(self):
        merged = _migrate_config(self, dict(_CHECK_DEFAULTS), self.get_name())
        _MIGRATED.add(self.get_name())
        try:
            version = self.get_config_version()
        except BaseException:
            version = ""
        return version, (merged if merged is not None else dict(_CHECK_DEFAULTS))

    def _want_guide(self):
        try:
            raw = json.loads(self.get_config() or "{}")
        except (AttributeError, TypeError, ValueError):
            return True
        value = raw.get("settings_guide", True)
        if isinstance(value, str):
            return value.strip().lower() not in ("false", "0", "no", "off")
        return bool(value)

    def execute(self):
        _log_loaded_once()
        _migrate_once(self, dict(_CHECK_DEFAULTS), self.get_name())
        lines = [f"Unlayered Infill v{PLUGIN_VERSION} -- setup check"]
        lines.append(f"engine: {'inlined/available' if npc else 'MISSING (rebuild)'}")
        if _ENGINE_ERROR:
            lines.append(f"engine load error: {_ENGINE_ERROR}")
        if npc is None:
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                "The engine module is missing — reinstall the plugin."
                + (f"\nReason: {_ENGINE_ERROR}" if _ENGINE_ERROR else ""))
        lines.append("dependencies: none (pure standard library, no restart needed)")
        lines.append("")
        st = _load_state()
        lines.append("--- what the last export actually did ---")
        if not st.get("seam_ever"):
            lines.append("The G-code step has NEVER RUN on this machine.")
            lines.append("")
            lines.append("Select it here:")
            lines.append("  Process preset -> Others -> Slicing Pipeline Plugin")
            lines.append("  -> Unlayered Infill")
            lines.append("")
            lines.append("That one field drives every step, including the")
            lines.append("G-code export step this plugin uses. Then slice,")
            lines.append("export, and run this check again.")
        elif st.get("last_refused"):
            lines.append("The G-code step ran, but the plugin refused:")
            lines.append(f"  {st['last_refused']}")
        else:
            lines.append(f"The G-code step ran: {st.get('last_moves', 0)} infill "
                         f"move(s) across {st.get('last_sections', 0)} section(s)")
            if not st.get("last_moves"):
                lines.append("...but there was no sparse infill between two")
                lines.append("solid skins to wave. Check infill density is not")
                lines.append("0% and the part has top/bottom solid layers.")
        lines.append("")
        lines.append("Your printer must use RELATIVE extrusion:")
        lines.append("  Printer Settings -> Advanced -> Use relative E distances")
        lines.append("Otherwise the plugin refuses to run rather than corrupt")
        lines.append("the file.")
        lines.append("")
        backup = _settings_backup()
        lines.append("")
        lines.append("--- your settings are backed up ---")
        if backup:
            changed = {k: v for k, v in backup["values"].items()
                       if k in _DEFAULTS and _DEFAULTS[k] != v}
            lines.append(f"{len(backup['values'])} setting(s) remembered, "
                         f"saved by v{backup.get('version', '?')} on "
                         f"{backup.get('saved_at', '?')}.")
            if changed:
                lines.append("Non-default values held: "
                             + ", ".join(f"{k}={json.dumps(v)}"
                                         for k, v in sorted(changed.items())))
            else:
                lines.append("All of them are at this build's defaults.")
            lines.append("If the Config panel ever comes back empty or reset,")
            lines.append("set restore_backup to true and slice once; these")
            lines.append("values go back and the flag returns to false.")
        else:
            lines.append("Nothing remembered yet -- a backup is taken every")
            lines.append("time this plugin runs.")
        lines.append("--- not seeing all the settings? ---")
        lines.append(f"This build has {len(_DEFAULTS)} settings. They are all")
        lines.append("listed further down. If the Config panel for")
        lines.append("\"Unlayered Infill\" shows FEWER than that, nothing is")
        lines.append("broken. OrcaSlicer saves each capability's settings in")
        lines.append("one global file and shows you that saved copy; settings")
        lines.append("added by a later version are not in a copy written by")
        lines.append("an older one. Your prints are unaffected either way --")
        lines.append("a setting that is missing from the file is used at its")
        lines.append("default; you just cannot see or change it.")
        lines.append("")
        lines.append("Since v0.4.2 the plugin repairs this itself: it merges")
        lines.append("the new settings into your saved copy, keeping every")
        lines.append("value you had set. Reopen the Config tab after running")
        lines.append("this check or slicing once, and they should be there.")
        lines.append("")
        lines.append("If they are still missing, do it by hand -- this always")
        lines.append("works and loses only your plugin settings:")
        lines.append("  1. Plugins dialog -> select Unlayered Infill")
        lines.append("  2. Config tab -> select the capability")
        lines.append("  3. Press \"Restore defaults\"")
        lines.append("That deletes the saved copy, so the panel falls back to")
        lines.append("this build's full default configuration.")
        lines.append("")
        lines.append("Still short? Then the installed plugin FILE is an older")
        lines.append("one. The version at the top of this report is the one")
        lines.append("really running -- if it is not the version you expected,")
        lines.append("run Orca-Plugins.bat again, then fully quit and reopen")
        lines.append("OrcaSlicer (not just close the window).")
        lines.append("")
        lines.append("--- log ---")
        lp = log_path()
        lines.append("Every run is appended without approval prompts to:")
        lines.append(f"  {lp}")
        if os.path.isfile(lp):
            try:
                size = os.path.getsize(lp)
                lines.append(f"  (exists, {size} bytes -- open it in Notepad)")
            except OSError:
                pass
        else:
            lines.append("  (not created yet -- it appears the first time the")
            lines.append("   plugin loads or runs)")
        lines.append("")
        lines.append("--- two things that are NOT bugs ---")
        lines.append("1. The 3D preview never shows this plugin's work. Orca")
        lines.append("   draws the preview from the slice; this runs after,")
        lines.append("   at export. Drag the exported .gcode back into Orca")
        lines.append("   to see the result.")
        lines.append("2. Post-processing only runs on 'Export G-code file'.")
        lines.append("   It does NOT run on Print or Send.")
        lines.append("")
        lines.append("EXPERIMENTAL: check the G-code Preview and print a small")
        lines.append("test part before trusting it on a long job.")
        lines.append("")
        lines.append("--- what changed recently ---")
        lines.extend(CHANGELOG_RECENT.splitlines())
        lines.append("")
        lines.append("Full history: plugins/unlayered-infill/CHANGELOG.md in the repo.")
        if self._want_guide():
            lines.append("")
            lines.extend(settings_guide_lines())
            lines.append("To hide this guide, set settings_guide to false in")
            lines.append("this item's own settings.")
        return orca.ExecutionResult.success("\n".join(lines))


@orca.plugin
class UnlayeredInfillPlugin(orca.base):
    def register_capabilities(self):
        orca.register_capability(UnlayeredInfill)
        orca.register_capability(UnlayeredInfillCheck)
