# /// script
# requires-python = ">=3.12"
# dependencies = []
#
# [tool.orcaslicer.plugin]
# name = "Unlayered Infill"
# description = "Non-planar sparse infill: rides a sine wave in Z so successive layers interlock instead of stacking as clean planes, tapering to flat where it meets the solid skin. | What's new in v0.4.0: The wave can now run in both directions at once (pattern)."
# author = "Unlayered Infill plugin lane"
# version = "0.4.0"
# ///
"""Unlayered Infill for OrcaSlicer — non-planar sparse infill.

Layer-aligned infill fails along the same planes the perimeters do, so a part
is only as strong as its weakest layer boundary. This rewrites sparse-infill
moves to ride a sine wave in Z, `dz = amplitude * scale * sin(f * x)`, so each
layer's infill keys into the one below. `scale` tapers to zero as the infill
approaches the solid skin above or below, leaving the skins flat.

WHY THIS ONE IS A POST-PROCESSOR
  The other plugins in this repo inject geometry at `Step.posSlice` and let
  Orca own flow, speed and cooling — see plugins/orca/README.md for the
  argument. Non-planar infill is the one case where that cannot work: a slice
  polygon is planar by construction, so there is no way to express a wave in Z
  through the slicing seam. This plugin therefore runs at
  `Step.psGCodePostProcess`, the supported seam for rewriting the exported
  file, where `ctx.gcode_path` points at the working G-code.

SETUP -- ONE preset field
  Process preset > Others > Slicing Pipeline Plugin > "Unlayered Infill".

  That single field is all there is. Both Print.cpp (geometry steps) and
  PostProcessor.cpp (the G-code export step this plugin uses) resolve the
  same preset capability refs, so selecting the capability once wires up
  every step. This plugin returns success() immediately for all the steps
  it does not care about.

  Slice once, then run "Unlayered Infill - Check setup": it reports whether
  the export step actually ran, so you never have to guess.

REQUIREMENTS
  * Relative extrusion (`M83`). Splitting moves under absolute E (`M82`) would
    corrupt the file, so the plugin refuses rather than produce bad G-code.
  * Pure standard library — no numpy, no shapely, no first-run dependency
    install, and no restart after installing.

Engine adapted from nonPlanarInfill.py, Copyright (c) 2025 Roman Tenger
(TenTech), GPL-3.0 — https://github.com/TengerTechnologies/NonPlanarInfill.
This file is likewise GPL-3.0. The five behavioural fixes relative to that
tool are documented in nonplanar_core.py and pinned by
plugins/orca-infill/tests/.
"""
import json
import os
import time

import orca

# The version this file was built as. Kept in lockstep with the PEP 723 header
# at the top (tests/test_installer.py fails if they drift), so everything that
# reports a version at runtime reports the one actually running.
PLUGIN_VERSION = "0.4.0"

# --- BEGIN changelog (generated by tools/sync_changelog.py) ---
CHANGELOG_RECENT = """\
v0.4.0  (2026-10-02)
   * The wave can now run in both directions at once (pattern). Until
     now the infill rode sin(frequency x) — a ripple that varies along X
     and only along X. That has a hole in it. An infill line running
     along Y crosses no ripple at all: every point on it has the same X,
     so the whole line is lifted to one height and set down flat. It
     keys into nothing. With the usual 45-degree infill you lose a
     little; with 0/90-degree infill, half your infill was doing no
     interlocking work. Set pattern to cross and the wave becomes an
     egg-crate rippling along both axes, so a line running in ANY
     direction still rises and falls.
   * wave_angle aims the ripples. Degrees, counter-clockwise, 0 being
     along X — the old behaviour. Turn them across your infill lines so
     every line crosses them. If you print 45-degree infill, try 45.
   * shape changes the profile: sine, triangle or square. Triangle has
     straight flanks and sharp peaks, so layers key together harder for
     the same height. Square keeps most of the infill at full offset
     with short ramps between crests. Square is a SATURATED sine, never
     a vertical step: no printer can move Z instantly, so a true square
     wave would just be a skipped step and a scar. All three share their
     zero crossings and peak positions, so swapping between them changes
     the character of the wave without moving it.
   * layer_phase stops every layer being a copy of the one below. At 0 —
     the old behaviour — each layer puts its crest at the same place, so
     the part ends up with a column of crests stacked on top of each
     other. Give it a small advance per layer and the crests walk
     sideways as the part grows, which is the thing that actually braids
     layers together. 180 puts each crest directly over the trough
     beneath it; 360 is a full turn and does nothing.
   * max_lift_mm is a hard ceiling on the Z movement. In millimetres,
     whatever amplitude and taper work out to; 0 means no ceiling. This
     is a safety net. The default amplitude is a SHARE OF LAYER HEIGHT,
     so raising layer height or amplitude without thinking can drive the
     nozzle up into material it has already printed. Set this and it
     cannot, and the run report tells you how many segments it caught.
   * Every setting now explains itself inside OrcaSlicer. The config
     panel carries a plain-English note above each setting, and
     Unlayered Infill - Check setup prints the full guide after the
     usual diagnostics — what each control does, in words, wrapped to
     fit Orca's message box. Set settings_guide to false on that item
     once you know them. OrcaSlicer only lets an item read its own
     settings, so the guide shows the defaults and says so, rather than
     printing a default and calling it your value.
   * The standalone tool gained the matching --pattern, --angle,
     --shape, --layer-phase and --max-lift options, and its report now
     names the wave it used.

v0.3.4  (2026-09-30)
   * The permanent package name is now simply Unlayered Infill. Release
     numbers will never be placed in the package or capability names
     again. Read the separate Version column for the installed release.
   * The complete 0.3.0 control set is pinned as the default
     configuration: percentage amplitude (200%), frequency, segment
     length, automatic nozzle-width grid, blending radius, and
     full-strength switch. The controls no longer depend on finding a
     configuration slot with an old versioned name.
   * This is the final naming migration. Reselect Unlayered Infill once
     after updating; future releases keep that exact identity.

v0.3.3  (2026-09-30)
   * Restored the Unlayered Infill v0.3.0 compatibility identity.
     Changing the plugin name in 0.3.2 made Orca look in a new
     configuration slot, so the owner's saved percentage amplitude,
     nozzle grid, blending, frequency, and full-strength controls
     appeared to stop working. The actual code was still present; this
     reconnects Orca to the configuration that worked in 0.3.0.
   * The current import-safety, logging, G-code, and updater fixes
     remain. This is not a rollback to the unsafe 0.3.0 source.
   * The real release remains visible as 0.3.3 in Orca's Version column,
     Check setup, logs, updater output, standalone tool, and G-code
     stamp.
"""
# --- END changelog ---

# nonplanar_core is inlined by build.py for the single-file install; during
# tests and development it is imported from src/ next to this file.
import sys as _sys, types as _types
# nonplanar_core.py inlined by build.py (single-file plugin). Registered in
# sys.modules so anything that resolves the module by name still works.
_NONPLANAR_CORE_SRC = "\"\"\"Non-planar infill engine: pure text in, pure text out, stdlib only.\n\nAdapted from `nonPlanarInfill.py`, Copyright (c) 2025 Roman Tenger (TenTech),\nGPL-3.0 \u2014 https://github.com/TengerTechnologies/NonPlanarInfill \u2014 by way of the\n\"Non-Planar Infill Tool\" kept verbatim at\n`my-plugins/unlayered-infill/reference/nonplanar_infill_tool.py`.\n\nThe idea is unchanged: inside sparse-infill sections, split each extrusion into\nshort segments and ride a sine wave in Z, `dz = amplitude * scale * sin(f * x)`,\nwith `scale` tapering to zero as the infill approaches the solid skin above or\nbelow it. Successive layers then interlock instead of stacking as clean planes.\n\nFive behaviours differ from the reference, each pinned by a test in\n`tests/test_nonplanar_core.py`:\n\n1. **Extrusion is attached to the right move.** In G-code the `E` on a line\n   describes the move that *ends* at that line's coordinates. The reference\n   read `(x, y)` off the current line as the segment *start* and `(x, y)` off\n   the next line as the end, so every stroke was printed with its neighbour's\n   extrusion. On a plain rectilinear layer that under-extrudes the long infill\n   strokes by ~44% and over-extrudes the short repositioning moves.\n\n2. **No duplicated points.** `segment_line()` returned both endpoints, so each\n   emitted stroke re-stated the previous stroke's final point *with a share of\n   the extrusion* \u2014 a zero-length extruding move, i.e. a blob, at every\n   junction (44 of them in a ten-layer test cube).\n\n3. **Z is restored on the way out.** The reference left the nozzle at whatever\n   displaced Z the last wave segment reached. Anything printed afterwards in\n   the same layer \u2014 gap fill, a top surface, the wipe \u2014 ran at that wrong\n   height until the next layer change reset it.\n\n4. **Orca's skins are recognised.** Solid layers were matched on\n   `\"solid infill\"` only. OrcaSlicer and Bambu Studio label the outermost\n   skins `;TYPE:Top surface` and `;TYPE:Bottom surface`, so the real bottom\n   was never found and the taper measured from the build plate instead. That\n   makes the wave far too aggressive right next to the bottom skin.\n\n5. **The taper can't inverate.** `next_top_layer` kept a stale value once the\n   nozzle rose above the topmost solid layer, which made `d_top` negative and\n   flipped the wave's sign. Infill that isn't bracketed by solid above *and*\n   below now simply gets no wave.\n\nSection markers are matched on `;TYPE:` lines only, and case-insensitively:\nPrusaSlicer writes `;TYPE:Internal infill`, Orca `;TYPE:Sparse infill`.\n\"\"\"\nimport bisect\nimport math\nimport re\n\nTYPE_PREFIX = \";type:\"\nINFILL_MARKERS = (\"internal infill\", \"sparse infill\")\n# \"internal solid infill\" contains \"solid infill\"; Orca/Bambu name the outer\n# skins \"top surface\" / \"bottom surface\", which the reference missed.\nSOLID_MARKERS = (\"solid infill\", \"top surface\", \"bottom surface\")\n\n# Amplitude is a share of the LAYER HEIGHT by default, not a fixed mm value:\n# \"200%\" on a 0.3 mm layer is 0.6 mm, and the same setting still makes sense\n# after you change layer height. Plain mm (\"-0.2\") and multiples (\"2x\") are\n# still accepted. Sign only phase-shifts a sine wave, so it barely matters.\nDEFAULT_AMPLITUDE = \"200%\"\nDEFAULT_FREQUENCY = 1.5\nDEFAULT_SEGMENT_MM = 1.0\n# XY resolution of the solid-column map. \"auto\" means one column per nozzle\n# diameter, read from the G-code -- the finest grid that still corresponds to\n# something the printer can actually lay down.\nDEFAULT_CELL_MM = \"auto\"\nFALLBACK_CELL_MM = 0.6       # used when the G-code does not name the nozzle\nDEFAULT_BLEND_MM = 2.0       # smooth the taper across this radius of columns\n\n# --- the shape of the wave -------------------------------------------------\n#\n# Up to 0.3.4 the displacement was always `sin(frequency * x)`: a ripple that\n# varies along X and along X only. That has one real weakness. An infill line\n# running along Y crosses no ripple at all -- every point on it has the same\n# X, so it gets one constant Z offset over its whole length. It is lifted,\n# not waved, and it keys into nothing. With the usual 45/135-degree infill\n# that costs little, but with 0/90-degree infill, or any line that happens to\n# run across the ripples, half the infill does no interlocking work.\n#\n# `pattern` fixes that, `angle` aims it, `shape` changes the profile, and\n# `layer_phase` stops every layer from being a copy of the one below.\n# Defaults reproduce 0.3.4 output exactly.\nPATTERNS = (\"linear\", \"cross\")\nDEFAULT_PATTERN = \"linear\"\n#   linear  ripples that vary along one axis only -- the 0.3.4 behaviour.\n#   cross   an egg-crate: ripples along BOTH axes at once, so a line running\n#           in any direction still goes up and down. Costs nothing extra and\n#           interlocks in two directions instead of one.\n\nDEFAULT_WAVE_ANGLE = 0.0     # degrees, counter-clockwise, 0 = ripples along X\n\nSHAPES = (\"sine\", \"triangle\", \"square\")\nDEFAULT_SHAPE = \"sine\"\n#   sine      the smooth classic.\n#   triangle  straight ramps into sharp peaks -- steeper flanks for the same\n#             peak height, so the layers key together harder.\n#   square    flat crests joined by short ramps: most of the infill sits at\n#             full offset instead of passing through it. It is a SATURATED\n#             sine, never a true square -- a vertical Z step is not printable.\nSQUARE_GAIN = 3.0            # how hard the sine is driven before clipping\n\nDEFAULT_LAYER_PHASE = 0.0    # degrees of extra phase per infill layer\n#   0 puts the crest of the wave at the same XY on every layer, so the part\n#   keeps a column of crests. Advancing the phase a little each layer makes\n#   the crests walk sideways, which is what actually braids the layers.\n#   180 puts each layer's crest exactly over the layer below's trough.\n\nDEFAULT_MAX_LIFT_MM = 0.0    # 0 = no clamp\n#   A hard ceiling on the Z displacement, in millimetres, whatever the\n#   amplitude and taper work out to. This is a safety net: \"200%\" of a\n#   0.3 mm layer is 0.6 mm, and if you then raise layer height or amplitude\n#   without thinking, the nozzle can be driven far enough up to hit the skin\n#   above or plough through already-printed material.\n\n# Stamped into the output so a second pass is a no-op. Orca can invoke\n# psGCodePostProcess more than once for one slice (file export and network\n# upload are separate calls), and waving an already-waved file would double\n# every displacement.\nMARKER_PREFIX = \"; unlayered-infill\"\nMARKER_VERSION = \"0.4.0\"\nMARKER = f\"{MARKER_PREFIX} v{MARKER_VERSION} (non-planar sparse infill)\\n\"\n\n_WORD = re.compile(r\"([A-Za-z])\\s*([-+]?\\d*\\.?\\d+)\")\n_Z = re.compile(r\"Z([-+]?\\d*\\.?\\d+)\")\n\n\nclass NonPlanarError(Exception):\n    \"\"\"A problem worth stopping for, explained in plain English.\"\"\"\n\n\ndef parse_words(line):\n    \"\"\"`G1 X1 Y2 E.5 ; comment` -> {'G':1.0,'X':1.0,'Y':2.0,'E':0.5}.\"\"\"\n    body = line.split(\";\", 1)[0]\n    if not body.strip():\n        return None\n    words = {}\n    for m in _WORD.finditer(body):\n        words.setdefault(m.group(1).upper(), float(m.group(2)))\n    return words or None\n\n\ndef section_name(line):\n    \"\"\"The section label if this is a `;TYPE:` line, else None.\"\"\"\n    low = line.lower()\n    if low.startswith(TYPE_PREFIX):\n        return low[len(TYPE_PREFIX):].strip()\n    return None\n\n\ndef is_infill_section(name):\n    return any(m in name for m in INFILL_MARKERS)\n\n\ndef is_solid_section(name):\n    return any(m in name for m in SOLID_MARKERS)\n\n\ndef detect_extrusion_mode(lines):\n    \"\"\"'relative' (M83), 'absolute' (M82), or 'unknown'.\"\"\"\n    head = \"\\n\".join(lines[:400])\n    if \"M83\" in head:\n        return \"relative\"\n    if \"M82\" in head:\n        return \"absolute\"\n    tail = \"\\n\".join(lines[-4000:])  # the slicer config block lives at the end\n    if \"relative_extrusion = 1\" in tail or \"use_relative_e_distances = 1\" in tail:\n        return \"relative\"\n    if \"relative_extrusion = 0\" in tail or \"use_relative_e_distances = 0\" in tail:\n        return \"absolute\"\n    return \"unknown\"\n\n\ndef detect_layer_height(lines):\n    \"\"\"The layer height actually being printed: the most common `;HEIGHT:`,\n    falling back to the slicer's `layer_height = ` config line.\"\"\"\n    heights = []\n    config_lh = None\n    for line in lines:\n        if line.startswith(\";HEIGHT:\"):\n            try:\n                heights.append(float(line[len(\";HEIGHT:\"):].strip()))\n            except ValueError:\n                pass\n        elif config_lh is None and \"layer_height\" in line:\n            m = re.search(r\";\\s*layer_height\\s*=\\s*(\\d*\\.?\\d+)\", line)\n            if m and \"first_layer\" not in line:\n                config_lh = float(m.group(1))\n    if heights:\n        from statistics import multimode\n        return max(multimode(heights))\n    return config_lh\n\n\ndef resolve_amplitude(spec, lines):\n    \"\"\"'-0.2' -> mm; '200%' / '-1.5x' -> that fraction of the layer height.\n\n    Returns (millimetres, human description).\n    \"\"\"\n    s = str(spec).strip()\n    if not s:\n        raise NonPlanarError(\n            \"No amplitude given. Use mm (e.g. -0.2), a percent of layer height \"\n            \"(e.g. -150%), or a multiple (e.g. -1.5x).\")\n    relative = s.endswith(\"%\") or s.lower().endswith(\"x\")\n    try:\n        value = float(s[:-1]) if relative else float(s)\n    except ValueError:\n        raise NonPlanarError(\n            f\"Could not understand amplitude {s!r}. Use mm (e.g. -0.2), a \"\n            f\"percent of layer height (e.g. -150%), or a multiple (e.g. -1.5x).\")\n    if not relative:\n        return value, f\"{value:.3f} mm (fixed value)\"\n    mult = value / 100.0 if s.endswith(\"%\") else value\n    lh = detect_layer_height(lines)\n    if lh is None:\n        raise NonPlanarError(\n            f\"You gave the amplitude as {s} of layer height, but this G-code has \"\n            \"no layer height in it (no ';HEIGHT:' comments and no \"\n            \"'layer_height =' config line). Give the amplitude in plain mm \"\n            \"instead, e.g. -0.2.\")\n    amp = mult * lh\n    return amp, f\"{s} of layer height {lh:.3f} mm = {amp:.3f} mm\"\n\n\ndef already_processed(lines):\n    \"\"\"Has this file already been waved? Then leave it completely alone.\"\"\"\n    return any(line.startswith(MARKER_PREFIX) for line in lines)\n\n\ndef waveform(shape, phase):\n    \"\"\"One cycle of the chosen profile at `phase` radians, in [-1, 1].\n\n    All three share their zero crossings and their peak positions, so\n    changing `shape` changes the character of the wave without moving it.\n    \"\"\"\n    if shape == \"sine\":\n        return math.sin(phase)\n    if shape == \"square\":\n        # A real square wave would ask the nozzle to step in Z instantly,\n        # which no printer can do and no extrusion can follow. Overdriving a\n        # sine and clipping it gives flat crests with short, printable ramps\n        # between them -- the useful part of a square wave, minus the cliff.\n        return max(-1.0, min(1.0, SQUARE_GAIN * math.sin(phase)))\n    if shape == \"triangle\":\n        t = (phase / (2.0 * math.pi)) % 1.0\n        return 4.0 * abs(((t - 0.25) % 1.0) - 0.5) - 1.0\n    raise NonPlanarError(\n        f\"Unknown wave shape {shape!r}. Use one of: {', '.join(SHAPES)}.\")\n\n\ndef resolve_shape(spec):\n    s = str(spec or DEFAULT_SHAPE).strip().lower()\n    if s not in SHAPES:\n        raise NonPlanarError(\n            f\"Unknown wave shape {spec!r}. Use one of: {', '.join(SHAPES)}.\")\n    return s\n\n\ndef resolve_pattern(spec):\n    s = str(spec or DEFAULT_PATTERN).strip().lower()\n    if s not in PATTERNS:\n        raise NonPlanarError(\n            f\"Unknown wave pattern {spec!r}. Use one of: \"\n            f\"{', '.join(PATTERNS)}.\")\n    return s\n\n\ndef displacement(x, y, pattern, shape, frequency, angle_rad, phase_rad):\n    \"\"\"The unit wave at a point: the bit that gets multiplied by amplitude.\n\n    Always within [-1, 1], so `max_lift_mm` and the amplitude mean what they\n    say no matter which pattern is chosen.\n    \"\"\"\n    cos_a, sin_a = math.cos(angle_rad), math.sin(angle_rad)\n    u = x * cos_a + y * sin_a\n    if pattern == \"linear\":\n        return waveform(shape, frequency * u + phase_rad)\n    # cross: the same ripple along the perpendicular axis as well. Averaging\n    # the two keeps the result inside [-1, 1]; adding them would double the\n    # amplitude the user asked for wherever two crests happened to meet.\n    v = -x * sin_a + y * cos_a\n    return 0.5 * (waveform(shape, frequency * u + phase_rad) +\n                  waveform(shape, frequency * v + phase_rad))\n\n\nclass SolidGrid:\n    \"\"\"Where the part has solid skin, mapped as a grid of XY columns.\n\n    A single global list of solid Z heights is only correct for a part whose\n    skins are flat planes spanning the whole footprint. Give it a ledge, a\n    bridge, a chamfered top, or two towers of different heights and it fails\n    in a way that matters: every column is told its roof is the *highest*\n    skin anywhere in the print, so infill directly under a low ledge thinks\n    it has metres of headroom and waves at full amplitude straight into it.\n\n    Recording solid heights per XY column instead gives every infill move a\n    floor and roof measured in its own column \u2014 the wave fades against the\n    skin it is actually about to hit.\n    \"\"\"\n\n    __slots__ = (\"cell\", \"columns\", \"_raw_cache\", \"_disc\")\n\n    def __init__(self, cell_mm=DEFAULT_CELL_MM):\n        self.cell = max(0.05, float(cell_mm))\n        self.columns = {}\n        self._raw_cache = {}\n        self._disc = None\n\n    def key(self, x, y):\n        c = self.cell\n        return (int(math.floor(x / c)), int(math.floor(y / c)))\n\n    def add_move(self, x0, y0, x1, y1, z):\n        \"\"\"Mark every column the solid extrusion (x0,y0)->(x1,y1) crosses.\"\"\"\n        zr = round(z, 4)\n        step = self.cell * 0.5\n        n = max(1, int(math.hypot(x1 - x0, y1 - y0) / step) + 1)\n        cols = self.columns\n        for i in range(n + 1):\n            t = i / n\n            cols.setdefault(self.key(x0 + t * (x1 - x0),\n                                     y0 + t * (y1 - y0)), set()).add(zr)\n\n    def finalize(self):\n        self.columns = {k: sorted(v) for k, v in self.columns.items()}\n        return self\n\n    def _raw(self, key, z, full_strength):\n        \"\"\"Taper for one column: 0 at its own skins, peak mid-span.\n\n        Returns None when the column has no solid at all (nothing to measure\n        against), which the blend treats as \"no opinion\" rather than zero.\n        \"\"\"\n        ck = (key, z)\n        hit = self._raw_cache.get(ck)\n        if hit is not None:\n            return hit[0]\n        zs = self.columns.get(key)\n        if not zs:\n            self._raw_cache[ck] = (None,)\n            return None\n        i = bisect.bisect_left(zs, z - 1e-9)\n        if i < len(zs) and abs(zs[i] - z) <= 1e-6:\n            val = 0.0                      # this column is solid right here\n        else:\n            below = zs[i - 1] if i > 0 else None\n            j = bisect.bisect_right(zs, z + 1e-9)\n            above = zs[j] if j < len(zs) else None\n            if below is None or above is None or above - below <= 0:\n                val = 0.0                  # unbracketed: no wave, no sign flip\n            else:\n                val = min(above - z, z - below) / (above - below)\n                if full_strength:\n                    val = min(1.0, val * 2.0)\n        self._raw_cache[ck] = (val,)\n        return val\n\n    def _offsets(self, blend_mm):\n        \"\"\"Cell offsets within the blend radius, computed once.\"\"\"\n        if self._disc is None:\n            r = min(8, int(math.ceil(blend_mm / self.cell)))\n            self._disc = [(dx, dy)\n                          for dx in range(-r, r + 1)\n                          for dy in range(-r, r + 1)\n                          if math.hypot(dx, dy) * self.cell <= blend_mm + 1e-9]\n        return self._disc\n\n    def scale(self, x, y, z, full_strength=False, blend_mm=DEFAULT_BLEND_MM):\n        \"\"\"Blended taper at a point.\n\n        Neighbouring columns can have very different floors and roofs \u2014 at the\n        edge of a ledge, one column's roof is 2 mm up and the next one's is\n        20 mm up. Taking each column's answer literally puts a step in the\n        wave exactly there. Averaging over a small disc turns that step into a\n        ramp, which is what `blend_mm` buys.\n\n        Columns with no solid recorded are skipped rather than counted as\n        zero: they are usually just gaps between solid extrusion lines, and\n        counting them would damp the wave everywhere.\n        \"\"\"\n        z = round(z, 4)\n        if blend_mm <= 0:\n            return self._raw(self.key(x, y), z, full_strength) or 0.0\n        ix, iy = self.key(x, y)\n        c = self.cell\n        total = weight = 0.0\n        for dx, dy in self._offsets(blend_mm):\n            val = self._raw((ix + dx, iy + dy), z, full_strength)\n            if val is None:\n                continue\n            # distance from the sample point to that column's centre\n            cx = (ix + dx + 0.5) * c\n            cy = (iy + dy + 0.5) * c\n            d = math.hypot(cx - x, cy - y)\n            w = 1.0 - d / blend_mm\n            if w <= 0.0:\n                continue\n            total += w * val\n            weight += w\n        return total / weight if weight > 0.0 else 0.0\n\n\ndef detect_nozzle_diameter(lines):\n    \"\"\"The nozzle diameter the slicer recorded, in mm, or None.\n\n    Orca writes `; nozzle_diameter = 0.6` into the config block at the end of\n    the file (comma-separated per extruder on a multi-tool machine; we take\n    the first). This is what makes the column grid match the printer instead\n    of being an arbitrary constant.\n    \"\"\"\n    for line in lines:\n        if \"nozzle_diameter\" not in line:\n            continue\n        m = re.search(r\";\\s*nozzle_diameter\\s*=\\s*([\\d.]+)\", line)\n        if m:\n            try:\n                v = float(m.group(1))\n            except ValueError:\n                continue\n            if 0.05 <= v <= 5.0:       # anything else is a misparse\n                return v\n    return None\n\n\ndef resolve_cell_mm(spec, lines):\n    \"\"\"'auto' -> the nozzle diameter; a number -> itself.\n\n    Returns (millimetres, human description).\n    \"\"\"\n    if spec is None or (isinstance(spec, str) and spec.strip().lower() in (\"\", \"auto\")):\n        nozzle = detect_nozzle_diameter(lines)\n        if nozzle is None:\n            return FALLBACK_CELL_MM, (\n                f\"{FALLBACK_CELL_MM:.3f} mm (auto, but this G-code does not \"\n                f\"name a nozzle diameter, so the default was used)\")\n        return nozzle, f\"{nozzle:.3f} mm (auto: one column per nozzle width)\"\n    try:\n        v = float(spec)\n    except (TypeError, ValueError):\n        raise NonPlanarError(\n            f\"Could not understand the grid cell size {spec!r}. Use 'auto' to \"\n            f\"follow the nozzle diameter, or a number of millimetres.\")\n    return v, f\"{v:.3f} mm (fixed value)\"\n\n\ndef build_solid_grid(lines, cell_mm=FALLBACK_CELL_MM):\n    \"\"\"Rasterise every solid-skin extrusion into an XY column map.\"\"\"\n    grid = SolidGrid(cell_mm)\n    x = y = None\n    z = 0.0\n    solid = False\n    solid_heights = set()\n    for line in lines:\n        name = section_name(line)\n        if name is not None:\n            solid = is_solid_section(name)\n            continue\n        words = parse_words(line)\n        if not words or words.get(\"G\") not in (0.0, 1.0):\n            continue\n        nx = words.get(\"X\", x)\n        ny = words.get(\"Y\", y)\n        if \"Z\" in words:\n            z = words[\"Z\"]\n        e = words.get(\"E\")\n        if solid and e is not None and e > 0 and None not in (x, y, nx, ny):\n            grid.add_move(x, y, nx, ny, z)\n            solid_heights.add(round(z, 4))\n        x, y = nx, ny\n    grid.finalize()\n    return grid, sorted(solid_heights)\n\n\ndef _empty_stats(**over):\n    base = {\"amplitude_mm\": 0.0, \"amplitude_desc\": \"\", \"extrusion_mode\": \"\",\n            \"solid_layers\": 0, \"solid_columns\": 0, \"sections\": 0, \"moves\": 0,\n            \"segments\": 0, \"max_wiggle\": 0.0, \"skipped_unbracketed\": 0,\n            \"already_processed\": False, \"cell_mm\": 0.0, \"cell_desc\": \"\",\n            \"nozzle_mm\": None, \"layer_height_mm\": None, \"blend_mm\": 2.0,\n            \"full_strength\": False, \"pattern\": DEFAULT_PATTERN,\n            \"wave_angle\": DEFAULT_WAVE_ANGLE, \"shape\": DEFAULT_SHAPE,\n            \"layer_phase\": DEFAULT_LAYER_PHASE,\n            \"max_lift_mm\": DEFAULT_MAX_LIFT_MM, \"clamped\": 0,\n            \"wave_layers\": 0}\n    base.update(over)\n    return base\n\n\ndef process(lines, amplitude_spec=DEFAULT_AMPLITUDE, frequency=DEFAULT_FREQUENCY,\n            segment_mm=DEFAULT_SEGMENT_MM, require_relative_e=True,\n            cell_mm=DEFAULT_CELL_MM, blend_mm=DEFAULT_BLEND_MM,\n            full_strength=False, pattern=DEFAULT_PATTERN,\n            wave_angle=DEFAULT_WAVE_ANGLE, shape=DEFAULT_SHAPE,\n            layer_phase=DEFAULT_LAYER_PHASE, max_lift_mm=DEFAULT_MAX_LIFT_MM):\n    \"\"\"Rewrite sparse-infill moves as wavy ones. Returns (out_lines, stats).\"\"\"\n    # Orca may run the export step twice for one slice (file + upload). Waving\n    # an already-waved file would double every displacement, so bail out.\n    if already_processed(lines):\n        return list(lines), _empty_stats(already_processed=True)\n\n    amplitude, amp_desc = resolve_amplitude(amplitude_spec, lines)\n\n    mode = detect_extrusion_mode(lines)\n    if mode == \"absolute\" and require_relative_e:\n        raise NonPlanarError(\n            \"This G-code uses ABSOLUTE extrusion (M82). Splitting moves would \"\n            \"corrupt it.\\n\\nFix: OrcaSlicer > Printer Settings > Advanced > \"\n            \"'Use relative E distances', then slice again.\")\n\n    cell_resolved, cell_desc = resolve_cell_mm(cell_mm, lines)\n    grid, solids = build_solid_grid(lines, cell_resolved)\n    frequency = float(frequency)\n    segment_mm = max(0.05, float(segment_mm))\n    blend_mm = max(0.0, float(blend_mm))\n    full_strength = bool(full_strength)\n    pattern = resolve_pattern(pattern)\n    shape = resolve_shape(shape)\n    angle_rad = math.radians(float(wave_angle))\n    layer_phase_rad = math.radians(float(layer_phase))\n    max_lift_mm = max(0.0, float(max_lift_mm))\n\n    out = []\n    x = y = z = None\n    in_infill = False\n    displaced = False           # nozzle currently sitting at a wave-shifted Z\n    sections = moves = segments = 0\n    max_wiggle = 0.0\n    skipped_unbracketed = 0\n    clamped = 0                 # segments the max_lift ceiling actually caught\n\n    # Which infill layer we are on, for `layer_phase`. Counted only at the\n    # heights where infill is really waved, and in the order they are met, so\n    # a Z-hop or a travel at some other height cannot advance the phase. The\n    # first waved layer is 0, which keeps `layer_phase` from moving anything\n    # when the feature is off.\n    layer_ordinal = {}\n\n    def restore_z():\n        \"\"\"Never leave the nozzle on the wave once the infill stroke ends.\"\"\"\n        nonlocal displaced\n        if displaced and z is not None:\n            out.append(f\"G1 Z{z:.3f}\\n\")\n            displaced = False\n\n    for line in lines:\n        name = section_name(line)\n        if name is not None:\n            was = in_infill\n            in_infill = is_infill_section(name)\n            if in_infill and not was:\n                sections += 1\n            if not in_infill:\n                restore_z()\n            out.append(line)\n            continue\n\n        words = parse_words(line)\n        if not words or words.get(\"G\") not in (0.0, 1.0):\n            out.append(line)\n            continue\n\n        nx = words.get(\"X\", x)\n        ny = words.get(\"Y\", y)\n        e = words.get(\"E\")\n\n        if \"Z\" in words:                 # the slicer's own Z always wins\n            z = words[\"Z\"]\n            displaced = False\n\n        movable = (in_infill and e is not None and e > 0 and \"Z\" not in words\n                   and None not in (x, y, z) and (nx != x or ny != y))\n        if movable:\n            # sample the taper at the midpoint of the stroke\n            scale = grid.scale((x + nx) * 0.5, (y + ny) * 0.5, z,\n                               full_strength, blend_mm)\n            if scale > 0.0:\n                length = math.hypot(nx - x, ny - y)\n                n = max(1, int(length // segment_mm))\n                feed = words.get(\"F\")\n                zr = round(z, 4)\n                if zr not in layer_ordinal:\n                    layer_ordinal[zr] = len(layer_ordinal)\n                phase_rad = layer_ordinal[zr] * layer_phase_rad\n                # Hand out the extrusion so the printed digits sum to exactly\n                # `e`. Rounding each segment independently drifts, and across\n                # a whole print that drift is systematic under/over-extrusion.\n                spent = 0.0\n                for i in range(1, n + 1):      # skip i=0: we are already there\n                    t = i / n\n                    sx = x + t * (nx - x)\n                    sy = y + t * (ny - y)\n                    dz = amplitude * scale * displacement(\n                        sx, sy, pattern, shape, frequency, angle_rad, phase_rad)\n                    if max_lift_mm and abs(dz) > max_lift_mm:\n                        dz = math.copysign(max_lift_mm, dz)\n                        clamped += 1\n                    if abs(dz) > max_wiggle:\n                        max_wiggle = abs(dz)\n                    share = round(e * t - spent, 5)\n                    spent += share\n                    tail = f\" F{feed:.0f}\" if (i == 1 and feed is not None) else \"\"\n                    out.append(f\"G1 X{sx:.3f} Y{sy:.3f} Z{z + dz:.3f} \"\n                               f\"E{share:.5f}{tail}\\n\")\n                segments += n\n                moves += 1\n                displaced = True\n                x, y = nx, ny\n                continue\n            skipped_unbracketed += 1\n\n        restore_z()\n        out.append(line)\n        x, y = nx, ny\n\n    restore_z()\n\n    if moves:\n        out.insert(0, MARKER)\n\n    return out, {\n        \"amplitude_mm\": amplitude,\n        \"amplitude_desc\": amp_desc,\n        \"extrusion_mode\": mode,\n        \"solid_layers\": len(solids),\n        \"solid_columns\": len(grid.columns),\n        \"sections\": sections,\n        \"moves\": moves,\n        \"segments\": segments,\n        \"max_wiggle\": max_wiggle,\n        \"skipped_unbracketed\": skipped_unbracketed,\n        \"already_processed\": False,\n        \"cell_mm\": grid.cell,\n        \"cell_desc\": cell_desc,\n        \"nozzle_mm\": detect_nozzle_diameter(lines),\n        \"layer_height_mm\": detect_layer_height(lines),\n        \"blend_mm\": blend_mm,\n        \"full_strength\": full_strength,\n        \"pattern\": pattern,\n        \"wave_angle\": float(wave_angle),\n        \"shape\": shape,\n        \"layer_phase\": float(layer_phase),\n        \"max_lift_mm\": max_lift_mm,\n        \"clamped\": clamped,\n        \"wave_layers\": len(layer_ordinal),\n    }\n"
npc = _types.ModuleType("nonplanar_core")
_sys.modules["nonplanar_core"] = npc
try:
    exec(compile(_NONPLANAR_CORE_SRC, "nonplanar_core (inlined)", "exec"), npc.__dict__)
except Exception:  # pragma: no cover - surfaced via the setup check / execute()
    _sys.modules.pop("nonplanar_core", None)
    npc = None


_DEFAULTS = {
    "enabled": True,
    # A share of the LAYER HEIGHT, so the setting keeps meaning when you
    # change layer height: "200%" on a 0.3 mm layer is 0.6 mm. Plain mm
    # ("-0.2") and multiples ("2x") still work. Sign only phase-shifts a sine
    # wave, so it makes almost no difference.
    "amplitude": "200%",
    # Ripples per mm along X.
    "frequency": 1.5,
    "segment_mm": 1.0,
    # XY resolution of the solid-skin map. "auto" = one column per nozzle
    # diameter, read from the G-code. Each column gets its own floor and roof,
    # so a local ledge or a short neighbouring tower cannot distort the taper
    # anywhere else in the part.
    "cell_mm": "auto",
    # Smooth the taper across this radius of columns, so the step between two
    # columns with very different roofs becomes a ramp instead of a kink.
    "blend_mm": 2.0,
    # The classic Tenger taper peaks at half the amplitude even mid-span.
    # Turning this on lets it reach the full amplitude in the middle while
    # still fading to nothing at the skins.
    "full_strength": False,
    # "linear" = ripples along one axis, the behaviour up to 0.3.4.
    # "cross"  = an egg-crate that ripples along both axes, so an infill line
    #            running in ANY direction still rises and falls. With linear,
    #            a line running across the ripples gets one constant offset
    #            and keys into nothing.
    "pattern": "linear",
    # Degrees to turn the ripples, counter-clockwise. 0 = ripples along X.
    "wave_angle": 0.0,
    # "sine", "triangle" (sharper peaks, steeper flanks) or "square" (flat
    # crests joined by short ramps -- a saturated sine, never a Z cliff).
    "shape": "sine",
    # Degrees of extra phase per waved layer, so the crests walk sideways
    # instead of stacking in a column. 180 puts a crest over the trough below.
    "layer_phase": 0.0,
    # Hard ceiling on the Z displacement in mm, whatever amplitude and taper
    # work out to. 0 = no ceiling.
    "max_lift_mm": 0.0,
    # Refuse to run on absolute-E G-code rather than corrupt it.
    "require_relative_e": True,
    # Append a human-readable record of every run to the plugin storage log.
    "log": True,
}


# Plain-English notes, shown two places: interleaved into the JSON config
# panel as `_key` entries, and printed in full by "Check setup". The owner
# should never have to find a README on GitHub to learn what a setting does.
_NOTES = {
    "_READ_ME": (
        "Keys starting with _ are notes, not settings -- the plugin ignores "
        "them. Edit the plain keys underneath each note. Run \"Unlayered "
        "Infill - Check setup\" to see these explanations with your own "
        "values filled in."
    ),
    "_enabled": (
        "Turn the whole plugin off without unselecting it in the preset."
    ),
    "_amplitude": (
        "How far the infill rides up and down in Z. A percent (\"200%\") or "
        "a multiple (\"2x\") is a share of your layer height, so it keeps "
        "meaning when you change layer height; a plain number (\"-0.2\") is "
        "millimetres. The sign only shifts the wave along, so it barely "
        "matters."
    ),
    "_frequency": (
        "Ripples per millimetre. Higher means tighter, more frequent waves. "
        "Much above about 3 and neighbouring crests start to merge into "
        "each other at normal line spacing."
    ),
    "_segment_mm": (
        "Each infill move is chopped into pieces this long to follow the "
        "wave. Smaller is smoother and makes a bigger file; much below "
        "0.5 mm mostly buys file size."
    ),
    "_cell_mm": (
        "How finely the solid skin above and below is mapped, in "
        "millimetres. \"auto\" uses one column per nozzle width, read from "
        "the G-code, which is as fine as the printer can actually resolve."
    ),
    "_blend_mm": (
        "Smooth the fade-out across this radius, in millimetres. Where a "
        "ledge makes one column's ceiling much lower than its neighbour's, "
        "this turns the step between them into a ramp."
    ),
    "_full_strength": (
        "Off, the wave peaks at half the amplitude even in the middle of a "
        "span. On, it reaches the full amplitude mid-span and still fades "
        "to nothing at the skins."
    ),
    "_pattern": (
        "\"linear\" ripples along one direction only. \"cross\" is an "
        "egg-crate that ripples along both, so infill lines running in any "
        "direction still rise and fall. With linear, a line that runs "
        "ACROSS the ripples gets one constant height for its whole length "
        "-- it is lifted, not waved, and keys into nothing. If your infill "
        "is 0/90 degrees, or you want interlocking in both directions, use "
        "cross."
    ),
    "_wave_angle": (
        "Degrees to turn the ripples, counter-clockwise, 0 being along X. "
        "Aim them across your infill direction so every line crosses them. "
        "With the common 45-degree infill, try 45. Ignored in practice by "
        "cross, which already covers both directions."
    ),
    "_shape": (
        "\"sine\" is the smooth classic. \"triangle\" has straight flanks "
        "and sharp peaks, so layers key together harder for the same "
        "height. \"square\" keeps most of the infill at full offset with "
        "short ramps between -- it is a saturated sine, never a vertical "
        "step, because no printer can move Z instantly."
    ),
    "_layer_phase": (
        "Degrees of extra phase added per waved layer. At 0 every layer's "
        "crest sits at the same place, leaving a column of crests. A small "
        "advance walks the crests sideways as the part grows, which is what "
        "actually braids the layers together. 180 puts each crest directly "
        "over the trough below it; 360 is a full turn and changes nothing."
    ),
    "_max_lift_mm": (
        "A hard ceiling on the Z displacement, in millimetres, whatever the "
        "amplitude and taper work out to. 0 means no ceiling. This is a "
        "safety net: raise layer height or amplitude without thinking and "
        "the nozzle can be driven up into material it has already printed."
    ),
    "_require_relative_e": (
        "Refuse to run on absolute-E G-code instead of corrupting it. Leave "
        "this on. The fix is Printer Settings > Advanced > Use relative E "
        "distances."
    ),
    "_log": (
        "Append a readable record of every export to the log file named by "
        "Check setup."
    ),
}


def settings_guide_lines(cfg=None, width=72):
    """The notes as readable text, for printing inside OrcaSlicer.

    `cfg` is the live config, so the guide shows the value actually in force
    rather than the default.
    """
    # Orca gives a capability its OWN config and no one else's, so this item
    # cannot read what you set on the main Unlayered Infill capability. Say
    # so rather than print a default and call it "your value".
    live = cfg or _DEFAULTS
    out = ["--- what every setting means ---"]
    if cfg is None:
        out += ["The values below are the DEFAULTS. OrcaSlicer only lets an",
                "item read its own settings, so this check cannot see what",
                "you changed on the main Unlayered Infill capability -- open",
                "that item to see and edit your own values. The same notes",
                "are in its config panel, as the entries beginning with an",
                "underscore."]
    else:
        out += ["Your current value is shown first; (default X) follows when",
                "you have changed it. The same notes are in the config panel",
                "as the entries beginning with an underscore."]
    out.append("")
    for key, default in _DEFAULTS.items():
        note = _NOTES.get("_" + key)
        if not note:
            continue
        value = live.get(key, default)
        head = f"{key} = {json.dumps(value)}"
        if value != default:
            head += f"   (default {json.dumps(default)})"
        out.append(head)
        # Wrap by hand: Orca shows this in a plain message box, which clips
        # long lines rather than reflowing them.
        line = "   "
        for word in note.split():
            if len(line) + len(word) + 1 > width:
                out.append(line)
                line = "   "
            line += (" " if line.strip() else "") + word
        if line.strip():
            out.append(line)
        out.append("")
    return out


def annotated_defaults():
    """`_DEFAULTS` with each setting preceded by its plain-English note.

    This is what the user actually sees and edits in OrcaSlicer, so it is
    built fresh every time (never hand out `_DEFAULTS` itself to be mutated)
    and ordered note-then-setting.
    """
    out = {"_READ_ME": _NOTES["_READ_ME"]}
    for key, value in _DEFAULTS.items():
        note = _NOTES.get("_" + key)
        if note:
            out["_" + key] = note
        out[key] = value
    return out


def _cfg(self):
    try:
        src = json.loads(self.get_config() or "{}")
    except (AttributeError, TypeError, ValueError):
        src = {}
    cfg = dict(_DEFAULTS)
    if isinstance(src, dict):
        for k, v in src.items():
            if k in cfg:
                cfg[k] = v
    return cfg


def _truthy(v):
    if isinstance(v, str):
        return v.strip().lower() not in ("", "0", "false", "no", "off")
    return bool(v)


def _plugin_storage_dir():
    """No-prompt plugin storage folder, with a local fallback for tests."""
    try:
        storage = orca.host.plugin.storage()
        if storage:
            return storage
    except BaseException:
        pass
    return os.path.dirname(os.path.abspath(__file__))


def _state_path():
    return os.path.join(_plugin_storage_dir(), "unlayered_infill_state.json")


def _load_state():
    """What happened on previous exports. Empty dict if there is no history."""
    try:
        with open(_state_path(), "r", encoding="utf-8") as f:
            st = json.load(f)
        return st if isinstance(st, dict) else {}
    except Exception:
        return {}


def _save_state(state):
    try:
        with open(_state_path(), "w", encoding="utf-8") as f:
            json.dump(state, f)
    except Exception:
        pass


def _record_run(**fields):
    """Remember that the export step fired, and what it did.

    Which preset field drives Step.psGCodePostProcess differs between
    OrcaSlicer builds, so rather than read a setting whose name we cannot
    rely on, the setup check reports what was actually observed.
    """
    st = _load_state()
    st["seam_ever"] = True
    st["last_run_at"] = time.time()
    st.update(fields)
    _save_state(st)


# ---------------------------------------------------------------------------
#  Logging
#
#  Default logs live in Orca's plugin storage folder. Orca allows writes there
#  without prompting, so normal slicing should not ask the user to authorize a
#  log or state-file write. ORCA_PLUGIN_LOG_DIR remains as an explicit debug
#  override for local tests or a user who deliberately wants an external log.
# ---------------------------------------------------------------------------
LOG_NAME = "orca-plugins.log"
LOG_MAX_BYTES = 1000000          # roll over at ~1 MB so it cannot grow forever


def log_path():
    """Default no-prompt plugin-storage log path.

    ORCA_PLUGIN_LOG_DIR is an explicit debug override and may trigger Orca's
    audit prompt if it points outside plugin storage.
    """
    override = os.environ.get("ORCA_PLUGIN_LOG_DIR")
    if override:
        return os.path.join(override, LOG_NAME)
    return os.path.join(_plugin_storage_dir(), LOG_NAME)


def _log(headline, *detail, **kw):
    """Append one readable block. Never raises -- logging must not break a print.

    Both plugins in this repo append to the SAME file, so one paste of it
    shows the whole picture.
    """
    if not kw.get("enabled", True):
        return
    try:
        path = log_path()
        try:
            if os.path.getsize(path) > LOG_MAX_BYTES:
                os.replace(path, path + ".1")
        except OSError:
            pass
        stamp = time.strftime("%Y-%m-%d %H:%M:%S")
        pad = " " * len(stamp)
        with open(path, "a", encoding="utf-8") as f:
            f.write(f"{stamp}  {headline}\n")
            for line in detail:
                f.write(f"{pad}    {line}\n")
    except BaseException:
        # Deliberately broader than Exception: Orca's audit hook can raise
        # things that are not Exception subclasses, and losing a log line must
        # never be able to fail an export or ruin a print.
        pass


def _fmt_stats(stats):
    """The numbers that tell you whether it worked, in plain language."""
    lh = stats.get("layer_height_mm")
    noz = stats.get("nozzle_mm")
    out = [
        f"layer height : {lh:.3f} mm" if lh else "layer height : not found in the G-code",
        f"nozzle       : {noz:.3f} mm" if noz else "nozzle       : not named in the G-code",
        f"grid columns : {stats.get('cell_desc') or stats.get('cell_mm')}",
        f"amplitude    : {stats.get('amplitude_desc')}",
        f"solid skin   : {stats.get('solid_layers')} layer height(s) over "
        f"{stats.get('solid_columns')} column(s)",
        f"infill runs  : {stats.get('sections')}",
        f"moves waved  : {stats.get('moves')}  ->  {stats.get('segments')} segment(s)",
        f"largest Z    : {stats.get('max_wiggle', 0.0):.3f} mm",
    ]
    if stats.get("skipped_unbracketed"):
        out.append(f"left flat    : {stats['skipped_unbracketed']} move(s) with no "
                   f"skin both above and below")
    return out


# NEVER log at import time. OrcaSlicer installs a CPython audit hook
# (PluginAuditManager) that categorises filesystem events, prompts the user,
# and persists per-plugin permissions. A write while the module is being
# imported happens during PluginLoader's load, outside any per-call audit
# scope -- at best it throws a permission prompt in the user's face mid-
# install, at worst it fails the load and the plugin "won't install".
# So the "loaded" line is emitted lazily, on the first capability call.
_LOADED_LOGGED = False


def _log_loaded_once():
    global _LOADED_LOGGED
    if _LOADED_LOGGED:
        return
    _LOADED_LOGGED = True
    _log(f"Unlayered Infill v{PLUGIN_VERSION} loaded "
         f"(engine {'ok' if npc else 'MISSING'})")


# Each pipeline step is logged the first time it is seen, and no more. That
# is bounded (there are only a handful of steps) and it is the single most
# useful diagnostic there is: it distinguishes "the plugin is not installed"
# (no log file) from "installed but never selected in the preset" (loaded,
# but no steps) from "it ran" (a psGCodePostProcess block).
_SEEN_STEPS = set()


class UnlayeredInfill(orca.slicing.SlicingPipelineCapabilityBase):
    def get_name(self):
        return "Unlayered Infill"

    def get_default_config(self):
        # Annotated, so the JSON panel in Orca explains itself. The notes are
        # ignored on the way back in (see _cfg).
        return annotated_defaults()

    def execute(self, ctx):
        _log_loaded_once()
        step = getattr(ctx, "step", None)
        step_name = getattr(step, "name", None) or str(step)

        # Every other step is somebody else's business.
        if step != orca.slicing.Step.psGCodePostProcess:
            if step_name not in _SEEN_STEPS:
                _SEEN_STEPS.add(step_name)
                _log(f"Unlayered Infill v{PLUGIN_VERSION}: pipeline step "
                     f"'{step_name}' seen (not ours, ignored)")
            return orca.ExecutionResult.success()

        cfg = _cfg(self)
        if not _truthy(cfg["enabled"]):
            return orca.ExecutionResult.success("Unlayered Infill: disabled")
        if npc is None:
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                "Unlayered Infill: the engine module is missing. Reinstall the "
                "plugin (the single-file build should have it inlined).")

        path = getattr(ctx, "gcode_path", "") or ""
        if not path or not os.path.isfile(path):
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                f"Unlayered Infill: no G-code file to work on (gcode_path={path!r})")

        do_log = _truthy(cfg["log"])
        started = time.time()
        _log(f"Unlayered Infill v{PLUGIN_VERSION}: EXPORT STEP RUNNING",
             f"file         : {path}",
             f"settings     : amplitude={cfg['amplitude']!r} "
             f"frequency={cfg['frequency']!r} cell_mm={cfg['cell_mm']!r} "
             f"full_strength={cfg['full_strength']!r}",
             f"wave         : pattern={cfg['pattern']!r} "
             f"shape={cfg['shape']!r} angle={cfg['wave_angle']!r} "
             f"layer_phase={cfg['layer_phase']!r} "
             f"max_lift_mm={cfg['max_lift_mm']!r}",
             enabled=do_log)
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                lines = f.readlines()
            out, stats = npc.process(
                lines,
                amplitude_spec=cfg["amplitude"],
                frequency=cfg["frequency"],
                segment_mm=cfg["segment_mm"],
                require_relative_e=_truthy(cfg["require_relative_e"]),
                cell_mm=cfg["cell_mm"],
                blend_mm=cfg["blend_mm"],
                full_strength=_truthy(cfg["full_strength"]),
                pattern=cfg["pattern"],
                wave_angle=cfg["wave_angle"],
                shape=cfg["shape"],
                layer_phase=cfg["layer_phase"],
                max_lift_mm=cfg["max_lift_mm"],
            )
        except npc.NonPlanarError as e:
            # A clear, actionable stop -- surfaced as a slicing error. The seam
            # still demonstrably fired, so record that.
            _record_run(last_refused=str(e))
            _log("Unlayered Infill: REFUSED (file left untouched)",
                 *str(e).splitlines(), enabled=do_log)
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError, f"Unlayered Infill: {e}")
        except Exception as e:  # never corrupt an export over a bug in here
            import traceback
            _log(f"Unlayered Infill: INTERNAL ERROR ({type(e).__name__}: {e})",
                 "the file was left untouched; this is a bug, please report it",
                 *traceback.format_exc().splitlines()[-6:], enabled=do_log)
            return orca.ExecutionResult.success(
                f"Unlayered Infill: skipped, file left untouched "
                f"({type(e).__name__}: {e})")

        if stats["already_processed"]:
            # Orca ran the export step twice for one slice. The first call did
            # the work; waving again would double every displacement.
            _record_run(last_skipped="already waved")
            _log("Unlayered Infill: already waved, left as is",
                 "Orca ran the export step twice for one slice; doing it again "
                 "would double every displacement", enabled=do_log)
            return orca.ExecutionResult.success(
                "Unlayered Infill: already applied to this file, left as is")

        if not stats["moves"]:
            _record_run(last_moves=0, last_sections=stats["sections"])
            if stats["sections"] == 0:
                why = ("no sparse-infill sections in this file -- infill "
                       "density 0%, or an all-wall part")
            elif stats["solid_layers"] == 0:
                why = ("infill found but no solid skin -- the wave tapers "
                       "against the skin above and below, so check that "
                       "top/bottom shell layers are not 0")
            else:
                why = ("infill and skin both found, but no infill move sits "
                       "between skin above AND below in its own column")
            _log("Unlayered Infill: NOTHING CHANGED", *_fmt_stats(stats),
                 f"reason       : {why}", enabled=do_log)
            return orca.ExecutionResult.success(
                "Unlayered Infill: nothing to do — no sparse infill was found "
                "between two solid skins. Thin all-wall parts, 0% infill, and "
                "parts with no top/bottom solid layers have nothing to wave.")

        try:
            with open(path, "w", encoding="utf-8") as f:
                f.writelines(out)
        except Exception as e:
            _log(f"Unlayered Infill: COULD NOT WRITE THE G-CODE ({e})",
                 enabled=do_log)
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                f"Unlayered Infill: could not write the G-code: {e}")

        _record_run(last_moves=stats["moves"], last_sections=stats["sections"],
                    last_segments=stats["segments"], last_skipped=None,
                    last_refused=None, last_columns=stats["solid_columns"])
        _log("Unlayered Infill: DONE -- the G-code was rewritten",
             *_fmt_stats(stats),
             f"took         : {time.time() - started:.1f} s",
             "NOTE: Orca's 3D preview will NOT show this. To see it, drag the "
             "exported .gcode back into OrcaSlicer.", enabled=do_log)
        return orca.ExecutionResult.success(
            f"Unlayered Infill: {stats['moves']} infill move(s) across "
            f"{stats['sections']} section(s) rewritten as {stats['segments']} "
            f"wavy segment(s); amplitude {stats['amplitude_desc']}, "
            f"largest Z offset {stats['max_wiggle']:.3f} mm")


_CHECK_DEFAULTS = {
    "_READ_ME": (
        "Keys starting with _ are notes, not settings -- the plugin ignores "
        "them. This item reports whether Unlayered Infill is working and "
        "then explains every setting of the main Unlayered Infill capability."
    ),
    "_settings_guide": (
        "Show the full explanation of every Unlayered Infill setting after "
        "the diagnostics. Set false once you know them and you will get just "
        "the short status report."
    ),
    "settings_guide": True,
}


class UnlayeredInfillCheck(orca.script.ScriptPluginCapabilityBase):
    def get_name(self):
        return "Unlayered Infill - Check setup"

    def get_default_config(self):
        return dict(_CHECK_DEFAULTS)

    def _want_guide(self):
        try:
            raw = json.loads(self.get_config() or "{}")
        except (AttributeError, TypeError, ValueError):
            return True
        value = raw.get("settings_guide", True)
        if isinstance(value, str):
            return value.strip().lower() not in ("false", "0", "no", "off")
        return bool(value)

    def execute(self):
        _log_loaded_once()
        lines = [f"Unlayered Infill v{PLUGIN_VERSION} -- setup check"]
        lines.append(f"engine: {'inlined/available' if npc else 'MISSING (rebuild)'}")
        if npc is None:
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                "The engine module is missing — reinstall the plugin.")
        lines.append("dependencies: none (pure standard library, no restart needed)")
        lines.append("")
        st = _load_state()
        lines.append("--- what the last export actually did ---")
        if not st.get("seam_ever"):
            lines.append("The G-code step has NEVER RUN on this machine.")
            lines.append("")
            lines.append("Select it here:")
            lines.append("  Process preset -> Others -> Slicing Pipeline Plugin")
            lines.append("  -> Unlayered Infill")
            lines.append("")
            lines.append("That one field drives every step, including the")
            lines.append("G-code export step this plugin uses. Then slice,")
            lines.append("export, and run this check again.")
        elif st.get("last_refused"):
            lines.append("The G-code step ran, but the plugin refused:")
            lines.append(f"  {st['last_refused']}")
        else:
            lines.append(f"The G-code step ran: {st.get('last_moves', 0)} infill "
                         f"move(s) across {st.get('last_sections', 0)} section(s)")
            if not st.get("last_moves"):
                lines.append("...but there was no sparse infill between two")
                lines.append("solid skins to wave. Check infill density is not")
                lines.append("0% and the part has top/bottom solid layers.")
        lines.append("")
        lines.append("Your printer must use RELATIVE extrusion:")
        lines.append("  Printer Settings -> Advanced -> Use relative E distances")
        lines.append("Otherwise the plugin refuses to run rather than corrupt")
        lines.append("the file.")
        lines.append("")
        lines.append("--- log ---")
        lp = log_path()
        lines.append("Every run is appended without approval prompts to:")
        lines.append(f"  {lp}")
        if os.path.isfile(lp):
            try:
                size = os.path.getsize(lp)
                lines.append(f"  (exists, {size} bytes -- open it in Notepad)")
            except OSError:
                pass
        else:
            lines.append("  (not created yet -- it appears the first time the")
            lines.append("   plugin loads or runs)")
        lines.append("")
        lines.append("--- two things that are NOT bugs ---")
        lines.append("1. The 3D preview never shows this plugin's work. Orca")
        lines.append("   draws the preview from the slice; this runs after,")
        lines.append("   at export. Drag the exported .gcode back into Orca")
        lines.append("   to see the result.")
        lines.append("2. Post-processing only runs on 'Export G-code file'.")
        lines.append("   It does NOT run on Print or Send.")
        lines.append("")
        lines.append("EXPERIMENTAL: check the G-code Preview and print a small")
        lines.append("test part before trusting it on a long job.")
        lines.append("")
        lines.append("--- what changed recently ---")
        lines.extend(CHANGELOG_RECENT.splitlines())
        lines.append("")
        lines.append("Full history: plugins/unlayered-infill/CHANGELOG.md in the repo.")
        if self._want_guide():
            lines.append("")
            lines.extend(settings_guide_lines())
            lines.append("To hide this guide, set settings_guide to false in")
            lines.append("this item's own settings.")
        return orca.ExecutionResult.success("\n".join(lines))


@orca.plugin
class UnlayeredInfillPlugin(orca.base):
    def register_capabilities(self):
        orca.register_capability(UnlayeredInfill)
        orca.register_capability(UnlayeredInfillCheck)
