# /// script
# requires-python = ">=3.12"
# dependencies = ["numpy>=2.0", "shapely>=2.0"]
#
# [tool.orcaslicer.plugin]
# name = "Wave Overhangs Geometry"
# description = "Experimental preview-visible Wave geometry for OrcaSlicer. Replaces reachable unsupported slice area with narrow Wave ribbons before perimeters and infill are generated. | What's new in v0.1.0: Added a separate posSlice prototype that changes Orca's live slice geometry before perimeter and infill generation."
# author = "Wave Overhangs plugin lane"
# version = "0.1.0"
# ///
"""Preview-visible geometry-stage Wave Overhangs prototype.

This is intentionally a separate plugin from Wave Overhangs. The stable plugin
waits for exported Bridge G-code and is still the fallback. This prototype runs
at ``posSlice`` and edits Orca's live slicing graph instead:

* the previous layer supplies the support footprint;
* the current slice is split into supported material and reachable overhang;
* fixed-spacing Wave fronts are turned into narrow polygon ribbons;
* the ribbons are written back into LayerRegion.slices;
* Orca's normal perimeter/infill stages continue from that edited geometry.

The current Python host API does not provide a writable ExtrusionPath collection.
Therefore this plugin cannot inject a raw Wave polyline directly into Orca's
extrusion graph. It creates preview-visible Wave ribbon geometry, which Orca
then turns into ordinary toolpaths. That distinction is reported by Check setup
and is kept visible in the documentation; it must not be described as a direct
ExtrusionPath injector until Orca exposes that mutator.

Every geometry edit is contained in the execute call. Invalid or incomplete
host bindings leave the slice unchanged and return a recoverable result.
"""
from __future__ import annotations

import json
import math
import os
import time

try:
    # Import at module load so Orca's audit hook cannot block a lazy import
    # during execute(). Orca installs these dependencies for the plugin; the
    # fallback keeps Diagnostics and the audit test usable if they are absent.
    import numpy as np
    import shapely
    from shapely.geometry import GeometryCollection, LineString, MultiPolygon, Polygon
    from shapely.ops import linemerge, unary_union
    _DEPS_ERROR = None
except ImportError as exc:  # pragma: no cover - exercised without Orca deps
    np = None
    shapely = None
    GeometryCollection = LineString = MultiPolygon = Polygon = None
    linemerge = unary_union = None
    _DEPS_ERROR = f"Wave Overhangs Geometry needs numpy and shapely: {exc}"

import orca


PLUGIN_VERSION = "0.1.0"
MARKER = "; wave-overhangs-geometry v0.1.0"
_SCALE = 1_000_000.0
_LOADED_LOGGED = False

_DEFAULTS = {
    "enabled": True,
    "line_spacing": 0.35,
    "line_width": 0.40,
    "overhang_tol": 0.05,
    "min_overhang_area": 0.5,
    "perimeter_overlap": 0.10,
    "min_wave_length": 1.0,
    "simplify_tolerance": 0.05,
    "max_iterations": 400,
}

# --- BEGIN changelog (generated by tools/sync_changelog.py) ---
CHANGELOG_RECENT = """\
v0.1.0  (2026-10-01)
   * Added a separate posSlice prototype that changes Orca's live slice
     geometry before perimeter and infill generation.
   * Added obstacle-aware fixed-spacing Wave fronts around holes and
     concave boundaries.
   * Added fail-closed mutation handling and a setup check that reports
     the preview-visible ribbon behavior.
   * Documented the current API boundary: existing ExtrusionPath objects
     are read-only, so the prototype supplies narrow Wave geometry
     ribbons rather than injecting raw extrusion paths. This is an
     experimental geometry-stage prototype. A fresh real-Orca slice and
     physical print are required before it can replace the
     post-processing plugin.
"""
# --- END changelog ---


def _cfg(capability):
    """Read the capability JSON without depending on a preset key."""
    cfg = dict(_DEFAULTS)
    try:
        raw = capability.get_config()
        if raw:
            data = json.loads(raw) if isinstance(raw, str) else raw
            if isinstance(data, dict):
                cfg.update(data)
    except BaseException:
        # Bad optional configuration must not damage the user's slice.
        pass
    return cfg


def _iter_polygons(geom):
    if geom is None or geom.is_empty:
        return
    if isinstance(geom, Polygon):
        yield geom
    elif isinstance(geom, MultiPolygon):
        yield from geom.geoms
    elif isinstance(geom, GeometryCollection):
        for child in geom.geoms:
            yield from _iter_polygons(child)


def _iter_lines(geom):
    if geom is None or geom.is_empty:
        return
    if isinstance(geom, LineString):
        yield geom
    elif hasattr(geom, "geoms"):
        for child in geom.geoms:
            yield from _iter_lines(child)


def _ring_xy(ring):
    """Return a Shapely ring without its repeated closing coordinate."""
    coords = [(float(p.x) / _SCALE, float(p.y) / _SCALE)
              for p in ring.points]
    if len(coords) > 1 and coords[0] == coords[-1]:
        coords.pop()
    return coords


def _expolygon_shape(expolygon):
    contour = _ring_xy(expolygon.contour)
    holes = [_ring_xy(hole) for hole in expolygon.holes]
    if len(contour) < 3:
        return Polygon()
    shape = Polygon(contour, holes)
    return shape if shape.is_valid else shape.buffer(0)


def _surface_shape(surface):
    return _expolygon_shape(surface.expolygon)


def _union_shapes(shapes):
    shapes = [shape for shape in shapes if shape is not None and not shape.is_empty]
    if not shapes:
        return Polygon()
    result = unary_union(shapes)
    return result if result.is_valid else result.buffer(0)


def _layer_region_shapes(layer):
    """Read the current region surfaces before any mutation."""
    regions = list(layer.regions())
    data = []
    for region in regions:
        surfaces = list(region.slices.surfaces)
        data.append((region, surfaces, [_surface_shape(s) for s in surfaces]))
    return data


def _layer_shape_from_lslices(layer):
    try:
        return _union_shapes([_expolygon_shape(exp) for exp in layer.lslices()])
    except BaseException:
        return Polygon()


def _base_support(layer):
    lower = layer.lower_layer
    if lower is None:
        return Polygon()
    return _layer_shape_from_lslices(lower)


def _fronts(support, overhang, cfg):
    """Generate reachable, fixed-spacing Wave fronts in millimetres."""
    if support.is_empty or overhang.is_empty:
        return []

    spacing = max(0.08, float(cfg["line_spacing"]))
    overlap = max(0.0, float(cfg["perimeter_overlap"]))
    base = 0.5 * spacing - overlap
    target = overhang.buffer(1e-7)
    max_iterations = max(1, int(cfg["max_iterations"]))
    has_hole = any(poly.interiors for poly in _iter_polygons(overhang))
    obstacle_aware = has_hole
    domain = support.union(target) if obstacle_aware else None
    reachable = support
    tracks = []

    for index in range(max_iterations):
        distance = base + index * spacing
        if distance <= 0:
            continue

        if not obstacle_aware:
            grown = support.buffer(distance)
            front = grown.boundary.intersection(target)
        else:
            previous = reachable
            if index == 0:
                reachable = support.buffer(distance).intersection(domain)
            else:
                reachable = reachable.buffer(spacing).intersection(domain)
            front = reachable.boundary.intersection(target)
            if index > 0:
                front = front.difference(previous.buffer(1e-6))
            try:
                front = linemerge(front)
            except (TypeError, ValueError):
                pass

        for line in _iter_lines(front):
            if line.length > spacing * 0.2:
                tracks.append(line)

        if not obstacle_aware:
            if grown.covers(target):
                break
        elif reachable.covers(target):
            break

    return tracks


def _ribbons(fronts, current, cfg):
    """Turn safe Wave centerlines into preview-visible narrow polygons."""
    width = max(0.12, float(cfg["line_width"]))
    minimum = max(0.0, float(cfg["min_wave_length"]))
    tolerance = max(0.0, float(cfg["simplify_tolerance"]))
    ribbons = []
    for front in fronts:
        if front.length < minimum:
            continue
        clean = front.simplify(tolerance, preserve_topology=False)
        # The source front is already a domain boundary intersection. If a
        # simplification ever leaves the current shape, use the safe source.
        if not current.buffer(0.002).covers(clean):
            clean = front
        ribbon = clean.buffer(width * 0.5, cap_style=2, join_style=2)
        ribbon = ribbon.intersection(current)
        ribbons.extend(poly for poly in _iter_polygons(ribbon)
                       if poly.area >= width * width * 0.05)
    return ribbons


def plan_layer_geometry(region_data, support, cfg):
    """Return (original shape, edited shape, ribbon polygons, front count)."""
    current = _union_shapes([
        shape for _, _, shapes in region_data for shape in shapes
    ])
    if current.is_empty or support.is_empty:
        return current, current, [], 0

    unsupported = current.difference(support.buffer(max(0.0, float(cfg["overhang_tol"]))))
    if unsupported.is_empty or unsupported.area < float(cfg["min_overhang_area"]):
        return current, current, [], 0

    fronts = _fronts(support, unsupported, cfg)
    ribbons = _ribbons(fronts, current, cfg)
    if not ribbons:
        return current, current, [], len(fronts)

    # Keep the material that is actually supported. The first Wave front stays
    # in the current-layer footprint, so it does not grow the model outward.
    kept = current.intersection(support.buffer(max(0.0, float(cfg["overhang_tol"]))))
    edited = _union_shapes([kept, *ribbons])
    return current, edited, ribbons, len(fronts)


def _ring_array(ring):
    coords = list(ring.coords)
    if len(coords) > 1 and coords[0] == coords[-1]:
        coords.pop()
    return np.asarray(
        [[int(round(x * _SCALE)), int(round(y * _SCALE))]
         for x, y in coords], dtype=np.int64)


def _host_expolygons(shape):
    """Convert a Shapely result to Orca host ExPolygon values."""
    for poly in _iter_polygons(shape):
        contour = _ring_array(poly.exterior)
        holes = [_ring_array(ring) for ring in poly.interiors]
        if len(contour) >= 3:
            yield orca.host.ExPolygon(contour, holes)


def _surface(surface_type, expolygon):
    return orca.host.Surface(surface_type, expolygon)


def _snapshot_regions(region_data):
    """Copy enough geometry to restore a layer if a later edit fails."""
    snapshots = []
    for region, surfaces, shapes in region_data:
        original = []
        for source, shape in zip(surfaces, shapes):
            for expolygon in _host_expolygons(shape):
                original.append(_surface(source.surface_type, expolygon))
        snapshots.append((region, original))
    return snapshots


def _restore_regions(snapshots):
    for region, original in snapshots:
        if original:
            region.slices.set(original)
        else:
            region.slices.clear()


def _replace_layer_regions(region_data, support, ribbons):
    """Clip old surfaces to support and put all Wave ribbons in region zero."""
    support_area = support.buffer(0.0)
    wave_type = orca.host.SurfaceType.stInternal
    for region_index, (region, surfaces, shapes) in enumerate(region_data):
        replacement = []
        for source, shape in zip(surfaces, shapes):
            kept = shape.intersection(support_area)
            for expolygon in _host_expolygons(kept):
                replacement.append(_surface(source.surface_type, expolygon))
        if region_index == 0:
            for ribbon in ribbons:
                for expolygon in _host_expolygons(ribbon):
                    replacement.append(_surface(wave_type, expolygon))
        if replacement:
            region.slices.set(replacement)
        else:
            region.slices.clear()


def _run_geometry(ctx, cfg, processed):
    if ctx.print is None or ctx.object is None:
        return 0, 0
    object_key = id(ctx.object)
    if object_key in processed:
        return 0, 0

    layers = list(ctx.object.layers())
    changed_layers = 0
    total_fronts = 0
    applied = []
    try:
        for layer in layers:
            region_data = _layer_region_shapes(layer)
            if not region_data:
                continue
            # Snapshot before planning or mutation. The lower layer may have
            # been updated by an earlier iteration, so planning stays bottom-up
            # while rollback remains possible for the whole object.
            snapshot = _snapshot_regions(region_data)
            support = _base_support(layer)
            current, edited, ribbons, front_count = plan_layer_geometry(
                region_data, support, cfg)
            if not ribbons or edited.equals(current):
                continue
            applied.append((layer, snapshot))
            _replace_layer_regions(region_data, support, ribbons)
            # This is the documented invariant-maintenance call after replacing
            # region slices. It refreshes merged layer islands for upper layers.
            layer.make_slices()
            changed_layers += 1
            total_fronts += front_count
    except BaseException:
        # No partial geometry should survive a failed experimental mutation.
        for layer, snapshot in reversed(applied):
            try:
                _restore_regions(snapshot)
                layer.make_slices()
            except BaseException:
                # Preserve the original host exception; diagnostics will show
                # that rollback itself was not available on this host.
                pass
        raise

    processed.add(object_key)
    return changed_layers, total_fronts


def log_path():
    override = os.environ.get("ORCA_PLUGIN_LOG_DIR")
    if override:
        return os.path.join(override, "orca-plugins.log")
    home = os.path.expanduser("~")
    downloads = os.path.join(home, "Downloads")
    return os.path.join(downloads if os.path.isdir(downloads) else home,
                        "orca-plugins.log")


def _log(message):
    try:
        with open(log_path(), "a", encoding="utf-8") as handle:
            handle.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')}  {message}\n")
    except BaseException:
        pass


def _log_loaded_once():
    global _LOADED_LOGGED
    if _LOADED_LOGGED:
        return
    _LOADED_LOGGED = True
    _log(f"Wave Overhangs Geometry v{PLUGIN_VERSION} loaded")


class WaveOverhangsGeometrySlicing(orca.slicing.SlicingPipelineCapabilityBase):
    def __init__(self, config=None):
        super().__init__(config)
        self._processed_objects = set()

    def get_name(self):
        return "Wave Overhangs Geometry"

    def get_default_config(self):
        return _DEFAULTS

    def execute(self, ctx):
        _log_loaded_once()
        cfg = _cfg(self)
        if not cfg["enabled"]:
            return orca.ExecutionResult.success(
                "Wave Overhangs Geometry: disabled")
        if np is None or shapely is None:
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                _DEPS_ERROR or "Wave Overhangs Geometry needs numpy and shapely")
        if ctx.step != orca.slicing.Step.posSlice:
            return orca.ExecutionResult.success()
        try:
            changed, fronts = _run_geometry(
                ctx, cfg, self._processed_objects)
        except BaseException as exc:
            _log(f"Wave Overhangs Geometry skipped safely: "
                 f"{type(exc).__name__}: {exc}")
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                "Wave Overhangs Geometry made no changes because the host "
                f"geometry API rejected the edit ({type(exc).__name__}).")
        if changed:
            return orca.ExecutionResult.success(
                f"Wave Overhangs Geometry: changed {changed} layer(s) with "
                f"{fronts} preview-visible Wave fronts")
        return orca.ExecutionResult.success(
            "Wave Overhangs Geometry: no reachable unsupported area was found")


class WaveOverhangsGeometryCheck(orca.script.ScriptPluginCapabilityBase):
    def get_name(self):
        return "Wave Overhangs Geometry - Check setup"

    def execute(self):
        _log_loaded_once()
        return orca.ExecutionResult.success(
            f"Wave Overhangs Geometry v{PLUGIN_VERSION} -- setup check\n"
            "mode: posSlice geometry mutation\n"
            "output: preview-visible Wave ribbon geometry\n"
            "safety: edits roll back for the whole object on failure\n"
            "limitation: current Python bindings expose existing paths read-only; "
            "Orca generates ordinary toolpaths from the Wave ribbons\n"
            "select this capability under Others -> Slicing Pipeline Plugin "
            "alongside the separate post-processing Wave plugin only if you "
            "intend to compare them")


@orca.plugin
class WaveOverhangsGeometryPlugin(orca.base):
    def register_capabilities(self):
        orca.register_capability(WaveOverhangsGeometrySlicing)
        orca.register_capability(WaveOverhangsGeometryCheck)
