# /// script
# requires-python = ">=3.12"
# dependencies = ["numpy>=2.0", "shapely>=2.0"]
#
# [tool.orcaslicer.plugin]
# name = "Wave Overhangs Geometry"
# description = "Experimental preview-visible Wave geometry for OrcaSlicer. Replaces reachable unsupported slice area with narrow Wave ribbons before perimeters and infill are generated. | What's new in v0.1.3: Split preview roles: the outer overhang edge is now one non-bridge wall shell, while only the interior Wave ribbons are bridge-classified."
# author = "Wave Overhangs plugin lane"
# version = "0.1.3"
# ///
"""Preview-visible geometry-stage Wave Overhangs prototype.

This is intentionally a separate plugin from Wave Overhangs. The stable plugin
waits for exported Bridge G-code and is still the fallback. This prototype runs
at ``posSlice`` and edits Orca's live slicing graph instead:

* the previous layer supplies the support footprint;
* the current slice is split into supported material and reachable overhang;
* fixed-spacing Wave fronts are turned into narrow polygon ribbons;
* the ribbons are written back into LayerRegion.slices;
* Orca's normal perimeter/infill stages continue from that edited geometry.

The current Python host API does not provide a writable ExtrusionPath collection.
Therefore this plugin cannot inject a raw Wave polyline directly into Orca's
extrusion graph. It creates preview-visible Wave ribbon geometry, which Orca
then turns into ordinary toolpaths. That distinction is reported by Check setup
and is kept visible in the documentation; it must not be described as a direct
ExtrusionPath injector until Orca exposes that mutator.

Every geometry edit is contained in the execute call. Invalid or incomplete
host bindings leave the slice unchanged and return a recoverable result.
"""
from __future__ import annotations

import json
import math
import os
import time

try:
    # Import at module load so Orca's audit hook cannot block a lazy import
    # during execute(). Orca installs these dependencies for the plugin; the
    # fallback keeps Diagnostics and the audit test usable if they are absent.
    import numpy as np
    import shapely
    from shapely.geometry import GeometryCollection, LineString, MultiPolygon, Polygon
    from shapely.ops import linemerge, unary_union
    _DEPS_ERROR = None
except ImportError as exc:  # pragma: no cover - exercised without Orca deps
    np = None
    shapely = None
    GeometryCollection = LineString = MultiPolygon = Polygon = None
    linemerge = unary_union = None
    _DEPS_ERROR = f"Wave Overhangs Geometry needs numpy and shapely: {exc}"

import orca


PLUGIN_VERSION = "0.1.3"
MARKER = "; wave-overhangs-geometry v0.1.3"
_SCALE = 1_000_000.0
_LOADED_LOGGED = False

_DEFAULTS = {
    "enabled": True,
    "line_spacing": 0.35,
    "line_width": 0.40,
    "overhang_tol": 0.05,
    "min_overhang_area": 0.5,
    "perimeter_overlap": 0.10,
    "min_wave_length": 1.0,
    "min_preview_island_area": 0.12,
    "outer_boundary_band": "auto",
    "simplify_tolerance": 0.05,
    "max_iterations": 400,
}

# --- BEGIN changelog (generated by tools/sync_changelog.py) ---
CHANGELOG_RECENT = """\
v0.1.3  (2026-10-01)
   * Split preview roles: the outer overhang edge is now one non-bridge
     wall shell, while only the interior Wave ribbons are
     bridge-classified.
   * Clipped bridge-classified Waves inside that wall shell so they do
     not spill outside the visible overhang perimeter.
   * Kept the support-outward ordering bias and added a guard that
     refuses to emit the wall shell by itself if no anchored Wave ribbon
     survives cleanup.

v0.1.2  (2026-10-01)
   * Cleaned preview output by dropping tiny clipped ribbon crumbs.
   * Preserved a continuous outer overhang boundary shell so the visible
     wall does not disappear between Wave ribbons.
   * Reclassified generated Wave replacement geometry as bridge surfaces
     and handed bridge pieces to Orca in supported-edge-to-outer-edge
     order.

v0.1.1  (2026-10-01)
   * Fixed real-Orca registration by constructing the slicing capability
     base with no Python arguments. The local fake Orca harness now
     enforces the same no-argument base-constructor contract so this
     failure is caught before install.
"""
# --- END changelog ---


def _cfg(capability):
    """Read the capability JSON without depending on a preset key."""
    cfg = dict(_DEFAULTS)
    try:
        raw = capability.get_config()
        if raw:
            data = json.loads(raw) if isinstance(raw, str) else raw
            if isinstance(data, dict):
                cfg.update(data)
    except BaseException:
        # Bad optional configuration must not damage the user's slice.
        pass
    return cfg


def _number(value, fallback):
    """Best-effort numeric config parsing that fails back safely."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return fallback


def _wave_width(cfg):
    return max(0.12, _number(cfg.get("line_width"), _DEFAULTS["line_width"]))


def _boundary_band_width(cfg):
    raw = cfg.get("outer_boundary_band", "auto")
    width = _wave_width(cfg)
    if isinstance(raw, str) and raw.strip().lower() == "auto":
        return width
    return max(0.0, _number(raw, width))


def _preview_area_floor(cfg, width):
    # A front shorter than min_wave_length is already removed. This second
    # guard catches tiny polygon crumbs created by clipping at corners/holes.
    configured = max(0.0, _number(cfg.get("min_preview_island_area"),
                                  _DEFAULTS["min_preview_island_area"]))
    by_width = width * max(0.0, _number(cfg.get("min_wave_length"), 1.0)) * 0.35
    return max(configured, by_width, width * width * 0.25)


def _iter_polygons(geom):
    if geom is None or geom.is_empty:
        return
    if isinstance(geom, Polygon):
        yield geom
    elif isinstance(geom, MultiPolygon):
        yield from geom.geoms
    elif isinstance(geom, GeometryCollection):
        for child in geom.geoms:
            yield from _iter_polygons(child)


def _iter_lines(geom):
    if geom is None or geom.is_empty:
        return
    if isinstance(geom, LineString):
        yield geom
    elif hasattr(geom, "geoms"):
        for child in geom.geoms:
            yield from _iter_lines(child)


def _ring_xy(ring):
    """Return a Shapely ring without its repeated closing coordinate."""
    coords = [(float(p.x) / _SCALE, float(p.y) / _SCALE)
              for p in ring.points]
    if len(coords) > 1 and coords[0] == coords[-1]:
        coords.pop()
    return coords


def _expolygon_shape(expolygon):
    contour = _ring_xy(expolygon.contour)
    holes = [_ring_xy(hole) for hole in expolygon.holes]
    if len(contour) < 3:
        return Polygon()
    shape = Polygon(contour, holes)
    return shape if shape.is_valid else shape.buffer(0)


def _surface_shape(surface):
    return _expolygon_shape(surface.expolygon)


def _union_shapes(shapes):
    shapes = [shape for shape in shapes if shape is not None and not shape.is_empty]
    if not shapes:
        return Polygon()
    result = unary_union(shapes)
    return result if result.is_valid else result.buffer(0)


def _layer_region_shapes(layer):
    """Read the current region surfaces before any mutation."""
    regions = list(layer.regions())
    data = []
    for region in regions:
        surfaces = list(region.slices.surfaces)
        data.append((region, surfaces, [_surface_shape(s) for s in surfaces]))
    return data


def _layer_shape_from_lslices(layer):
    try:
        return _union_shapes([_expolygon_shape(exp) for exp in layer.lslices()])
    except BaseException:
        return Polygon()


def _base_support(layer):
    lower = layer.lower_layer
    if lower is None:
        return Polygon()
    return _layer_shape_from_lslices(lower)


def _fronts(support, overhang, cfg):
    """Generate reachable, fixed-spacing Wave fronts in millimetres."""
    if support.is_empty or overhang.is_empty:
        return []

    spacing = max(0.08, _number(cfg.get("line_spacing"), _DEFAULTS["line_spacing"]))
    overlap = max(0.0, _number(cfg.get("perimeter_overlap"), _DEFAULTS["perimeter_overlap"]))
    base = 0.5 * spacing - overlap
    target = overhang.buffer(1e-7)
    max_iterations = max(1, int(_number(cfg.get("max_iterations"),
                                      _DEFAULTS["max_iterations"])))
    has_hole = any(poly.interiors for poly in _iter_polygons(overhang))
    obstacle_aware = has_hole
    domain = support.union(target) if obstacle_aware else None
    reachable = support
    tracks = []

    for index in range(max_iterations):
        distance = base + index * spacing
        if distance <= 0:
            continue

        if not obstacle_aware:
            grown = support.buffer(distance)
            front = grown.boundary.intersection(target)
        else:
            previous = reachable
            if index == 0:
                reachable = support.buffer(distance).intersection(domain)
            else:
                reachable = reachable.buffer(spacing).intersection(domain)
            front = reachable.boundary.intersection(target)
            if index > 0:
                front = front.difference(previous.buffer(1e-6))
            try:
                front = linemerge(front)
            except (TypeError, ValueError):
                pass

        for line in _iter_lines(front):
            if line.length > spacing * 0.2:
                tracks.append(line)

        if not obstacle_aware:
            if grown.covers(target):
                break
        elif reachable.covers(target):
            break

    return tracks


def _sort_near_to_far(geoms, support):
    """Stable order: anchored material first, thin-air boundary last."""
    def key(geom):
        c = geom.representative_point()
        return (support.distance(geom), c.x, c.y, geom.area)
    return sorted(geoms, key=key)


def _large_enough_preview(poly, cfg, width):
    if poly.is_empty:
        return False
    min_area = _preview_area_floor(cfg, width)
    if poly.area < min_area:
        return False
    min_span = max(0.20, width * 0.75)
    minx, miny, maxx, maxy = poly.bounds
    return max(maxx - minx, maxy - miny) >= min_span


def _ribbons(fronts, current, support, cfg):
    """Turn safe Wave centerlines into preview-visible narrow polygons."""
    width = _wave_width(cfg)
    minimum = max(0.0, _number(cfg.get("min_wave_length"),
                               _DEFAULTS["min_wave_length"]))
    tolerance = max(0.0, _number(cfg.get("simplify_tolerance"),
                                 _DEFAULTS["simplify_tolerance"]))
    ribbons = []
    for front in fronts:
        if front.length < minimum:
            continue
        clean = front.simplify(tolerance, preserve_topology=False)
        # The source front is already a domain boundary intersection. If a
        # simplification ever leaves the current shape, use the safe source.
        if not current.buffer(0.002).covers(clean):
            clean = front
        ribbon = clean.buffer(width * 0.5, cap_style=2, join_style=2)
        ribbon = ribbon.intersection(current)
        for poly in _iter_polygons(ribbon):
            if _large_enough_preview(poly, cfg, width):
                ribbons.append(poly)
    return _sort_near_to_far(ribbons, support)


def _outer_boundary_band(current, unsupported, support, cfg):
    """Keep one non-bridge shell on the visible overhang edge.

    Without this band the preview sees only individual Wave stripes, so the
    overhanging wall/perimeter is broken into fragments. The shell is clipped
    to the unsupported boundary of the original slice, which keeps the wall
    inside the model instead of growing it outward. It is intentionally *not*
    bridge-classified; only the Wave ribbons inside it are bridge surfaces.
    """
    width = _boundary_band_width(cfg)
    if width <= 0:
        return []
    raw_band = current.boundary.buffer(width * 0.5, cap_style=2, join_style=2)
    band = raw_band.intersection(current).intersection(unsupported.buffer(width * 0.5))
    # Keep the overhang edge as a shell, but drop tiny crumbs where the band is
    # sliced by support intersections or hole tangencies.
    pieces = [poly for poly in _iter_polygons(band)
              if _large_enough_preview(poly, cfg, width)]
    return _sort_near_to_far(pieces, support)


def _clip_inside_shell(current, shell_parts):
    """Domain for bridge ribbons: inside the original slice, away from the shell."""
    if not shell_parts:
        return current
    shell = _union_shapes(shell_parts)
    if shell.is_empty:
        return current
    inside = current.difference(shell.buffer(0.005))
    return inside if not inside.is_empty else current


def plan_layer_geometry(region_data, support, cfg):
    """Return (original, edited, bridge polygons, shell polygons, front count)."""
    current = _union_shapes([
        shape for _, _, shapes in region_data for shape in shapes
    ])
    if current.is_empty or support.is_empty:
        return current, current, [], [], 0

    overhang_tol = max(0.0, _number(cfg.get("overhang_tol"),
                                    _DEFAULTS["overhang_tol"]))
    unsupported = current.difference(support.buffer(overhang_tol))
    min_area = max(0.0, _number(cfg.get("min_overhang_area"),
                                _DEFAULTS["min_overhang_area"]))
    if unsupported.is_empty or unsupported.area < min_area:
        return current, current, [], [], 0

    fronts = _fronts(support, unsupported, cfg)
    boundary_band = _outer_boundary_band(current, unsupported, support, cfg)
    wave_domain = _clip_inside_shell(current, boundary_band)
    ribbons = _ribbons(fronts, wave_domain, support, cfg)
    if not ribbons:
        # Never emit only the outside shell; that would deliberately start in
        # thin air. The shell is kept only when support-anchored Wave ribbons
        # also survived cleanup.
        return current, current, [], [], len(fronts)
    bridge_parts = _sort_near_to_far(ribbons, support)
    wall_parts = _sort_near_to_far(boundary_band, support)

    # Keep the material that is actually supported. The first Wave front stays
    # in the current-layer footprint, so it does not grow the model outward.
    kept = current.intersection(support.buffer(overhang_tol))
    edited = _union_shapes([kept, *wall_parts, *bridge_parts])
    return current, edited, bridge_parts, wall_parts, len(fronts)


def _ring_array(ring):
    coords = list(ring.coords)
    if len(coords) > 1 and coords[0] == coords[-1]:
        coords.pop()
    return np.asarray(
        [[int(round(x * _SCALE)), int(round(y * _SCALE))]
         for x, y in coords], dtype=np.int64)


def _host_expolygons(shape):
    """Convert a Shapely result to Orca host ExPolygon values."""
    for poly in _iter_polygons(shape):
        contour = _ring_array(poly.exterior)
        holes = [_ring_array(ring) for ring in poly.interiors]
        if len(contour) >= 3:
            yield orca.host.ExPolygon(contour, holes)


def _surface(surface_type, expolygon):
    return orca.host.Surface(surface_type, expolygon)


def _surface_type_named(*names):
    types = getattr(orca.host, "SurfaceType", None)
    for name in names:
        if types is not None and hasattr(types, name):
            return getattr(types, name)
    raise AttributeError("orca.host.SurfaceType has none of: " + ", ".join(names))


def _bridge_surface_type():
    """Preview role for interior Wave replacement geometry."""
    return _surface_type_named("stBottomBridge", "stInternalBridge", "stBottom", "stInternal")


def _wall_surface_type():
    """Preview role for the single outer overhang wall shell."""
    return _surface_type_named("stBottom", "stInternal", "stPerimeter", "stBottomBridge")


def _snapshot_regions(region_data):
    """Copy enough geometry to restore a layer if a later edit fails."""
    snapshots = []
    for region, surfaces, shapes in region_data:
        original = []
        for source, shape in zip(surfaces, shapes):
            for expolygon in _host_expolygons(shape):
                original.append(_surface(source.surface_type, expolygon))
        snapshots.append((region, original))
    return snapshots


def _restore_regions(snapshots):
    for region, original in snapshots:
        if original:
            region.slices.set(original)
        else:
            region.slices.clear()


def _replace_layer_regions(region_data, support, bridge_parts, wall_parts):
    """Clip old surfaces to support, then add Wave bridges inside one wall shell."""
    support_area = support.buffer(0.0)
    wave_type = _bridge_surface_type()
    wall_type = _wall_surface_type()
    for region_index, (region, surfaces, shapes) in enumerate(region_data):
        replacement = []
        for source, shape in zip(surfaces, shapes):
            kept = shape.intersection(support_area)
            for expolygon in _host_expolygons(kept):
                replacement.append(_surface(source.surface_type, expolygon))
        if region_index == 0:
            # Hand Orca the anchored Wave bridges first, from support outward.
            # The outside shell comes last and is non-bridge so preview can show
            # one overhang wall containing bridge-classified Wave fill.
            for part in bridge_parts:
                for expolygon in _host_expolygons(part):
                    replacement.append(_surface(wave_type, expolygon))
            for part in wall_parts:
                for expolygon in _host_expolygons(part):
                    replacement.append(_surface(wall_type, expolygon))
        if replacement:
            region.slices.set(replacement)
        else:
            region.slices.clear()


def _run_geometry(ctx, cfg, processed):
    if ctx.print is None or ctx.object is None:
        return 0, 0
    object_key = id(ctx.object)
    if object_key in processed:
        return 0, 0

    layers = list(ctx.object.layers())
    changed_layers = 0
    total_fronts = 0
    applied = []
    try:
        for layer in layers:
            region_data = _layer_region_shapes(layer)
            if not region_data:
                continue
            # Snapshot before planning or mutation. The lower layer may have
            # been updated by an earlier iteration, so planning stays bottom-up
            # while rollback remains possible for the whole object.
            snapshot = _snapshot_regions(region_data)
            support = _base_support(layer)
            current, edited, bridge_parts, wall_parts, front_count = plan_layer_geometry(
                region_data, support, cfg)
            if not bridge_parts or edited.equals(current):
                continue
            applied.append((layer, snapshot))
            _replace_layer_regions(region_data, support, bridge_parts, wall_parts)
            # This is the documented invariant-maintenance call after replacing
            # region slices. It refreshes merged layer islands for upper layers.
            layer.make_slices()
            changed_layers += 1
            total_fronts += front_count
    except BaseException:
        # No partial geometry should survive a failed experimental mutation.
        for layer, snapshot in reversed(applied):
            try:
                _restore_regions(snapshot)
                layer.make_slices()
            except BaseException:
                # Preserve the original host exception; diagnostics will show
                # that rollback itself was not available on this host.
                pass
        raise

    processed.add(object_key)
    return changed_layers, total_fronts


LOG_NAME = "orca-plugins.log"


def _plugin_storage_dir():
    """No-prompt plugin storage folder, with a local fallback for tests."""
    try:
        storage = orca.host.plugin.storage()
        if storage:
            return storage
    except BaseException:
        pass
    return os.path.dirname(os.path.abspath(__file__))


def log_path():
    """Default no-prompt plugin-storage log path."""
    override = os.environ.get("ORCA_PLUGIN_LOG_DIR")
    if override:
        return os.path.join(override, LOG_NAME)
    return os.path.join(_plugin_storage_dir(), LOG_NAME)


def _log(message):
    try:
        with open(log_path(), "a", encoding="utf-8") as handle:
            handle.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')}  {message}\n")
    except BaseException:
        pass


def _log_loaded_once():
    global _LOADED_LOGGED
    if _LOADED_LOGGED:
        return
    _LOADED_LOGGED = True
    _log(f"Wave Overhangs Geometry v{PLUGIN_VERSION} loaded")


class WaveOverhangsGeometrySlicing(orca.slicing.SlicingPipelineCapabilityBase):
    def __init__(self):
        # Real Orca constructs capability bases with no Python arguments, then
        # exposes configuration through get_config(). Passing None here breaks
        # registration on Orca even though the local fake host used to allow it.
        super().__init__()
        self._processed_objects = set()

    def get_name(self):
        return "Wave Overhangs Geometry"

    def get_default_config(self):
        return _DEFAULTS

    def execute(self, ctx):
        _log_loaded_once()
        cfg = _cfg(self)
        if not cfg["enabled"]:
            return orca.ExecutionResult.success(
                "Wave Overhangs Geometry: disabled")
        if np is None or shapely is None:
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                _DEPS_ERROR or "Wave Overhangs Geometry needs numpy and shapely")
        if ctx.step != orca.slicing.Step.posSlice:
            return orca.ExecutionResult.success()
        try:
            changed, fronts = _run_geometry(
                ctx, cfg, self._processed_objects)
        except BaseException as exc:
            _log(f"Wave Overhangs Geometry skipped safely: "
                 f"{type(exc).__name__}: {exc}")
            return orca.ExecutionResult.failure(
                orca.PluginResult.RecoverableError,
                "Wave Overhangs Geometry made no changes because the host "
                f"geometry API rejected the edit ({type(exc).__name__}).")
        if changed:
            return orca.ExecutionResult.success(
                f"Wave Overhangs Geometry: changed {changed} layer(s) with "
                f"{fronts} preview-visible Wave fronts")
        return orca.ExecutionResult.success(
            "Wave Overhangs Geometry: no reachable unsupported area was found")


class WaveOverhangsGeometryCheck(orca.script.ScriptPluginCapabilityBase):
    def get_name(self):
        return "Wave Overhangs Geometry - Check setup"

    def execute(self):
        _log_loaded_once()
        return orca.ExecutionResult.success(
            f"Wave Overhangs Geometry v{PLUGIN_VERSION} -- setup check\n"
            "mode: posSlice geometry mutation\n"
            "output: one outer overhang-wall shell containing bridge-classified Waves\n"
            "order: bridge pieces are handed to Orca from supported edge outward\n"
            "log: routine diagnostics use plugin storage to avoid approval prompts\n"
            f"log path: {log_path()}\n"
            "safety: edits roll back for the whole object on failure\n"
            "limitation: current Python bindings expose existing paths read-only; "
            "Orca generates ordinary toolpaths from the Wave ribbons\n"
            "select this capability under Others -> Slicing Pipeline Plugin "
            "alongside the separate post-processing Wave plugin only if you "
            "intend to compare them")


@orca.plugin
class WaveOverhangsGeometryPlugin(orca.base):
    def register_capabilities(self):
        orca.register_capability(WaveOverhangsGeometrySlicing)
        orca.register_capability(WaveOverhangsGeometryCheck)
