#!/usr/bin/env python3
"""Copy each plugin's CHANGELOG.md into the plugin file, so OrcaSlicer can show it.

    python3 tools/sync_changelog.py            # write
    python3 tools/sync_changelog.py --check    # fail if stale, write nothing

WHY
  OrcaSlicer's Plugins dialog has a Changelog tab, but for a side-loaded .py
  plugin there is no documented way to populate it: the PEP 723 parser reads
  only name, description, author, version, requires-python and dependencies,
  and the descriptor's changelog field is filled from the cloud listing.

  So the changelog is carried two other ways, both of which the owner can
  actually see from inside OrcaSlicer:

    1. CHANGELOG_RECENT, a constant inside the plugin, printed by the
       "Check setup" capability.
    2. a one-line "What's new in vX.Y.Z: ..." suffix on the PEP 723
       description, which Orca shows in the Description tab — the tab you
       look at when you are adding the plugin.

  Both are generated from plugins/<id>/CHANGELOG.md by this script, so the
  changelog is written once, in one place, in Markdown.

  Nothing here runs at plugin import time; it is all string constants.
"""
import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent

PLUGINS = [
    ("plugins/unlayered-infill/CHANGELOG.md",
     "plugins/unlayered-infill/unlayered_infill_orca.py"),
    ("plugins/wave-overhangs/CHANGELOG.md",
     "plugins/wave-overhangs/wave_overhangs_orca.py"),
    ("plugins/wave-overhangs-geometry/CHANGELOG.md",
     "plugins/wave-overhangs-geometry/wave_overhangs_geometry_orca.py"),
]

N_RELEASES = 3          # how many releases to carry inside the plugin
WIDTH = 72

BEGIN = "# --- BEGIN changelog (generated by tools/sync_changelog.py) ---"
END = "# --- END changelog ---"
BLOCK_RE = re.compile(
    re.escape(BEGIN) + r"\n.*?" + re.escape(END), re.DOTALL)

# "## 0.3.1 — 2026-09-30"  (em dash or plain hyphen)
HEADING_RE = re.compile(r"^##\s+(\d+\.\d+\.\d+)\s*[—–-]\s*(\S+)\s*$", re.MULTILINE)


def parse_changelog(md_path):
    """-> [(version, date, [bullet, ...]), ...] newest first."""
    text = md_path.read_text(encoding="utf-8")
    heads = list(HEADING_RE.finditer(text))
    if not heads:
        raise SystemExit(f"{md_path}: no '## <version> - <date>' headings found")
    out = []
    for i, h in enumerate(heads):
        body = text[h.end(): heads[i + 1].start() if i + 1 < len(heads) else len(text)]
        bullets = []
        for raw in re.split(r"\n(?=\* )", body.strip()):
            raw = raw.strip()
            if not raw.startswith("* "):
                continue
            # collapse the wrapped Markdown bullet into one line of plain text
            one = " ".join(raw[2:].split())
            one = re.sub(r"\*\*(.+?)\*\*", r"\1", one)      # bold
            one = re.sub(r"`([^`]+)`", r"\1", one)          # code
            one = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", one)   # links
            bullets.append(one)
        out.append((h.group(1), h.group(2), bullets))
    return out


def wrap(text, indent, width=WIDTH):
    words, lines, cur = text.split(), [], indent
    for w in words:
        if cur.strip() and len(cur) + 1 + len(w) > width:
            lines.append(cur.rstrip())
            cur = indent + w
        else:
            cur = (cur + " " + w) if cur.strip() else cur + w
    if cur.strip():
        lines.append(cur.rstrip())
    return lines


def render_constant(releases):
    lines = []
    for ver, date, bullets in releases[:N_RELEASES]:
        lines.append(f"v{ver}  ({date})")
        for b in bullets:
            body = wrap(b, "     ")
            body[0] = "   * " + body[0].lstrip()
            lines.extend(body)
        lines.append("")
    while lines and not lines[-1]:
        lines.pop()
    body = "\n".join(lines).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return f'{BEGIN}\nCHANGELOG_RECENT = """\\\n{body}\n"""\n{END}'


def first_sentence(bullets):
    if not bullets:
        return "see CHANGELOG.md"
    s = bullets[0]
    m = re.search(r"(?<=[.!?])\s", s)
    s = s[:m.start()] if m else s
    s = s.rstrip(".")
    return (s[:157] + "...") if len(s) > 160 else s


def sync_one(md_rel, py_rel, check):
    md, py = REPO / md_rel, REPO / py_rel
    releases = parse_changelog(md)
    src = py.read_text(encoding="utf-8")
    problems, before = [], src

    # ---- 1. the CHANGELOG_RECENT constant --------------------------------
    if not BLOCK_RE.search(src):
        problems.append(f"{py_rel}: no changelog block "
                        f"({BEGIN!r} ... {END!r}) to fill")
    else:
        src = BLOCK_RE.sub(lambda _: render_constant(releases), src, count=1)

    # ---- 2. the "What's new" suffix on the PEP 723 description -----------
    top_ver, _, top_bullets = releases[0]
    whats_new = f"What's new in v{top_ver}: {first_sentence(top_bullets)}."
    m = re.search(r'^# description = "(.*)"$', src, re.MULTILINE)
    if not m:
        problems.append(f"{py_rel}: no PEP 723 description line")
    else:
        base = re.sub(r"\s*\|\s*What's new in v.*$", "", m.group(1)).rstrip()
        new_desc = f'# description = "{base} | {whats_new}"'
        src = src[:m.start()] + new_desc + src[m.end():]

    # ---- 3. the plugin version must match the newest changelog entry -----
    pv = re.search(r'^PLUGIN_VERSION = "([^"]+)"$', src, re.MULTILINE)
    if pv and pv.group(1) != top_ver:
        problems.append(
            f"{py_rel}: PLUGIN_VERSION is {pv.group(1)} but the newest entry "
            f"in {md_rel} is {top_ver}. Add the changelog entry for this "
            f"release (hard rule 3).")

    changed = src != before
    if problems:
        return problems, changed
    if changed and not check:
        py.write_text(src, encoding="utf-8")
    return [], changed


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if anything is out of date; write nothing")
    args = ap.parse_args()

    all_problems, stale = [], []
    for md_rel, py_rel in PLUGINS:
        problems, changed = sync_one(md_rel, py_rel, args.check)
        all_problems += problems
        if changed:
            stale.append(py_rel)
            print(f"{'STALE' if args.check else 'synced'}: {py_rel} <- {md_rel}")
        else:
            print(f"ok: {py_rel} matches {md_rel}")

    for p in all_problems:
        print(f"PROBLEM: {p}")
    if all_problems:
        return 1
    if args.check and stale:
        print("\nRun: python3 tools/sync_changelog.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
